// Code generated by tommy; DO NOT EDIT.

package options_print

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type abbreviationsV0Document struct {
	data     abbreviationsV0
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeabbreviationsV0(input []byte) (*abbreviationsV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &abbreviationsV0Document{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "hinweisen"); err == nil {
		d.data.ZettelIds = &v
		d.consumed["hinweisen"] = true
	}
	if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "shas"); err == nil {
		d.data.Shas = &v
		d.consumed["shas"] = true
	}

	return d, nil
}

func (d *abbreviationsV0Document) Data() *abbreviationsV0 { return &d.data }

func (d *abbreviationsV0Document) Encode() ([]byte, error) {
	if d.data.ZettelIds != nil {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "hinweisen", *d.data.ZettelIds); err != nil {
			return nil, err
		}
	}
	if d.data.Shas != nil {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "shas", *d.data.Shas); err != nil {
			return nil, err
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *abbreviationsV0Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
