// Code generated by tommy; DO NOT EDIT.

package type_blobs

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type ReferencesConfigDocument struct {
	data     ReferencesConfig
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeReferencesConfig(input []byte) (*ReferencesConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &ReferencesConfigDocument{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "description"); err == nil {
		d.data.Description = v
		d.consumed["description"] = true
	}
	if v, err := document.GetFromContainer[[]string](d.cstDoc, d.cstDoc.Root(), "shell"); err == nil {
		d.data.Shell = v
		d.consumed["shell"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "script"); err == nil {
		d.data.Script = v
		d.consumed["script"] = true
	}
	if tableNode := d.cstDoc.FindTable("env"); tableNode != nil {
		d.data.Env = document.GetStringMapFromTable(tableNode)
		d.consumed["env"] = true
		document.MarkAllConsumed(tableNode, "env", d.consumed)
	}
	if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "optional"); err == nil {
		d.data.Optional = v
		d.consumed["optional"] = true
	}

	return d, nil
}

func (d *ReferencesConfigDocument) Data() *ReferencesConfig { return &d.data }

func (d *ReferencesConfigDocument) Encode() ([]byte, error) {
	if d.data.Description != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "description") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "description", d.data.Description); err != nil {
			return nil, err
		}
	}
	if len(d.data.Shell) > 0 || d.cstDoc.HasInContainer(d.cstDoc.Root(), "shell") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "shell", d.data.Shell); err != nil {
			return nil, err
		}
	}
	if d.data.Script != "" {
		if err := d.cstDoc.SetMultilineInContainer(d.cstDoc.Root(), "script", d.data.Script); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "script")
	}
	if len(d.data.Env) > 0 {
		tableNode := d.cstDoc.EnsureTable("env")
		document.DeleteAllInContainer(tableNode)
		for k, v := range d.data.Env {
			if err := d.cstDoc.SetInContainer(tableNode, k, v); err != nil {
				return nil, err
			}
		}
	}
	if d.data.Optional != false {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "optional", d.data.Optional); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "optional")
	}

	return d.cstDoc.Bytes(), nil
}

func (d *ReferencesConfigDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func (d *ReferencesConfigDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *ReferencesConfigDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *ReferencesConfigDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *ReferencesConfigDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeReferencesConfigInto(data *ReferencesConfig, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	if v, err := document.GetFromContainer[string](doc, container, "description"); err == nil {
		data.Description = v
		consumed[keyPrefix+"description"] = true
	}
	if v, err := document.GetFromContainer[[]string](doc, container, "shell"); err == nil {
		data.Shell = v
		consumed[keyPrefix+"shell"] = true
	}
	if v, err := document.GetFromContainer[string](doc, container, "script"); err == nil {
		data.Script = v
		consumed[keyPrefix+"script"] = true
	}
	if tableNode := doc.FindTableInContainer(container, "env"); tableNode != nil {
		data.Env = document.GetStringMapFromTable(tableNode)
		consumed[keyPrefix+"env"] = true
		document.MarkAllConsumed(tableNode, keyPrefix+"env", consumed)
	}
	if v, err := document.GetFromContainer[bool](doc, container, "optional"); err == nil {
		data.Optional = v
		consumed[keyPrefix+"optional"] = true
	}

	return nil
}

func EncodeReferencesConfigFrom(data *ReferencesConfig, doc *document.Document, container *cst.Node) error {
	if data.Description != "" || doc.HasInContainer(container, "description") {
		if err := doc.SetInContainer(container, "description", data.Description); err != nil {
			return err
		}
	}
	if len(data.Shell) > 0 || doc.HasInContainer(container, "shell") {
		if err := doc.SetInContainer(container, "shell", data.Shell); err != nil {
			return err
		}
	}
	if data.Script != "" {
		if err := doc.SetMultilineInContainer(container, "script", data.Script); err != nil {
			return err
		}
	} else {
		_ = doc.DeleteFromContainer(container, "script")
	}
	if len(data.Env) > 0 {
		tableNode := doc.EnsureTableInContainer(container, "env")
		document.DeleteAllInContainer(tableNode)
		for k, v := range data.Env {
			if err := doc.SetInContainer(tableNode, k, v); err != nil {
				return err
			}
		}
	}
	if data.Optional != false {
		if err := doc.SetInContainer(container, "optional", data.Optional); err != nil {
			return err
		}
	} else {
		_ = doc.DeleteFromContainer(container, "optional")
	}

	return nil
}
