// Code generated by tommy 0.4.7 (68213be); DO NOT EDIT.

package repo_blobs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlUriV0Document struct {
	data   TomlUriV0
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlUriV0(input []byte) (*TomlUriV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlUriV0Document{
		cstDoc: doc,
		model:  model,
	}

	if _vPublicKey, _ok := model.Get("public-key"); _ok && _vPublicKey.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPublicKey.Leaf); _xok {
			if err := d.data.PublicKey.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("public-key: %w", err)
			}
			_vPublicKey.MarkConsumed()
		}
	}
	if _vUri, _ok := model.Get("uri"); _ok && _vUri.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUri.Leaf); _xok {
			if err := d.data.Uri.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("uri: %w", err)
			}
			_vUri.MarkConsumed()
		}
	}
	return d, nil
}

func (d *TomlUriV0Document) Data() *TomlUriV0 {
	return &d.data
}

func (d *TomlUriV0Document) Encode() ([]byte, error) {
	{
		v, err := d.data.PublicKey.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("public-key: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "public-key", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.Uri.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("uri: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "uri", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlUriV0Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlUriV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlUriV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlUriV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlUriV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlUriV0Into(data *TomlUriV0, sub *cst.Value) error {
	if _vPublicKey, _ok := sub.Get("public-key"); _ok && _vPublicKey.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPublicKey.Leaf); _xok {
			if err := data.PublicKey.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("public-key: %w", err)
			}
			_vPublicKey.MarkConsumed()
		}
	}
	if _vUri, _ok := sub.Get("uri"); _ok && _vUri.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vUri.Leaf); _xok {
			if err := data.Uri.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("uri: %w", err)
			}
			_vUri.MarkConsumed()
		}
	}
	return nil
}

func EncodeTomlUriV0From(data *TomlUriV0, doc *document.Document, container *cst.Node) error {
	{
		v, err := data.PublicKey.MarshalText()
		if err != nil {
			return fmt.Errorf("public-key: %w", err)
		}
		if err := cst.SetAny(container, "public-key", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.Uri.MarshalText()
		if err != nil {
			return fmt.Errorf("uri: %w", err)
		}
		if err := cst.SetAny(container, "uri", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
