// Code generated by tommy 0.5.0 (47364f2); DO NOT EDIT.

package repo_blobs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlXDGV0Document struct {
	data   TomlXDGV0
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlXDGV0(input []byte) (*TomlXDGV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	return decodeTomlXDGV0Parsed(doc)
}

// DecodeTomlXDGV0Strict is DecodeTomlXDGV0 for input that must be exactly what it
// claims: it returns a *cst.SyntaxError when input is not well-formed TOML and
// *cst.TypeError values when a key's TOML type does not match its field, where
// DecodeTomlXDGV0 would decode leniently. Keys no field claims are not errors; they
// stay in Undecoded.
func DecodeTomlXDGV0Strict(input []byte) (*TomlXDGV0Document, error) {
	doc, err := document.ParseStrict(input)
	if err != nil {
		return nil, err
	}
	d, err := decodeTomlXDGV0Parsed(doc)
	if err != nil {
		return nil, err
	}
	if err := d.model.TypeErrors(); err != nil {
		return nil, err
	}
	return d, nil
}

func decodeTomlXDGV0Parsed(doc *document.Document) (*TomlXDGV0Document, error) {
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlXDGV0Document{
		cstDoc: doc,
		model:  model,
	}

	if _vPublicKey, _ok := model.Field("public-key"); _ok && _vPublicKey.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPublicKey.Leaf); _xok {
			if err := d.data.PublicKey.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("public-key: %w", err)
			}
			_vPublicKey.MarkConsumedText()
		}
	}
	if _vData, _ok := model.Field("data"); _ok && _vData.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vData.Leaf); _xok {
			d.data.Data = _x
			_vData.MarkConsumedString()
		}
	}
	if _vConfig, _ok := model.Field("config"); _ok && _vConfig.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vConfig.Leaf); _xok {
			d.data.Config = _x
			_vConfig.MarkConsumedString()
		}
	}
	if _vState, _ok := model.Field("state"); _ok && _vState.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vState.Leaf); _xok {
			d.data.State = _x
			_vState.MarkConsumedString()
		}
	}
	if _vCache, _ok := model.Field("cache"); _ok && _vCache.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vCache.Leaf); _xok {
			d.data.Cache = _x
			_vCache.MarkConsumedString()
		}
	}
	if _vRuntime, _ok := model.Field("runtime"); _ok && _vRuntime.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vRuntime.Leaf); _xok {
			d.data.Runtime = _x
			_vRuntime.MarkConsumedString()
		}
	}
	return d, nil
}

func (d *TomlXDGV0Document) Data() *TomlXDGV0 {
	return &d.data
}

func (d *TomlXDGV0Document) Encode() ([]byte, error) {
	{
		v, err := d.data.PublicKey.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("public-key: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "public-key", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Data != "" || cst.HasValue(d.cstDoc.Root(), "data") {
		if err := cst.SetAny(d.cstDoc.Root(), "data", d.data.Data); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Config != "" || cst.HasValue(d.cstDoc.Root(), "config") {
		if err := cst.SetAny(d.cstDoc.Root(), "config", d.data.Config); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.State != "" || cst.HasValue(d.cstDoc.Root(), "state") {
		if err := cst.SetAny(d.cstDoc.Root(), "state", d.data.State); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Cache != "" || cst.HasValue(d.cstDoc.Root(), "cache") {
		if err := cst.SetAny(d.cstDoc.Root(), "cache", d.data.Cache); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Runtime != "" || cst.HasValue(d.cstDoc.Root(), "runtime") {
		if err := cst.SetAny(d.cstDoc.Root(), "runtime", d.data.Runtime); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlXDGV0Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlXDGV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlXDGV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlXDGV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlXDGV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlXDGV0Into(data *TomlXDGV0, sub *cst.Value) error {
	if _vPublicKey, _ok := sub.Field("public-key"); _ok && _vPublicKey.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPublicKey.Leaf); _xok {
			if err := data.PublicKey.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("public-key: %w", err)
			}
			_vPublicKey.MarkConsumedText()
		}
	}
	if _vData, _ok := sub.Field("data"); _ok && _vData.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vData.Leaf); _xok {
			data.Data = _x
			_vData.MarkConsumedString()
		}
	}
	if _vConfig, _ok := sub.Field("config"); _ok && _vConfig.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vConfig.Leaf); _xok {
			data.Config = _x
			_vConfig.MarkConsumedString()
		}
	}
	if _vState, _ok := sub.Field("state"); _ok && _vState.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vState.Leaf); _xok {
			data.State = _x
			_vState.MarkConsumedString()
		}
	}
	if _vCache, _ok := sub.Field("cache"); _ok && _vCache.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vCache.Leaf); _xok {
			data.Cache = _x
			_vCache.MarkConsumedString()
		}
	}
	if _vRuntime, _ok := sub.Field("runtime"); _ok && _vRuntime.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vRuntime.Leaf); _xok {
			data.Runtime = _x
			_vRuntime.MarkConsumedString()
		}
	}
	return nil
}

func EncodeTomlXDGV0From(data *TomlXDGV0, doc *document.Document, container *cst.Node) error {
	{
		v, err := data.PublicKey.MarshalText()
		if err != nil {
			return fmt.Errorf("public-key: %w", err)
		}
		if err := cst.SetAny(container, "public-key", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Data != "" || cst.HasValue(container, "data") {
		if err := cst.SetAny(container, "data", data.Data); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Config != "" || cst.HasValue(container, "config") {
		if err := cst.SetAny(container, "config", data.Config); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.State != "" || cst.HasValue(container, "state") {
		if err := cst.SetAny(container, "state", data.State); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Cache != "" || cst.HasValue(container, "cache") {
		if err := cst.SetAny(container, "cache", data.Cache); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Runtime != "" || cst.HasValue(container, "runtime") {
		if err := cst.SetAny(container, "runtime", data.Runtime); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
