// Code generated by tommy 0.4.3 (1ae69d3); DO NOT EDIT.

package repo_blobs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlLocalOverridePathV0Document struct {
	data   TomlLocalOverridePathV0
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlLocalOverridePathV0(input []byte) (*TomlLocalOverridePathV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlLocalOverridePathV0Document{
		cstDoc: doc,
		model:  model,
	}

	if _vPublicKey, _ok := model.Get("public-key"); _ok && _vPublicKey.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPublicKey.Leaf); _xok {
			if err := d.data.PublicKey.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("public-key: %w", err)
			}
			_vPublicKey.MarkConsumed()
		}
	}
	if _vOverridePath, _ok := model.Get("override-path"); _ok && _vOverridePath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vOverridePath.Leaf); _xok {
			d.data.OverridePath = _x
			_vOverridePath.MarkConsumed()
		}
	}
	return d, nil
}

func (d *TomlLocalOverridePathV0Document) Data() *TomlLocalOverridePathV0 {
	return &d.data
}

func (d *TomlLocalOverridePathV0Document) Encode() ([]byte, error) {
	{
		v, err := d.data.PublicKey.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("public-key: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "public-key", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.OverridePath != "" || cst.HasValue(d.cstDoc.Root(), "override-path") {
		if err := cst.SetAny(d.cstDoc.Root(), "override-path", d.data.OverridePath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlLocalOverridePathV0Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlLocalOverridePathV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlLocalOverridePathV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlLocalOverridePathV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlLocalOverridePathV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlLocalOverridePathV0Into(data *TomlLocalOverridePathV0, sub *cst.Value) error {
	if _vPublicKey, _ok := sub.Get("public-key"); _ok && _vPublicKey.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPublicKey.Leaf); _xok {
			if err := data.PublicKey.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("public-key: %w", err)
			}
			_vPublicKey.MarkConsumed()
		}
	}
	if _vOverridePath, _ok := sub.Get("override-path"); _ok && _vOverridePath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vOverridePath.Leaf); _xok {
			data.OverridePath = _x
			_vOverridePath.MarkConsumed()
		}
	}
	return nil
}

func EncodeTomlLocalOverridePathV0From(data *TomlLocalOverridePathV0, doc *document.Document, container *cst.Node) error {
	{
		v, err := data.PublicKey.MarshalText()
		if err != nil {
			return fmt.Errorf("public-key: %w", err)
		}
		if err := cst.SetAny(container, "public-key", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.OverridePath != "" || cst.HasValue(container, "override-path") {
		if err := cst.SetAny(container, "override-path", data.OverridePath); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
