// Code generated by tommy; DO NOT EDIT.

package repo_blobs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlXDGV0Document struct {
	data     TomlXDGV0
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlXDGV0(input []byte) (*TomlXDGV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlXDGV0Document{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "public-key":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := d.data.PublicKey.UnmarshalText([]byte(v)); err != nil {
					return nil, fmt.Errorf("public-key: %w", err)
				}
				d.consumed["public-key"] = true
			}
		case "data":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Data = v
				d.consumed["data"] = true
			}
		case "config":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Config = v
				d.consumed["config"] = true
			}
		case "state":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.State = v
				d.consumed["state"] = true
			}
		case "cache":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Cache = v
				d.consumed["cache"] = true
			}
		case "runtime":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Runtime = v
				d.consumed["runtime"] = true
			}
		}
	}
	return d, nil
}

func (d *TomlXDGV0Document) Data() *TomlXDGV0 {
	return &d.data
}

func (d *TomlXDGV0Document) Encode() ([]byte, error) {
	{
		v, err := d.data.PublicKey.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("public-key: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "public-key", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Data != "" || cst.HasValue(d.cstDoc.Root(), "data") {
		if err := cst.SetAny(d.cstDoc.Root(), "data", d.data.Data); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Config != "" || cst.HasValue(d.cstDoc.Root(), "config") {
		if err := cst.SetAny(d.cstDoc.Root(), "config", d.data.Config); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.State != "" || cst.HasValue(d.cstDoc.Root(), "state") {
		if err := cst.SetAny(d.cstDoc.Root(), "state", d.data.State); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Cache != "" || cst.HasValue(d.cstDoc.Root(), "cache") {
		if err := cst.SetAny(d.cstDoc.Root(), "cache", d.data.Cache); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Runtime != "" || cst.HasValue(d.cstDoc.Root(), "runtime") {
		if err := cst.SetAny(d.cstDoc.Root(), "runtime", d.data.Runtime); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlXDGV0Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func (d *TomlXDGV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlXDGV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlXDGV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlXDGV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlXDGV0Into(data *TomlXDGV0, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "public-key":
			if v, ok := cst.ExtractString(_kv); ok {
				if err := data.PublicKey.UnmarshalText([]byte(v)); err != nil {
					return fmt.Errorf("public-key: %w", err)
				}
				consumed[keyPrefix+"public-key"] = true
			}
		case "data":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Data = v
				consumed[keyPrefix+"data"] = true
			}
		case "config":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Config = v
				consumed[keyPrefix+"config"] = true
			}
		case "state":
			if v, ok := cst.ExtractString(_kv); ok {
				data.State = v
				consumed[keyPrefix+"state"] = true
			}
		case "cache":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Cache = v
				consumed[keyPrefix+"cache"] = true
			}
		case "runtime":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Runtime = v
				consumed[keyPrefix+"runtime"] = true
			}
		}
	}
	return nil
}

func EncodeTomlXDGV0From(data *TomlXDGV0, doc *document.Document, container *cst.Node) error {
	{
		v, err := data.PublicKey.MarshalText()
		if err != nil {
			return fmt.Errorf("public-key: %w", err)
		}
		if err := cst.SetAny(container, "public-key", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Data != "" || cst.HasValue(container, "data") {
		if err := cst.SetAny(container, "data", data.Data); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Config != "" || cst.HasValue(container, "config") {
		if err := cst.SetAny(container, "config", data.Config); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.State != "" || cst.HasValue(container, "state") {
		if err := cst.SetAny(container, "state", data.State); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Cache != "" || cst.HasValue(container, "cache") {
		if err := cst.SetAny(container, "cache", data.Cache); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Runtime != "" || cst.HasValue(container, "runtime") {
		if err := cst.SetAny(container, "runtime", data.Runtime); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
