// Code generated by tommy; DO NOT EDIT.

package options_tools

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type OptionsDocument struct {
	data     Options
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeOptions(input []byte) (*OptionsDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &OptionsDocument{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[[]string](d.cstDoc, d.cstDoc.Root(), "merge"); err == nil {
		d.data.Merge = v
		d.consumed["merge"] = true
	}

	return d, nil
}

func (d *OptionsDocument) Data() *Options { return &d.data }

func (d *OptionsDocument) Encode() ([]byte, error) {
	if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "merge", d.data.Merge); err != nil {
		return nil, err
	}

	return d.cstDoc.Bytes(), nil
}

func (d *OptionsDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
