// Code generated by tommy; DO NOT EDIT.

package tag_blobs

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type TomlV1Document struct {
	data     TomlV1
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlV1(input []byte) (*TomlV1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlV1Document{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "filter"); err == nil {
		d.data.Filter = v
		d.consumed["filter"] = true
	}

	return d, nil
}

func (d *TomlV1Document) Data() *TomlV1 { return &d.data }

func (d *TomlV1Document) Encode() ([]byte, error) {
	if d.data.Filter != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "filter") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "filter", d.data.Filter); err != nil {
			return nil, err
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *TomlV1Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func (d *TomlV1Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlV1Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlV1Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlV1Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlV1Into(data *TomlV1, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	if v, err := document.GetFromContainer[string](doc, container, "filter"); err == nil {
		data.Filter = v
		consumed[keyPrefix+"filter"] = true
	}

	return nil
}

func EncodeTomlV1From(data *TomlV1, doc *document.Document, container *cst.Node) error {
	if data.Filter != "" || doc.HasInContainer(container, "filter") {
		if err := doc.SetInContainer(container, "filter", data.Filter); err != nil {
			return err
		}
	}

	return nil
}
