// Code generated by "stringer -type=Binary"; DO NOT EDIT.

package key_bytes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[ContentLength-67]
	_ = x[Sigil-83]
	_ = x[Blob-65]
	_ = x[RepoPubKey-80]
	_ = x[RepoSig-113]
	_ = x[Description-66]
	_ = x[Tag-69]
	_ = x[Genre-71]
	_ = x[ObjectId-75]
	_ = x[Comment-107]
	_ = x[Tai-84]
	_ = x[Type-116]
	_ = x[References-82]
	_ = x[BlobReferences-98]
	_ = x[SigParentMetadataParentObjectId-77]
	_ = x[DigestMetadataParentObjectId-115]
	_ = x[DigestMetadataWithoutTai-110]
	_ = x[DigestMetadata-109]
	_ = x[CacheDormant-97]
	_ = x[CacheTagImplicit-73]
	_ = x[CacheTags-120]
	_ = x[CacheTags2-121]
}

const _Binary_name = "UnknownBlobDescriptionContentLengthTagGenreCacheTagImplicitObjectIdSigParentMetadataParentObjectIdRepoPubKeyReferencesSigilTaiCacheDormantBlobReferencesCommentDigestMetadataDigestMetadataWithoutTaiRepoSigDigestMetadataParentObjectIdTypeCacheTagsCacheTags2"

var _Binary_map = map[Binary]string{
	0:   _Binary_name[0:7],
	65:  _Binary_name[7:11],
	66:  _Binary_name[11:22],
	67:  _Binary_name[22:35],
	69:  _Binary_name[35:38],
	71:  _Binary_name[38:43],
	73:  _Binary_name[43:59],
	75:  _Binary_name[59:67],
	77:  _Binary_name[67:98],
	80:  _Binary_name[98:108],
	82:  _Binary_name[108:118],
	83:  _Binary_name[118:123],
	84:  _Binary_name[123:126],
	97:  _Binary_name[126:138],
	98:  _Binary_name[138:152],
	107: _Binary_name[152:159],
	109: _Binary_name[159:173],
	110: _Binary_name[173:197],
	113: _Binary_name[197:204],
	115: _Binary_name[204:232],
	116: _Binary_name[232:236],
	120: _Binary_name[236:245],
	121: _Binary_name[245:255],
}

func (i Binary) String() string {
	if str, ok := _Binary_map[i]; ok {
		return str
	}
	return "Binary(" + strconv.FormatInt(int64(i), 10) + ")"
}
