// Code generated by tommy 0.5.0 (47364f2); DO NOT EDIT.

package zettel_id_log

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type V1Document struct {
	data   V1
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeV1(input []byte) (*V1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	return decodeV1Parsed(doc)
}

// DecodeV1Strict is DecodeV1 for input that must be exactly what it
// claims: it returns a *cst.SyntaxError when input is not well-formed TOML and
// *cst.TypeError values when a key's TOML type does not match its field, where
// DecodeV1 would decode leniently. Keys no field claims are not errors; they
// stay in Undecoded.
func DecodeV1Strict(input []byte) (*V1Document, error) {
	doc, err := document.ParseStrict(input)
	if err != nil {
		return nil, err
	}
	d, err := decodeV1Parsed(doc)
	if err != nil {
		return nil, err
	}
	if err := d.model.TypeErrors(); err != nil {
		return nil, err
	}
	return d, nil
}

func decodeV1Parsed(doc *document.Document) (*V1Document, error) {
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &V1Document{
		cstDoc: doc,
		model:  model,
	}

	if _vSide, _ok := model.Field("side"); _ok && _vSide.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vSide.Leaf); _xok {
			if err := d.data.Side.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("side: %w", err)
			}
			_vSide.MarkConsumedText()
		}
	}
	if _vTai, _ok := model.Field("tai"); _ok && _vTai.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTai.Leaf); _xok {
			if err := d.data.Tai.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("tai: %w", err)
			}
			_vTai.MarkConsumedText()
		}
	}
	if _vMarklId, _ok := model.Field("markl-id"); _ok && _vMarklId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vMarklId.Leaf); _xok {
			if err := d.data.MarklId.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("markl-id: %w", err)
			}
			_vMarklId.MarkConsumedText()
		}
	}
	if _vWordCount, _ok := model.Field("word-count"); _ok && _vWordCount.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractInt(_vWordCount.Leaf); _xok {
			d.data.WordCount = _x
			_vWordCount.MarkConsumed()
		}
	}
	return d, nil
}

func (d *V1Document) Data() *V1 {
	return &d.data
}

func (d *V1Document) Encode() ([]byte, error) {
	{
		v, err := d.data.Side.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("side: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "side", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.Tai.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("tai: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "tai", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.MarklId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("markl-id: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "markl-id", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.WordCount != 0 || cst.HasValue(d.cstDoc.Root(), "word-count") {
		if err := cst.SetAny(d.cstDoc.Root(), "word-count", d.data.WordCount); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *V1Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *V1Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *V1Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *V1Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *V1Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeV1Into(data *V1, sub *cst.Value) error {
	if _vSide, _ok := sub.Field("side"); _ok && _vSide.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vSide.Leaf); _xok {
			if err := data.Side.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("side: %w", err)
			}
			_vSide.MarkConsumedText()
		}
	}
	if _vTai, _ok := sub.Field("tai"); _ok && _vTai.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTai.Leaf); _xok {
			if err := data.Tai.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("tai: %w", err)
			}
			_vTai.MarkConsumedText()
		}
	}
	if _vMarklId, _ok := sub.Field("markl-id"); _ok && _vMarklId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vMarklId.Leaf); _xok {
			if err := data.MarklId.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("markl-id: %w", err)
			}
			_vMarklId.MarkConsumedText()
		}
	}
	if _vWordCount, _ok := sub.Field("word-count"); _ok && _vWordCount.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractInt(_vWordCount.Leaf); _xok {
			data.WordCount = _x
			_vWordCount.MarkConsumed()
		}
	}
	return nil
}

func EncodeV1From(data *V1, doc *document.Document, container *cst.Node) error {
	{
		v, err := data.Side.MarshalText()
		if err != nil {
			return fmt.Errorf("side: %w", err)
		}
		if err := cst.SetAny(container, "side", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.Tai.MarshalText()
		if err != nil {
			return fmt.Errorf("tai: %w", err)
		}
		if err := cst.SetAny(container, "tai", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.MarklId.MarshalText()
		if err != nil {
			return fmt.Errorf("markl-id: %w", err)
		}
		if err := cst.SetAny(container, "markl-id", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.WordCount != 0 || cst.HasValue(container, "word-count") {
		if err := cst.SetAny(container, "word-count", data.WordCount); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
