// Code generated by tommy; DO NOT EDIT.

package zettel_id_log

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type V1Document struct {
	data     V1
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeV1(input []byte) (*V1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &V1Document{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "side"); err == nil {
		if err := d.data.Side.UnmarshalText([]byte(v)); err != nil {
			return nil, fmt.Errorf("side: %w", err)
		}
		d.consumed["side"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "tai"); err == nil {
		if err := d.data.Tai.UnmarshalText([]byte(v)); err != nil {
			return nil, fmt.Errorf("tai: %w", err)
		}
		d.consumed["tai"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "markl-id"); err == nil {
		if err := d.data.MarklId.UnmarshalText([]byte(v)); err != nil {
			return nil, fmt.Errorf("markl-id: %w", err)
		}
		d.consumed["markl-id"] = true
	}
	if v, err := document.GetFromContainer[int](d.cstDoc, d.cstDoc.Root(), "word-count"); err == nil {
		d.data.WordCount = v
		d.consumed["word-count"] = true
	}

	return d, nil
}

func (d *V1Document) Data() *V1 { return &d.data }

func (d *V1Document) Encode() ([]byte, error) {
	{
		v, err := d.data.Side.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("side: %w", err)
		}
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "side", string(v)); err != nil {
			return nil, err
		}
	}
	{
		v, err := d.data.Tai.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("tai: %w", err)
		}
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "tai", string(v)); err != nil {
			return nil, err
		}
	}
	{
		v, err := d.data.MarklId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("markl-id: %w", err)
		}
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "markl-id", string(v)); err != nil {
			return nil, err
		}
	}
	if d.data.WordCount != 0 || d.cstDoc.HasInContainer(d.cstDoc.Root(), "word-count") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "word-count", d.data.WordCount); err != nil {
			return nil, err
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *V1Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
