// Code generated by tommy; DO NOT EDIT.

package workspace_config_blobs

import (
	"fmt"

	"code.linenisgreat.com/dodder/go/internal/delta/repo_configs"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type V0Document struct {
	data     V0
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeV0(input []byte) (*V0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &V0Document{cstDoc: doc, consumed: make(map[string]bool)}

	if tableNode := d.cstDoc.FindTable("defaults"); tableNode != nil {
		d.consumed["defaults"] = true
		if err := repo_configs.DecodeDefaultsV1OmitEmptyInto(&d.data.Defaults, d.cstDoc, tableNode, d.consumed, "defaults."); err != nil {
			return nil, fmt.Errorf("defaults: %w", err)
		}
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "query"); err == nil {
		d.data.Query = v
		d.consumed["query"] = true
	}
	if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "dry-run"); err == nil {
		d.data.DryRun = v
		d.consumed["dry-run"] = true
	}

	return d, nil
}

func (d *V0Document) Data() *V0 { return &d.data }

func (d *V0Document) Encode() ([]byte, error) {
	if tableNode := d.cstDoc.FindTable("defaults"); tableNode != nil {
		if err := repo_configs.EncodeDefaultsV1OmitEmptyFrom(&d.data.Defaults, d.cstDoc, tableNode); err != nil {
			return nil, fmt.Errorf("defaults: %w", err)
		}
	}
	if d.data.Query != "" {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "query", d.data.Query); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "query")
	}
	if d.data.DryRun != false || d.cstDoc.HasInContainer(d.cstDoc.Root(), "dry-run") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "dry-run", d.data.DryRun); err != nil {
			return nil, err
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *V0Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func DecodeV0Into(data *V0, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	if tableNode := doc.FindTableInContainer(container, "defaults"); tableNode != nil {
		consumed[keyPrefix+"defaults"] = true
		if err := repo_configs.DecodeDefaultsV1OmitEmptyInto(&data.Defaults, doc, tableNode, consumed, "defaults."); err != nil {
			return fmt.Errorf("defaults: %w", err)
		}
	}
	if v, err := document.GetFromContainer[string](doc, container, "query"); err == nil {
		data.Query = v
		consumed[keyPrefix+"query"] = true
	}
	if v, err := document.GetFromContainer[bool](doc, container, "dry-run"); err == nil {
		data.DryRun = v
		consumed[keyPrefix+"dry-run"] = true
	}

	return nil
}

func EncodeV0From(data *V0, doc *document.Document, container *cst.Node) error {
	if tableNode := doc.FindTableInContainer(container, "defaults"); tableNode != nil {
		if err := repo_configs.EncodeDefaultsV1OmitEmptyFrom(&data.Defaults, doc, tableNode); err != nil {
			return fmt.Errorf("defaults: %w", err)
		}
	}
	if data.Query != "" {
		if err := doc.SetInContainer(container, "query", data.Query); err != nil {
			return err
		}
	} else {
		_ = doc.DeleteFromContainer(container, "query")
	}
	if data.DryRun != false || doc.HasInContainer(container, "dry-run") {
		if err := doc.SetInContainer(container, "dry-run", data.DryRun); err != nil {
			return err
		}
	}

	return nil
}
