// Code generated by tommy; DO NOT EDIT.

package workspace_config_blobs

import (
	"code.linenisgreat.com/dodder/go/internal/charlie/repo_configs"
	"fmt"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
	"strings"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type V1Document struct {
	data     V1
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeV1(input []byte) (*V1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &V1Document{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "query":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Query = v
				d.consumed["query"] = true
			}
		case "dry-run":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.DryRun = v
				d.consumed["dry-run"] = true
			}
		case "parent-path":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.ParentPath = v
				d.consumed["parent-path"] = true
			}
		case "sync-tai":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.SyncTai = v
				d.consumed["sync-tai"] = true
			}
		case "sync-digest":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.SyncDigest = v
				d.consumed["sync-digest"] = true
			}
		}
	}
	for _, _ch := range d.cstDoc.Root().Children {
		if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "defaults" {
			d.consumed["defaults"] = true
			if err := repo_configs.DecodeDefaultsV1OmitEmptyInto(&d.data.Defaults, d.cstDoc, _ch, d.consumed, "defaults."); err != nil {
				return nil, fmt.Errorf("defaults: %w", err)
			}
			break
		}
	}
	return d, nil
}
func (d *V1Document) Data() *V1 {
	return &d.data
}
func (d *V1Document) Encode() ([]byte, error) {
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "defaults")
		if err := repo_configs.EncodeDefaultsV1OmitEmptyFrom(&d.data.Defaults, d.cstDoc, tableNode); err != nil {
			return nil, fmt.Errorf("defaults: %w", err)
		}
	}
	if d.data.Query != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "query", d.data.Query); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "query")
	}
	if d.data.DryRun != false || cst.HasValue(d.cstDoc.Root(), "dry-run") {
		if err := cst.SetAny(d.cstDoc.Root(), "dry-run", d.data.DryRun); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.ParentPath != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "parent-path", d.data.ParentPath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "parent-path")
	}
	if d.data.SyncTai != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "sync-tai", d.data.SyncTai); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "sync-tai")
	}
	if d.data.SyncDigest != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "sync-digest", d.data.SyncDigest); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "sync-digest")
	}
	return d.cstDoc.Bytes(), nil
}
func (d *V1Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *V1Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *V1Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *V1Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *V1Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeV1Into(data *V1, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "query":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Query = v
				consumed[keyPrefix+"query"] = true
			}
		case "dry-run":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.DryRun = v
				consumed[keyPrefix+"dry-run"] = true
			}
		case "parent-path":
			if v, ok := cst.ExtractString(_kv); ok {
				data.ParentPath = v
				consumed[keyPrefix+"parent-path"] = true
			}
		case "sync-tai":
			if v, ok := cst.ExtractString(_kv); ok {
				data.SyncTai = v
				consumed[keyPrefix+"sync-tai"] = true
			}
		case "sync-digest":
			if v, ok := cst.ExtractString(_kv); ok {
				data.SyncDigest = v
				consumed[keyPrefix+"sync-digest"] = true
			}
		}
	}
	for _, _ch := range doc.Root().Children {
		if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"defaults" {
			consumed[keyPrefix+"defaults"] = true
			if err := repo_configs.DecodeDefaultsV1OmitEmptyInto(&data.Defaults, doc, _ch, consumed, keyPrefix+"defaults."); err != nil {
				return fmt.Errorf("defaults: %w", err)
			}
			break
		}
	}
	return nil
}
func EncodeV1From(data *V1, doc *document.Document, container *cst.Node) error {
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "defaults")
		if err := repo_configs.EncodeDefaultsV1OmitEmptyFrom(&data.Defaults, doc, tableNode); err != nil {
			return fmt.Errorf("defaults: %w", err)
		}
	}
	if data.Query != "" {
		if err := cst.SetAny(container, "query", data.Query); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "query")
	}
	if data.DryRun != false || cst.HasValue(container, "dry-run") {
		if err := cst.SetAny(container, "dry-run", data.DryRun); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.ParentPath != "" {
		if err := cst.SetAny(container, "parent-path", data.ParentPath); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "parent-path")
	}
	if data.SyncTai != "" {
		if err := cst.SetAny(container, "sync-tai", data.SyncTai); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "sync-tai")
	}
	if data.SyncDigest != "" {
		if err := cst.SetAny(container, "sync-digest", data.SyncDigest); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "sync-digest")
	}
	return nil
}
