// Code generated by tommy; DO NOT EDIT.

package workspace_config_blobs

import (
	"code.linenisgreat.com/dodder/go/internal/charlie/repo_configs"
	"fmt"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
	"strings"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type V2Document struct {
	data     V2
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeV2(input []byte) (*V2Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &V2Document{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "query":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Query = v
				d.consumed["query"] = true
			}
		case "dry-run":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.DryRun = v
				d.consumed["dry-run"] = true
			}
		case "parent-path":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.ParentPath = v
				d.consumed["parent-path"] = true
			}
		case "sync-tai":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.SyncTai = v
				d.consumed["sync-tai"] = true
			}
		case "sync-digest":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.SyncDigest = v
				d.consumed["sync-digest"] = true
			}
		}
	}
	for _, _ch := range d.cstDoc.Root().Children {
		if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "defaults" {
			d.consumed["defaults"] = true
			if err := repo_configs.DecodeDefaultsV1OmitEmptyInto(&d.data.Defaults, d.cstDoc, _ch, d.consumed, "defaults."); err != nil {
				return nil, fmt.Errorf("defaults: %w", err)
			}
			break
		}
	}
	for _, _ch := range d.cstDoc.Root().Children {
		if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "haustoria" {
			d.consumed["haustoria"] = true
			for _, _kv := range _ch.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "type":
					if v, ok := cst.ExtractString(_kv); ok {
						d.data.Haustoria.Type = v
						d.consumed["haustoria.type"] = true
					}
				}
			}
			{
				var _ftCaldav *cst.Node
				for _, _ch := range d.cstDoc.Root().Children {
					if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "haustoria.caldav" {
						_ftCaldav = _ch
						break
					}
				}
				if _ftCaldav != nil {
					d.consumed["haustoria.caldav"] = true
					calDAVVal := &CalDAVConfig{}
					for _, _kv := range _ftCaldav.Children {
						if _kv.Kind != cst.NodeKeyValue {
							continue
						}
						switch cst.KeyValueName(_kv) {
						case "url":
							if v, ok := cst.ExtractString(_kv); ok {
								calDAVVal.URL = v
								d.consumed["haustoria.caldav.url"] = true
							}
						case "username":
							if v, ok := cst.ExtractString(_kv); ok {
								calDAVVal.Username = v
								d.consumed["haustoria.caldav.username"] = true
							}
						}
					}
					d.data.Haustoria.CalDAV = calDAVVal
				} else {
					calDAVVal := &CalDAVConfig{}
					_found := false
					for _, _kv := range _ch.Children {
						if _kv.Kind != cst.NodeKeyValue {
							continue
						}
						switch cst.KeyValueName(_kv) {
						case "url":
							if v, ok := cst.ExtractString(_kv); ok {
								calDAVVal.URL = v
								_found = true
								d.consumed["url"] = true
							}
						case "username":
							if v, ok := cst.ExtractString(_kv); ok {
								calDAVVal.Username = v
								_found = true
								d.consumed["username"] = true
							}
						}
					}
					if _found {
						d.data.Haustoria.CalDAV = calDAVVal
					}
				}
			}
			{
				var _mr map[string]CalendarConfig
				for _, _ch := range d.cstDoc.Root().Children {
					if _ch.Kind != cst.NodeTable {
						continue
					}
					_hdr := cst.TableHeaderKey(_ch)
					if !strings.HasPrefix(_hdr, "haustoria.calendars.") {
						continue
					}
					_mk := _hdr[20:]
					if strings.Contains(_mk, ".") {
						continue
					}
					if _mr == nil {
						d.consumed["haustoria.calendars"] = true
						_mr = make(map[string]CalendarConfig)
					}
					d.consumed["haustoria.calendars"+"."+_mk] = true
					var entry CalendarConfig
					for _, _kv := range _ch.Children {
						if _kv.Kind != cst.NodeKeyValue {
							continue
						}
						switch cst.KeyValueName(_kv) {
						case "url":
							if v, ok := cst.ExtractString(_kv); ok {
								entry.URL = v
								d.consumed["haustoria.calendars."+_mk+"."+"url"] = true
							}
						case "type":
							if v, ok := cst.ExtractString(_kv); ok {
								entry.Type = v
								d.consumed["haustoria.calendars."+_mk+"."+"type"] = true
							}
						case "tags":
							if v, ok := cst.ExtractStringSlice(_kv); ok {
								entry.Tags = v
								d.consumed["haustoria.calendars."+_mk+"."+"tags"] = true
							}
						}
					}
					for _, _ch := range d.cstDoc.Root().Children {
						if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "haustoria.calendars."+_mk+"."+"status-tags" {
							entry.StatusTags = cst.ExtractStringMap(_ch)
							d.consumed["haustoria.calendars."+_mk+"."+"status-tags"] = true
							for _ik := range entry.StatusTags {
								d.consumed["haustoria.calendars."+_mk+"."+"status-tags"+"."+_ik] = true
							}
							break
						}
					}
					_mr[_mk] = entry
				}
				if _mr != nil {
					d.data.Haustoria.Calendars = _mr
				}
			}
			{
				var _ftOrgmode *cst.Node
				for _, _ch := range d.cstDoc.Root().Children {
					if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "haustoria.orgmode" {
						_ftOrgmode = _ch
						break
					}
				}
				if _ftOrgmode != nil {
					d.consumed["haustoria.orgmode"] = true
					orgmodeVal := &OrgmodeConfig{}
					for _, _kv := range _ftOrgmode.Children {
						if _kv.Kind != cst.NodeKeyValue {
							continue
						}
						switch cst.KeyValueName(_kv) {
						case "transport":
							if v, ok := cst.ExtractString(_kv); ok {
								orgmodeVal.Transport = v
								d.consumed["haustoria.orgmode.transport"] = true
							}
						}
					}
					{
						var _ftWebdav *cst.Node
						for _, _ch := range d.cstDoc.Root().Children {
							if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "haustoria.orgmode.webdav" {
								_ftWebdav = _ch
								break
							}
						}
						if _ftWebdav != nil {
							d.consumed["haustoria.orgmode.webdav"] = true
							webDAVVal := &OrgmodeWebDAV{}
							for _, _kv := range _ftWebdav.Children {
								if _kv.Kind != cst.NodeKeyValue {
									continue
								}
								switch cst.KeyValueName(_kv) {
								case "url":
									if v, ok := cst.ExtractString(_kv); ok {
										webDAVVal.URL = v
										d.consumed["haustoria.orgmode.webdav.url"] = true
									}
								case "username":
									if v, ok := cst.ExtractString(_kv); ok {
										webDAVVal.Username = v
										d.consumed["haustoria.orgmode.webdav.username"] = true
									}
								}
							}
							orgmodeVal.WebDAV = webDAVVal
						} else {
							webDAVVal := &OrgmodeWebDAV{}
							_found := false
							for _, _kv := range _ftOrgmode.Children {
								if _kv.Kind != cst.NodeKeyValue {
									continue
								}
								switch cst.KeyValueName(_kv) {
								case "url":
									if v, ok := cst.ExtractString(_kv); ok {
										webDAVVal.URL = v
										_found = true
										d.consumed["url"] = true
									}
								case "username":
									if v, ok := cst.ExtractString(_kv); ok {
										webDAVVal.Username = v
										_found = true
										d.consumed["username"] = true
									}
								}
							}
							if _found {
								orgmodeVal.WebDAV = webDAVVal
							}
						}
					}
					{
						var _ftSftp *cst.Node
						for _, _ch := range d.cstDoc.Root().Children {
							if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "haustoria.orgmode.sftp" {
								_ftSftp = _ch
								break
							}
						}
						if _ftSftp != nil {
							d.consumed["haustoria.orgmode.sftp"] = true
							sFTPVal := &OrgmodeSFTP{}
							for _, _kv := range _ftSftp.Children {
								if _kv.Kind != cst.NodeKeyValue {
									continue
								}
								switch cst.KeyValueName(_kv) {
								case "host":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.Host = v
										d.consumed["haustoria.orgmode.sftp.host"] = true
									}
								case "port":
									if v, ok := cst.ExtractInt(_kv); ok {
										sFTPVal.Port = v
										d.consumed["haustoria.orgmode.sftp.port"] = true
									}
								case "user":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.User = v
										d.consumed["haustoria.orgmode.sftp.user"] = true
									}
								case "private-key-path":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.PrivateKeyPath = v
										d.consumed["haustoria.orgmode.sftp.private-key-path"] = true
									}
								case "known-hosts-file":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.KnownHostsFile = v
										d.consumed["haustoria.orgmode.sftp.known-hosts-file"] = true
									}
								}
							}
							orgmodeVal.SFTP = sFTPVal
						} else {
							sFTPVal := &OrgmodeSFTP{}
							_found := false
							for _, _kv := range _ftOrgmode.Children {
								if _kv.Kind != cst.NodeKeyValue {
									continue
								}
								switch cst.KeyValueName(_kv) {
								case "host":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.Host = v
										_found = true
										d.consumed["host"] = true
									}
								case "port":
									if v, ok := cst.ExtractInt(_kv); ok {
										sFTPVal.Port = v
										_found = true
										d.consumed["port"] = true
									}
								case "user":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.User = v
										_found = true
										d.consumed["user"] = true
									}
								case "private-key-path":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.PrivateKeyPath = v
										_found = true
										d.consumed["private-key-path"] = true
									}
								case "known-hosts-file":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.KnownHostsFile = v
										_found = true
										d.consumed["known-hosts-file"] = true
									}
								}
							}
							if _found {
								orgmodeVal.SFTP = sFTPVal
							}
						}
					}
					d.data.Haustoria.Orgmode = orgmodeVal
				} else {
					orgmodeVal := &OrgmodeConfig{}
					_found := false
					for _, _kv := range _ch.Children {
						if _kv.Kind != cst.NodeKeyValue {
							continue
						}
						switch cst.KeyValueName(_kv) {
						case "transport":
							if v, ok := cst.ExtractString(_kv); ok {
								orgmodeVal.Transport = v
								_found = true
								d.consumed["transport"] = true
							}
						}
					}
					{
						var _ftWebdav *cst.Node
						for _, _ch := range d.cstDoc.Root().Children {
							if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "webdav" {
								_ftWebdav = _ch
								break
							}
						}
						if _ftWebdav != nil {
							d.consumed["webdav"] = true
							webDAVVal := &OrgmodeWebDAV{}
							for _, _kv := range _ftWebdav.Children {
								if _kv.Kind != cst.NodeKeyValue {
									continue
								}
								switch cst.KeyValueName(_kv) {
								case "url":
									if v, ok := cst.ExtractString(_kv); ok {
										webDAVVal.URL = v
										d.consumed["webdav.url"] = true
									}
								case "username":
									if v, ok := cst.ExtractString(_kv); ok {
										webDAVVal.Username = v
										d.consumed["webdav.username"] = true
									}
								}
							}
							orgmodeVal.WebDAV = webDAVVal
						} else {
							webDAVVal := &OrgmodeWebDAV{}
							_found := false
							for _, _kv := range _ch.Children {
								if _kv.Kind != cst.NodeKeyValue {
									continue
								}
								switch cst.KeyValueName(_kv) {
								case "url":
									if v, ok := cst.ExtractString(_kv); ok {
										webDAVVal.URL = v
										_found = true
										d.consumed["url"] = true
									}
								case "username":
									if v, ok := cst.ExtractString(_kv); ok {
										webDAVVal.Username = v
										_found = true
										d.consumed["username"] = true
									}
								}
							}
							if _found {
								orgmodeVal.WebDAV = webDAVVal
							}
						}
					}
					{
						var _ftSftp *cst.Node
						for _, _ch := range d.cstDoc.Root().Children {
							if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "sftp" {
								_ftSftp = _ch
								break
							}
						}
						if _ftSftp != nil {
							d.consumed["sftp"] = true
							sFTPVal := &OrgmodeSFTP{}
							for _, _kv := range _ftSftp.Children {
								if _kv.Kind != cst.NodeKeyValue {
									continue
								}
								switch cst.KeyValueName(_kv) {
								case "host":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.Host = v
										d.consumed["sftp.host"] = true
									}
								case "port":
									if v, ok := cst.ExtractInt(_kv); ok {
										sFTPVal.Port = v
										d.consumed["sftp.port"] = true
									}
								case "user":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.User = v
										d.consumed["sftp.user"] = true
									}
								case "private-key-path":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.PrivateKeyPath = v
										d.consumed["sftp.private-key-path"] = true
									}
								case "known-hosts-file":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.KnownHostsFile = v
										d.consumed["sftp.known-hosts-file"] = true
									}
								}
							}
							orgmodeVal.SFTP = sFTPVal
						} else {
							sFTPVal := &OrgmodeSFTP{}
							_found := false
							for _, _kv := range _ch.Children {
								if _kv.Kind != cst.NodeKeyValue {
									continue
								}
								switch cst.KeyValueName(_kv) {
								case "host":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.Host = v
										_found = true
										d.consumed["host"] = true
									}
								case "port":
									if v, ok := cst.ExtractInt(_kv); ok {
										sFTPVal.Port = v
										_found = true
										d.consumed["port"] = true
									}
								case "user":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.User = v
										_found = true
										d.consumed["user"] = true
									}
								case "private-key-path":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.PrivateKeyPath = v
										_found = true
										d.consumed["private-key-path"] = true
									}
								case "known-hosts-file":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.KnownHostsFile = v
										_found = true
										d.consumed["known-hosts-file"] = true
									}
								}
							}
							if _found {
								orgmodeVal.SFTP = sFTPVal
							}
						}
					}
					if _found {
						d.data.Haustoria.Orgmode = orgmodeVal
					}
				}
			}
			{
				var _mr map[string]FolderConfig
				for _, _ch := range d.cstDoc.Root().Children {
					if _ch.Kind != cst.NodeTable {
						continue
					}
					_hdr := cst.TableHeaderKey(_ch)
					if !strings.HasPrefix(_hdr, "haustoria.folders.") {
						continue
					}
					_mk := _hdr[18:]
					if strings.Contains(_mk, ".") {
						continue
					}
					if _mr == nil {
						d.consumed["haustoria.folders"] = true
						_mr = make(map[string]FolderConfig)
					}
					d.consumed["haustoria.folders"+"."+_mk] = true
					var entry FolderConfig
					for _, _kv := range _ch.Children {
						if _kv.Kind != cst.NodeKeyValue {
							continue
						}
						switch cst.KeyValueName(_kv) {
						case "path":
							if v, ok := cst.ExtractString(_kv); ok {
								entry.Path = v
								d.consumed["haustoria.folders."+_mk+"."+"path"] = true
							}
						case "type":
							if v, ok := cst.ExtractString(_kv); ok {
								entry.Type = v
								d.consumed["haustoria.folders."+_mk+"."+"type"] = true
							}
						case "tags":
							if v, ok := cst.ExtractStringSlice(_kv); ok {
								entry.Tags = v
								d.consumed["haustoria.folders."+_mk+"."+"tags"] = true
							}
						}
					}
					_mr[_mk] = entry
				}
				if _mr != nil {
					d.data.Haustoria.Folders = _mr
				}
			}
			break
		}
	}
	return d, nil
}
func (d *V2Document) Data() *V2 {
	return &d.data
}
func (d *V2Document) Encode() ([]byte, error) {
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "defaults")
		if err := repo_configs.EncodeDefaultsV1OmitEmptyFrom(&d.data.Defaults, d.cstDoc, tableNode); err != nil {
			return nil, fmt.Errorf("defaults: %w", err)
		}
	}
	if d.data.Query != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "query", d.data.Query); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "query")
	}
	if d.data.DryRun != false || cst.HasValue(d.cstDoc.Root(), "dry-run") {
		if err := cst.SetAny(d.cstDoc.Root(), "dry-run", d.data.DryRun); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.ParentPath != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "parent-path", d.data.ParentPath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "parent-path")
	}
	if d.data.SyncTai != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "sync-tai", d.data.SyncTai); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "sync-tai")
	}
	if d.data.SyncDigest != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "sync-digest", d.data.SyncDigest); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "sync-digest")
	}
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "haustoria")
		if d.data.Haustoria.Type != "" || cst.HasValue(tableNode, "type") {
			if err := cst.SetAny(tableNode, "type", d.data.Haustoria.Type); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Haustoria.CalDAV != nil {
			tableNode := cst.EnsureChildTable(d.cstDoc.Root(), tableNode, "caldav")
			if d.data.Haustoria.CalDAV.URL != "" || cst.HasValue(tableNode, "url") {
				if err := cst.SetAny(tableNode, "url", d.data.Haustoria.CalDAV.URL); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Haustoria.CalDAV.Username != "" || cst.HasValue(tableNode, "username") {
				if err := cst.SetAny(tableNode, "username", d.data.Haustoria.CalDAV.Username); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		if len(d.data.Haustoria.Calendars) > 0 {
			for mapKey, mapVal := range d.data.Haustoria.Calendars {
				subTable := cst.EnsureChildSubTable(d.cstDoc.Root(), tableNode, "calendars", mapKey)
				if mapVal.URL != "" || cst.HasValue(subTable, "url") {
					if err := cst.SetAny(subTable, "url", mapVal.URL); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if mapVal.Type != "" || cst.HasValue(subTable, "type") {
					if err := cst.SetAny(subTable, "type", mapVal.Type); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				{
					if len(mapVal.Tags) > 0 || cst.HasValue(subTable, "tags") {
						if err := cst.SetAny(subTable, "tags", mapVal.Tags); err != nil {
							return nil, fmt.Errorf("%w", err)
						}
					}
				}
				if len(mapVal.StatusTags) > 0 {
					tableNode := cst.EnsureChildTable(d.cstDoc.Root(), subTable, "status-tags")
					cst.DeleteAllValues(tableNode)
					for k, v := range mapVal.StatusTags {
						if err := cst.SetAny(tableNode, k, v); err != nil {
							return nil, fmt.Errorf("%w", err)
						}
					}
				}
			}
		}
		if d.data.Haustoria.Orgmode != nil {
			tableNode := cst.EnsureChildTable(d.cstDoc.Root(), tableNode, "orgmode")
			if d.data.Haustoria.Orgmode.Transport != "" || cst.HasValue(tableNode, "transport") {
				if err := cst.SetAny(tableNode, "transport", d.data.Haustoria.Orgmode.Transport); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Haustoria.Orgmode.WebDAV != nil {
				tableNode := cst.EnsureChildTable(d.cstDoc.Root(), tableNode, "webdav")
				if d.data.Haustoria.Orgmode.WebDAV.URL != "" || cst.HasValue(tableNode, "url") {
					if err := cst.SetAny(tableNode, "url", d.data.Haustoria.Orgmode.WebDAV.URL); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Haustoria.Orgmode.WebDAV.Username != "" || cst.HasValue(tableNode, "username") {
					if err := cst.SetAny(tableNode, "username", d.data.Haustoria.Orgmode.WebDAV.Username); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			if d.data.Haustoria.Orgmode.SFTP != nil {
				tableNode := cst.EnsureChildTable(d.cstDoc.Root(), tableNode, "sftp")
				if d.data.Haustoria.Orgmode.SFTP.Host != "" || cst.HasValue(tableNode, "host") {
					if err := cst.SetAny(tableNode, "host", d.data.Haustoria.Orgmode.SFTP.Host); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Haustoria.Orgmode.SFTP.Port != 0 || cst.HasValue(tableNode, "port") {
					if err := cst.SetAny(tableNode, "port", d.data.Haustoria.Orgmode.SFTP.Port); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Haustoria.Orgmode.SFTP.User != "" || cst.HasValue(tableNode, "user") {
					if err := cst.SetAny(tableNode, "user", d.data.Haustoria.Orgmode.SFTP.User); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Haustoria.Orgmode.SFTP.PrivateKeyPath != "" || cst.HasValue(tableNode, "private-key-path") {
					if err := cst.SetAny(tableNode, "private-key-path", d.data.Haustoria.Orgmode.SFTP.PrivateKeyPath); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Haustoria.Orgmode.SFTP.KnownHostsFile != "" || cst.HasValue(tableNode, "known-hosts-file") {
					if err := cst.SetAny(tableNode, "known-hosts-file", d.data.Haustoria.Orgmode.SFTP.KnownHostsFile); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
		}
		if len(d.data.Haustoria.Folders) > 0 {
			for mapKey, mapVal := range d.data.Haustoria.Folders {
				subTable := cst.EnsureChildSubTable(d.cstDoc.Root(), tableNode, "folders", mapKey)
				if mapVal.Path != "" || cst.HasValue(subTable, "path") {
					if err := cst.SetAny(subTable, "path", mapVal.Path); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if mapVal.Type != "" || cst.HasValue(subTable, "type") {
					if err := cst.SetAny(subTable, "type", mapVal.Type); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				{
					if len(mapVal.Tags) > 0 || cst.HasValue(subTable, "tags") {
						if err := cst.SetAny(subTable, "tags", mapVal.Tags); err != nil {
							return nil, fmt.Errorf("%w", err)
						}
					}
				}
			}
		}
	}
	return d.cstDoc.Bytes(), nil
}
func (d *V2Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *V2Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *V2Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *V2Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *V2Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeV2Into(data *V2, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "query":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Query = v
				consumed[keyPrefix+"query"] = true
			}
		case "dry-run":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.DryRun = v
				consumed[keyPrefix+"dry-run"] = true
			}
		case "parent-path":
			if v, ok := cst.ExtractString(_kv); ok {
				data.ParentPath = v
				consumed[keyPrefix+"parent-path"] = true
			}
		case "sync-tai":
			if v, ok := cst.ExtractString(_kv); ok {
				data.SyncTai = v
				consumed[keyPrefix+"sync-tai"] = true
			}
		case "sync-digest":
			if v, ok := cst.ExtractString(_kv); ok {
				data.SyncDigest = v
				consumed[keyPrefix+"sync-digest"] = true
			}
		}
	}
	for _, _ch := range doc.Root().Children {
		if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"defaults" {
			consumed[keyPrefix+"defaults"] = true
			if err := repo_configs.DecodeDefaultsV1OmitEmptyInto(&data.Defaults, doc, _ch, consumed, keyPrefix+"defaults."); err != nil {
				return fmt.Errorf("defaults: %w", err)
			}
			break
		}
	}
	for _, _ch := range doc.Root().Children {
		if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"haustoria" {
			consumed[keyPrefix+"haustoria"] = true
			for _, _kv := range _ch.Children {
				if _kv.Kind != cst.NodeKeyValue {
					continue
				}
				switch cst.KeyValueName(_kv) {
				case "type":
					if v, ok := cst.ExtractString(_kv); ok {
						data.Haustoria.Type = v
						consumed[keyPrefix+"haustoria.type"] = true
					}
				}
			}
			{
				var _ftCaldav *cst.Node
				for _, _ch := range doc.Root().Children {
					if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"haustoria.caldav" {
						_ftCaldav = _ch
						break
					}
				}
				if _ftCaldav != nil {
					consumed[keyPrefix+"haustoria.caldav"] = true
					calDAVVal := &CalDAVConfig{}
					for _, _kv := range _ftCaldav.Children {
						if _kv.Kind != cst.NodeKeyValue {
							continue
						}
						switch cst.KeyValueName(_kv) {
						case "url":
							if v, ok := cst.ExtractString(_kv); ok {
								calDAVVal.URL = v
								consumed[keyPrefix+"haustoria.caldav.url"] = true
							}
						case "username":
							if v, ok := cst.ExtractString(_kv); ok {
								calDAVVal.Username = v
								consumed[keyPrefix+"haustoria.caldav.username"] = true
							}
						}
					}
					data.Haustoria.CalDAV = calDAVVal
				} else {
					calDAVVal := &CalDAVConfig{}
					_found := false
					for _, _kv := range _ch.Children {
						if _kv.Kind != cst.NodeKeyValue {
							continue
						}
						switch cst.KeyValueName(_kv) {
						case "url":
							if v, ok := cst.ExtractString(_kv); ok {
								calDAVVal.URL = v
								_found = true
								consumed["url"] = true
							}
						case "username":
							if v, ok := cst.ExtractString(_kv); ok {
								calDAVVal.Username = v
								_found = true
								consumed["username"] = true
							}
						}
					}
					if _found {
						data.Haustoria.CalDAV = calDAVVal
					}
				}
			}
			{
				var _mr map[string]CalendarConfig
				for _, _ch := range doc.Root().Children {
					if _ch.Kind != cst.NodeTable {
						continue
					}
					_hdr := cst.TableHeaderKey(_ch)
					if !strings.HasPrefix(_hdr, keyPrefix+"haustoria.calendars.") {
						continue
					}
					_mk := _hdr[len(keyPrefix)+len("haustoria.calendars."):]
					if strings.Contains(_mk, ".") {
						continue
					}
					if _mr == nil {
						consumed[keyPrefix+"haustoria.calendars"] = true
						_mr = make(map[string]CalendarConfig)
					}
					consumed[keyPrefix+"haustoria.calendars"+"."+_mk] = true
					var entry CalendarConfig
					for _, _kv := range _ch.Children {
						if _kv.Kind != cst.NodeKeyValue {
							continue
						}
						switch cst.KeyValueName(_kv) {
						case "url":
							if v, ok := cst.ExtractString(_kv); ok {
								entry.URL = v
								consumed[keyPrefix+keyPrefix+"haustoria.calendars."+_mk+"."+"url"] = true
							}
						case "type":
							if v, ok := cst.ExtractString(_kv); ok {
								entry.Type = v
								consumed[keyPrefix+keyPrefix+"haustoria.calendars."+_mk+"."+"type"] = true
							}
						case "tags":
							if v, ok := cst.ExtractStringSlice(_kv); ok {
								entry.Tags = v
								consumed[keyPrefix+keyPrefix+"haustoria.calendars."+_mk+"."+"tags"] = true
							}
						}
					}
					for _, _ch := range doc.Root().Children {
						if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+keyPrefix+"haustoria.calendars."+_mk+"."+"status-tags" {
							entry.StatusTags = cst.ExtractStringMap(_ch)
							consumed[keyPrefix+keyPrefix+"haustoria.calendars."+_mk+"."+"status-tags"] = true
							for _ik := range entry.StatusTags {
								consumed[keyPrefix+keyPrefix+"haustoria.calendars."+_mk+"."+"status-tags"+"."+_ik] = true
							}
							break
						}
					}
					_mr[_mk] = entry
				}
				if _mr != nil {
					data.Haustoria.Calendars = _mr
				}
			}
			{
				var _ftOrgmode *cst.Node
				for _, _ch := range doc.Root().Children {
					if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"haustoria.orgmode" {
						_ftOrgmode = _ch
						break
					}
				}
				if _ftOrgmode != nil {
					consumed[keyPrefix+"haustoria.orgmode"] = true
					orgmodeVal := &OrgmodeConfig{}
					for _, _kv := range _ftOrgmode.Children {
						if _kv.Kind != cst.NodeKeyValue {
							continue
						}
						switch cst.KeyValueName(_kv) {
						case "transport":
							if v, ok := cst.ExtractString(_kv); ok {
								orgmodeVal.Transport = v
								consumed[keyPrefix+"haustoria.orgmode.transport"] = true
							}
						}
					}
					{
						var _ftWebdav *cst.Node
						for _, _ch := range doc.Root().Children {
							if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"haustoria.orgmode.webdav" {
								_ftWebdav = _ch
								break
							}
						}
						if _ftWebdav != nil {
							consumed[keyPrefix+"haustoria.orgmode.webdav"] = true
							webDAVVal := &OrgmodeWebDAV{}
							for _, _kv := range _ftWebdav.Children {
								if _kv.Kind != cst.NodeKeyValue {
									continue
								}
								switch cst.KeyValueName(_kv) {
								case "url":
									if v, ok := cst.ExtractString(_kv); ok {
										webDAVVal.URL = v
										consumed[keyPrefix+"haustoria.orgmode.webdav.url"] = true
									}
								case "username":
									if v, ok := cst.ExtractString(_kv); ok {
										webDAVVal.Username = v
										consumed[keyPrefix+"haustoria.orgmode.webdav.username"] = true
									}
								}
							}
							orgmodeVal.WebDAV = webDAVVal
						} else {
							webDAVVal := &OrgmodeWebDAV{}
							_found := false
							for _, _kv := range _ftOrgmode.Children {
								if _kv.Kind != cst.NodeKeyValue {
									continue
								}
								switch cst.KeyValueName(_kv) {
								case "url":
									if v, ok := cst.ExtractString(_kv); ok {
										webDAVVal.URL = v
										_found = true
										consumed["url"] = true
									}
								case "username":
									if v, ok := cst.ExtractString(_kv); ok {
										webDAVVal.Username = v
										_found = true
										consumed["username"] = true
									}
								}
							}
							if _found {
								orgmodeVal.WebDAV = webDAVVal
							}
						}
					}
					{
						var _ftSftp *cst.Node
						for _, _ch := range doc.Root().Children {
							if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"haustoria.orgmode.sftp" {
								_ftSftp = _ch
								break
							}
						}
						if _ftSftp != nil {
							consumed[keyPrefix+"haustoria.orgmode.sftp"] = true
							sFTPVal := &OrgmodeSFTP{}
							for _, _kv := range _ftSftp.Children {
								if _kv.Kind != cst.NodeKeyValue {
									continue
								}
								switch cst.KeyValueName(_kv) {
								case "host":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.Host = v
										consumed[keyPrefix+"haustoria.orgmode.sftp.host"] = true
									}
								case "port":
									if v, ok := cst.ExtractInt(_kv); ok {
										sFTPVal.Port = v
										consumed[keyPrefix+"haustoria.orgmode.sftp.port"] = true
									}
								case "user":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.User = v
										consumed[keyPrefix+"haustoria.orgmode.sftp.user"] = true
									}
								case "private-key-path":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.PrivateKeyPath = v
										consumed[keyPrefix+"haustoria.orgmode.sftp.private-key-path"] = true
									}
								case "known-hosts-file":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.KnownHostsFile = v
										consumed[keyPrefix+"haustoria.orgmode.sftp.known-hosts-file"] = true
									}
								}
							}
							orgmodeVal.SFTP = sFTPVal
						} else {
							sFTPVal := &OrgmodeSFTP{}
							_found := false
							for _, _kv := range _ftOrgmode.Children {
								if _kv.Kind != cst.NodeKeyValue {
									continue
								}
								switch cst.KeyValueName(_kv) {
								case "host":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.Host = v
										_found = true
										consumed["host"] = true
									}
								case "port":
									if v, ok := cst.ExtractInt(_kv); ok {
										sFTPVal.Port = v
										_found = true
										consumed["port"] = true
									}
								case "user":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.User = v
										_found = true
										consumed["user"] = true
									}
								case "private-key-path":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.PrivateKeyPath = v
										_found = true
										consumed["private-key-path"] = true
									}
								case "known-hosts-file":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.KnownHostsFile = v
										_found = true
										consumed["known-hosts-file"] = true
									}
								}
							}
							if _found {
								orgmodeVal.SFTP = sFTPVal
							}
						}
					}
					data.Haustoria.Orgmode = orgmodeVal
				} else {
					orgmodeVal := &OrgmodeConfig{}
					_found := false
					for _, _kv := range _ch.Children {
						if _kv.Kind != cst.NodeKeyValue {
							continue
						}
						switch cst.KeyValueName(_kv) {
						case "transport":
							if v, ok := cst.ExtractString(_kv); ok {
								orgmodeVal.Transport = v
								_found = true
								consumed["transport"] = true
							}
						}
					}
					{
						var _ftWebdav *cst.Node
						for _, _ch := range doc.Root().Children {
							if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "webdav" {
								_ftWebdav = _ch
								break
							}
						}
						if _ftWebdav != nil {
							consumed["webdav"] = true
							webDAVVal := &OrgmodeWebDAV{}
							for _, _kv := range _ftWebdav.Children {
								if _kv.Kind != cst.NodeKeyValue {
									continue
								}
								switch cst.KeyValueName(_kv) {
								case "url":
									if v, ok := cst.ExtractString(_kv); ok {
										webDAVVal.URL = v
										consumed["webdav.url"] = true
									}
								case "username":
									if v, ok := cst.ExtractString(_kv); ok {
										webDAVVal.Username = v
										consumed["webdav.username"] = true
									}
								}
							}
							orgmodeVal.WebDAV = webDAVVal
						} else {
							webDAVVal := &OrgmodeWebDAV{}
							_found := false
							for _, _kv := range _ch.Children {
								if _kv.Kind != cst.NodeKeyValue {
									continue
								}
								switch cst.KeyValueName(_kv) {
								case "url":
									if v, ok := cst.ExtractString(_kv); ok {
										webDAVVal.URL = v
										_found = true
										consumed["url"] = true
									}
								case "username":
									if v, ok := cst.ExtractString(_kv); ok {
										webDAVVal.Username = v
										_found = true
										consumed["username"] = true
									}
								}
							}
							if _found {
								orgmodeVal.WebDAV = webDAVVal
							}
						}
					}
					{
						var _ftSftp *cst.Node
						for _, _ch := range doc.Root().Children {
							if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "sftp" {
								_ftSftp = _ch
								break
							}
						}
						if _ftSftp != nil {
							consumed["sftp"] = true
							sFTPVal := &OrgmodeSFTP{}
							for _, _kv := range _ftSftp.Children {
								if _kv.Kind != cst.NodeKeyValue {
									continue
								}
								switch cst.KeyValueName(_kv) {
								case "host":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.Host = v
										consumed["sftp.host"] = true
									}
								case "port":
									if v, ok := cst.ExtractInt(_kv); ok {
										sFTPVal.Port = v
										consumed["sftp.port"] = true
									}
								case "user":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.User = v
										consumed["sftp.user"] = true
									}
								case "private-key-path":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.PrivateKeyPath = v
										consumed["sftp.private-key-path"] = true
									}
								case "known-hosts-file":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.KnownHostsFile = v
										consumed["sftp.known-hosts-file"] = true
									}
								}
							}
							orgmodeVal.SFTP = sFTPVal
						} else {
							sFTPVal := &OrgmodeSFTP{}
							_found := false
							for _, _kv := range _ch.Children {
								if _kv.Kind != cst.NodeKeyValue {
									continue
								}
								switch cst.KeyValueName(_kv) {
								case "host":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.Host = v
										_found = true
										consumed["host"] = true
									}
								case "port":
									if v, ok := cst.ExtractInt(_kv); ok {
										sFTPVal.Port = v
										_found = true
										consumed["port"] = true
									}
								case "user":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.User = v
										_found = true
										consumed["user"] = true
									}
								case "private-key-path":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.PrivateKeyPath = v
										_found = true
										consumed["private-key-path"] = true
									}
								case "known-hosts-file":
									if v, ok := cst.ExtractString(_kv); ok {
										sFTPVal.KnownHostsFile = v
										_found = true
										consumed["known-hosts-file"] = true
									}
								}
							}
							if _found {
								orgmodeVal.SFTP = sFTPVal
							}
						}
					}
					if _found {
						data.Haustoria.Orgmode = orgmodeVal
					}
				}
			}
			{
				var _mr map[string]FolderConfig
				for _, _ch := range doc.Root().Children {
					if _ch.Kind != cst.NodeTable {
						continue
					}
					_hdr := cst.TableHeaderKey(_ch)
					if !strings.HasPrefix(_hdr, keyPrefix+"haustoria.folders.") {
						continue
					}
					_mk := _hdr[len(keyPrefix)+len("haustoria.folders."):]
					if strings.Contains(_mk, ".") {
						continue
					}
					if _mr == nil {
						consumed[keyPrefix+"haustoria.folders"] = true
						_mr = make(map[string]FolderConfig)
					}
					consumed[keyPrefix+"haustoria.folders"+"."+_mk] = true
					var entry FolderConfig
					for _, _kv := range _ch.Children {
						if _kv.Kind != cst.NodeKeyValue {
							continue
						}
						switch cst.KeyValueName(_kv) {
						case "path":
							if v, ok := cst.ExtractString(_kv); ok {
								entry.Path = v
								consumed[keyPrefix+keyPrefix+"haustoria.folders."+_mk+"."+"path"] = true
							}
						case "type":
							if v, ok := cst.ExtractString(_kv); ok {
								entry.Type = v
								consumed[keyPrefix+keyPrefix+"haustoria.folders."+_mk+"."+"type"] = true
							}
						case "tags":
							if v, ok := cst.ExtractStringSlice(_kv); ok {
								entry.Tags = v
								consumed[keyPrefix+keyPrefix+"haustoria.folders."+_mk+"."+"tags"] = true
							}
						}
					}
					_mr[_mk] = entry
				}
				if _mr != nil {
					data.Haustoria.Folders = _mr
				}
			}
			break
		}
	}
	return nil
}
func EncodeV2From(data *V2, doc *document.Document, container *cst.Node) error {
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "defaults")
		if err := repo_configs.EncodeDefaultsV1OmitEmptyFrom(&data.Defaults, doc, tableNode); err != nil {
			return fmt.Errorf("defaults: %w", err)
		}
	}
	if data.Query != "" {
		if err := cst.SetAny(container, "query", data.Query); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "query")
	}
	if data.DryRun != false || cst.HasValue(container, "dry-run") {
		if err := cst.SetAny(container, "dry-run", data.DryRun); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.ParentPath != "" {
		if err := cst.SetAny(container, "parent-path", data.ParentPath); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "parent-path")
	}
	if data.SyncTai != "" {
		if err := cst.SetAny(container, "sync-tai", data.SyncTai); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "sync-tai")
	}
	if data.SyncDigest != "" {
		if err := cst.SetAny(container, "sync-digest", data.SyncDigest); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "sync-digest")
	}
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "haustoria")
		if data.Haustoria.Type != "" || cst.HasValue(tableNode, "type") {
			if err := cst.SetAny(tableNode, "type", data.Haustoria.Type); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Haustoria.CalDAV != nil {
			tableNode := cst.EnsureChildTable(doc.Root(), tableNode, "caldav")
			if data.Haustoria.CalDAV.URL != "" || cst.HasValue(tableNode, "url") {
				if err := cst.SetAny(tableNode, "url", data.Haustoria.CalDAV.URL); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Haustoria.CalDAV.Username != "" || cst.HasValue(tableNode, "username") {
				if err := cst.SetAny(tableNode, "username", data.Haustoria.CalDAV.Username); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		if len(data.Haustoria.Calendars) > 0 {
			for mapKey, mapVal := range data.Haustoria.Calendars {
				subTable := cst.EnsureChildSubTable(doc.Root(), tableNode, "calendars", mapKey)
				if mapVal.URL != "" || cst.HasValue(subTable, "url") {
					if err := cst.SetAny(subTable, "url", mapVal.URL); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if mapVal.Type != "" || cst.HasValue(subTable, "type") {
					if err := cst.SetAny(subTable, "type", mapVal.Type); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				{
					if len(mapVal.Tags) > 0 || cst.HasValue(subTable, "tags") {
						if err := cst.SetAny(subTable, "tags", mapVal.Tags); err != nil {
							return fmt.Errorf("%w", err)
						}
					}
				}
				if len(mapVal.StatusTags) > 0 {
					tableNode := cst.EnsureChildTable(doc.Root(), subTable, "status-tags")
					cst.DeleteAllValues(tableNode)
					for k, v := range mapVal.StatusTags {
						if err := cst.SetAny(tableNode, k, v); err != nil {
							return fmt.Errorf("%w", err)
						}
					}
				}
			}
		}
		if data.Haustoria.Orgmode != nil {
			tableNode := cst.EnsureChildTable(doc.Root(), tableNode, "orgmode")
			if data.Haustoria.Orgmode.Transport != "" || cst.HasValue(tableNode, "transport") {
				if err := cst.SetAny(tableNode, "transport", data.Haustoria.Orgmode.Transport); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Haustoria.Orgmode.WebDAV != nil {
				tableNode := cst.EnsureChildTable(doc.Root(), tableNode, "webdav")
				if data.Haustoria.Orgmode.WebDAV.URL != "" || cst.HasValue(tableNode, "url") {
					if err := cst.SetAny(tableNode, "url", data.Haustoria.Orgmode.WebDAV.URL); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Haustoria.Orgmode.WebDAV.Username != "" || cst.HasValue(tableNode, "username") {
					if err := cst.SetAny(tableNode, "username", data.Haustoria.Orgmode.WebDAV.Username); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			if data.Haustoria.Orgmode.SFTP != nil {
				tableNode := cst.EnsureChildTable(doc.Root(), tableNode, "sftp")
				if data.Haustoria.Orgmode.SFTP.Host != "" || cst.HasValue(tableNode, "host") {
					if err := cst.SetAny(tableNode, "host", data.Haustoria.Orgmode.SFTP.Host); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Haustoria.Orgmode.SFTP.Port != 0 || cst.HasValue(tableNode, "port") {
					if err := cst.SetAny(tableNode, "port", data.Haustoria.Orgmode.SFTP.Port); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Haustoria.Orgmode.SFTP.User != "" || cst.HasValue(tableNode, "user") {
					if err := cst.SetAny(tableNode, "user", data.Haustoria.Orgmode.SFTP.User); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Haustoria.Orgmode.SFTP.PrivateKeyPath != "" || cst.HasValue(tableNode, "private-key-path") {
					if err := cst.SetAny(tableNode, "private-key-path", data.Haustoria.Orgmode.SFTP.PrivateKeyPath); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Haustoria.Orgmode.SFTP.KnownHostsFile != "" || cst.HasValue(tableNode, "known-hosts-file") {
					if err := cst.SetAny(tableNode, "known-hosts-file", data.Haustoria.Orgmode.SFTP.KnownHostsFile); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
		}
		if len(data.Haustoria.Folders) > 0 {
			for mapKey, mapVal := range data.Haustoria.Folders {
				subTable := cst.EnsureChildSubTable(doc.Root(), tableNode, "folders", mapKey)
				if mapVal.Path != "" || cst.HasValue(subTable, "path") {
					if err := cst.SetAny(subTable, "path", mapVal.Path); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if mapVal.Type != "" || cst.HasValue(subTable, "type") {
					if err := cst.SetAny(subTable, "type", mapVal.Type); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				{
					if len(mapVal.Tags) > 0 || cst.HasValue(subTable, "tags") {
						if err := cst.SetAny(subTable, "tags", mapVal.Tags); err != nil {
							return fmt.Errorf("%w", err)
						}
					}
				}
			}
		}
	}
	return nil
}
