// Code generated by tommy; DO NOT EDIT.

package workspace_config_blobs

import (
	"fmt"

	"code.linenisgreat.com/dodder/go/internal/charlie/repo_configs"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type V2Document struct {
	data     V2
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeV2(input []byte) (*V2Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &V2Document{cstDoc: doc, consumed: make(map[string]bool)}

	if tableNode := d.cstDoc.FindTable("defaults"); tableNode != nil {
		d.consumed["defaults"] = true
		if err := repo_configs.DecodeDefaultsV1OmitEmptyInto(&d.data.Defaults, d.cstDoc, tableNode, d.consumed, "defaults."); err != nil {
			return nil, fmt.Errorf("defaults: %w", err)
		}
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "query"); err == nil {
		d.data.Query = v
		d.consumed["query"] = true
	}
	if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "dry-run"); err == nil {
		d.data.DryRun = v
		d.consumed["dry-run"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "parent-path"); err == nil {
		d.data.ParentPath = v
		d.consumed["parent-path"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "sync-tai"); err == nil {
		d.data.SyncTai = v
		d.consumed["sync-tai"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "sync-digest"); err == nil {
		d.data.SyncDigest = v
		d.consumed["sync-digest"] = true
	}
	if tableNode := d.cstDoc.FindTable("haustoria"); tableNode != nil {
		d.consumed["haustoria"] = true
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "type"); err == nil {
			d.data.Haustoria.Type = v
			d.consumed["haustoria.type"] = true
		}
		if tableNode := d.cstDoc.FindTableInContainer(tableNode, "caldav"); tableNode != nil {
			d.consumed["haustoria.caldav"] = true
			calDAVVal := &CalDAVConfig{}
			if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "url"); err == nil {
				calDAVVal.URL = v
				d.consumed["haustoria.caldav.url"] = true
			}
			if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "username"); err == nil {
				calDAVVal.Username = v
				d.consumed["haustoria.caldav.username"] = true
			}
			d.data.Haustoria.CalDAV = calDAVVal
		} else {
			calDAVVal := &CalDAVConfig{}
			found := false
			if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "url"); err == nil {
				calDAVVal.URL = v
				found = true
				d.consumed["haustoria.url"] = true
			}
			if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "username"); err == nil {
				calDAVVal.Username = v
				found = true
				d.consumed["haustoria.username"] = true
			}
			if found {
				d.data.Haustoria.CalDAV = calDAVVal
			}
		}
		{
			subTables := d.cstDoc.FindSubTablesInContainer(tableNode, "calendars")
			if len(subTables) > 0 {
				d.consumed["haustoria.calendars"] = true
				d.data.Haustoria.Calendars = make(map[string]CalendarConfig)
				for _, subTable := range subTables {
					mapKey := document.SubTableKeyInContainer(subTable, tableNode, "calendars")
					d.consumed["haustoria.calendars"+"."+mapKey] = true
					var entry CalendarConfig
					if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "url"); err == nil {
						entry.URL = v
						d.consumed["haustoria.calendars.url"] = true
					}
					if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "type"); err == nil {
						entry.Type = v
						d.consumed["haustoria.calendars.type"] = true
					}
					if v, err := document.GetFromContainer[[]string](d.cstDoc, subTable, "tags"); err == nil {
						entry.Tags = v
						d.consumed["haustoria.calendars.tags"] = true
					}
					d.data.Haustoria.Calendars[mapKey] = entry
				}
			}
		}
	}

	return d, nil
}

func (d *V2Document) Data() *V2 { return &d.data }

func (d *V2Document) Encode() ([]byte, error) {
	{
		tableNode := d.cstDoc.EnsureTable("defaults")
		if err := repo_configs.EncodeDefaultsV1OmitEmptyFrom(&d.data.Defaults, d.cstDoc, tableNode); err != nil {
			return nil, fmt.Errorf("defaults: %w", err)
		}
	}
	if d.data.Query != "" {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "query", d.data.Query); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "query")
	}
	if d.data.DryRun != false || d.cstDoc.HasInContainer(d.cstDoc.Root(), "dry-run") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "dry-run", d.data.DryRun); err != nil {
			return nil, err
		}
	}
	if d.data.ParentPath != "" {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "parent-path", d.data.ParentPath); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "parent-path")
	}
	if d.data.SyncTai != "" {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "sync-tai", d.data.SyncTai); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "sync-tai")
	}
	if d.data.SyncDigest != "" {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "sync-digest", d.data.SyncDigest); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "sync-digest")
	}
	{
		tableNode := d.cstDoc.EnsureTable("haustoria")
		if d.data.Haustoria.Type != "" || d.cstDoc.HasInContainer(tableNode, "type") {
			if err := d.cstDoc.SetInContainer(tableNode, "type", d.data.Haustoria.Type); err != nil {
				return nil, err
			}
		}
		if d.data.Haustoria.CalDAV != nil {
			tableNode := d.cstDoc.EnsureTableInContainer(tableNode, "caldav")
			if d.data.Haustoria.CalDAV.URL != "" || d.cstDoc.HasInContainer(tableNode, "url") {
				if err := d.cstDoc.SetInContainer(tableNode, "url", d.data.Haustoria.CalDAV.URL); err != nil {
					return nil, err
				}
			}
			if d.data.Haustoria.CalDAV.Username != "" || d.cstDoc.HasInContainer(tableNode, "username") {
				if err := d.cstDoc.SetInContainer(tableNode, "username", d.data.Haustoria.CalDAV.Username); err != nil {
					return nil, err
				}
			}
		}
		if len(d.data.Haustoria.Calendars) > 0 {
			for mapKey, mapVal := range d.data.Haustoria.Calendars {
				subTable := d.cstDoc.EnsureSubTableInContainer(tableNode, "calendars", mapKey)
				if mapVal.URL != "" || d.cstDoc.HasInContainer(subTable, "url") {
					if err := d.cstDoc.SetInContainer(subTable, "url", mapVal.URL); err != nil {
						return nil, err
					}
				}
				if mapVal.Type != "" || d.cstDoc.HasInContainer(subTable, "type") {
					if err := d.cstDoc.SetInContainer(subTable, "type", mapVal.Type); err != nil {
						return nil, err
					}
				}
				if len(mapVal.Tags) > 0 || d.cstDoc.HasInContainer(subTable, "tags") {
					if err := d.cstDoc.SetInContainer(subTable, "tags", mapVal.Tags); err != nil {
						return nil, err
					}
				}
			}
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *V2Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func (d *V2Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *V2Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *V2Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *V2Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeV2Into(data *V2, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	if tableNode := doc.FindTableInContainer(container, "defaults"); tableNode != nil {
		consumed[keyPrefix+"defaults"] = true
		if err := repo_configs.DecodeDefaultsV1OmitEmptyInto(&data.Defaults, doc, tableNode, consumed, keyPrefix+"defaults."); err != nil {
			return fmt.Errorf("defaults: %w", err)
		}
	}
	if v, err := document.GetFromContainer[string](doc, container, "query"); err == nil {
		data.Query = v
		consumed[keyPrefix+"query"] = true
	}
	if v, err := document.GetFromContainer[bool](doc, container, "dry-run"); err == nil {
		data.DryRun = v
		consumed[keyPrefix+"dry-run"] = true
	}
	if v, err := document.GetFromContainer[string](doc, container, "parent-path"); err == nil {
		data.ParentPath = v
		consumed[keyPrefix+"parent-path"] = true
	}
	if v, err := document.GetFromContainer[string](doc, container, "sync-tai"); err == nil {
		data.SyncTai = v
		consumed[keyPrefix+"sync-tai"] = true
	}
	if v, err := document.GetFromContainer[string](doc, container, "sync-digest"); err == nil {
		data.SyncDigest = v
		consumed[keyPrefix+"sync-digest"] = true
	}
	if tableNode := doc.FindTableInContainer(container, "haustoria"); tableNode != nil {
		consumed[keyPrefix+"haustoria"] = true
		if v, err := document.GetFromContainer[string](doc, tableNode, "type"); err == nil {
			data.Haustoria.Type = v
			consumed[keyPrefix+"haustoria.type"] = true
		}
		if tableNode := doc.FindTableInContainer(tableNode, "caldav"); tableNode != nil {
			consumed[keyPrefix+"haustoria.caldav"] = true
			calDAVVal := &CalDAVConfig{}
			if v, err := document.GetFromContainer[string](doc, tableNode, "url"); err == nil {
				calDAVVal.URL = v
				consumed[keyPrefix+"haustoria.caldav.url"] = true
			}
			if v, err := document.GetFromContainer[string](doc, tableNode, "username"); err == nil {
				calDAVVal.Username = v
				consumed[keyPrefix+"haustoria.caldav.username"] = true
			}
			data.Haustoria.CalDAV = calDAVVal
		} else {
			calDAVVal := &CalDAVConfig{}
			found := false
			if v, err := document.GetFromContainer[string](doc, tableNode, "url"); err == nil {
				calDAVVal.URL = v
				found = true
				consumed[keyPrefix+"haustoria.url"] = true
			}
			if v, err := document.GetFromContainer[string](doc, tableNode, "username"); err == nil {
				calDAVVal.Username = v
				found = true
				consumed[keyPrefix+"haustoria.username"] = true
			}
			if found {
				data.Haustoria.CalDAV = calDAVVal
			}
		}
		{
			subTables := doc.FindSubTablesInContainer(tableNode, "calendars")
			if len(subTables) > 0 {
				consumed[keyPrefix+"haustoria.calendars"] = true
				data.Haustoria.Calendars = make(map[string]CalendarConfig)
				for _, subTable := range subTables {
					mapKey := document.SubTableKeyInContainer(subTable, tableNode, "calendars")
					consumed[keyPrefix+"haustoria.calendars"+"."+mapKey] = true
					var entry CalendarConfig
					if v, err := document.GetFromContainer[string](doc, subTable, "url"); err == nil {
						entry.URL = v
						consumed[keyPrefix+"haustoria.calendars.url"] = true
					}
					if v, err := document.GetFromContainer[string](doc, subTable, "type"); err == nil {
						entry.Type = v
						consumed[keyPrefix+"haustoria.calendars.type"] = true
					}
					if v, err := document.GetFromContainer[[]string](doc, subTable, "tags"); err == nil {
						entry.Tags = v
						consumed[keyPrefix+"haustoria.calendars.tags"] = true
					}
					data.Haustoria.Calendars[mapKey] = entry
				}
			}
		}
	}

	return nil
}

func EncodeV2From(data *V2, doc *document.Document, container *cst.Node) error {
	{
		tableNode := doc.EnsureTableInContainer(container, "defaults")
		if err := repo_configs.EncodeDefaultsV1OmitEmptyFrom(&data.Defaults, doc, tableNode); err != nil {
			return fmt.Errorf("defaults: %w", err)
		}
	}
	if data.Query != "" {
		if err := doc.SetInContainer(container, "query", data.Query); err != nil {
			return err
		}
	} else {
		_ = doc.DeleteFromContainer(container, "query")
	}
	if data.DryRun != false || doc.HasInContainer(container, "dry-run") {
		if err := doc.SetInContainer(container, "dry-run", data.DryRun); err != nil {
			return err
		}
	}
	if data.ParentPath != "" {
		if err := doc.SetInContainer(container, "parent-path", data.ParentPath); err != nil {
			return err
		}
	} else {
		_ = doc.DeleteFromContainer(container, "parent-path")
	}
	if data.SyncTai != "" {
		if err := doc.SetInContainer(container, "sync-tai", data.SyncTai); err != nil {
			return err
		}
	} else {
		_ = doc.DeleteFromContainer(container, "sync-tai")
	}
	if data.SyncDigest != "" {
		if err := doc.SetInContainer(container, "sync-digest", data.SyncDigest); err != nil {
			return err
		}
	} else {
		_ = doc.DeleteFromContainer(container, "sync-digest")
	}
	{
		tableNode := doc.EnsureTableInContainer(container, "haustoria")
		if data.Haustoria.Type != "" || doc.HasInContainer(tableNode, "type") {
			if err := doc.SetInContainer(tableNode, "type", data.Haustoria.Type); err != nil {
				return err
			}
		}
		if data.Haustoria.CalDAV != nil {
			tableNode := doc.EnsureTableInContainer(tableNode, "caldav")
			if data.Haustoria.CalDAV.URL != "" || doc.HasInContainer(tableNode, "url") {
				if err := doc.SetInContainer(tableNode, "url", data.Haustoria.CalDAV.URL); err != nil {
					return err
				}
			}
			if data.Haustoria.CalDAV.Username != "" || doc.HasInContainer(tableNode, "username") {
				if err := doc.SetInContainer(tableNode, "username", data.Haustoria.CalDAV.Username); err != nil {
					return err
				}
			}
		}
		if len(data.Haustoria.Calendars) > 0 {
			for mapKey, mapVal := range data.Haustoria.Calendars {
				subTable := doc.EnsureSubTableInContainer(tableNode, "calendars", mapKey)
				if mapVal.URL != "" || doc.HasInContainer(subTable, "url") {
					if err := doc.SetInContainer(subTable, "url", mapVal.URL); err != nil {
						return err
					}
				}
				if mapVal.Type != "" || doc.HasInContainer(subTable, "type") {
					if err := doc.SetInContainer(subTable, "type", mapVal.Type); err != nil {
						return err
					}
				}
				if len(mapVal.Tags) > 0 || doc.HasInContainer(subTable, "tags") {
					if err := doc.SetInContainer(subTable, "tags", mapVal.Tags); err != nil {
						return err
					}
				}
			}
		}
	}

	return nil
}
