set output-format := "tap"

bin_dir := env("BATS_BIN_DIR", "")
# Exclude af_unix-tagged files; they need --no-sandbox (see test-tags-no-sandbox).
_non_af_unix_bats := `grep -L 'file_tags=.*af_unix' current_version/*.bats | tr '\n' ' '`
_bin_dir_arg := if bin_dir != "" { "--bin-dir " + bin_dir } else { "" }

export DODDER_XDG_UTILITY_OVERRIDE := ""

default: test

[group("clean")]
clean-fixtures:
  #! /bin/bash -e

  dir="previous_versions/v$(dodder info store-version)"
  git reset HEAD "$dir" >/dev/null 2>&1
  ./../bin/chflags.bash -R nouchg "$dir" >/dev/null 2>&1
  git clean -fd "$dir" >/dev/null 2>&1
  git checkout "$dir" >/dev/null 2>&1

[group("clean")]
@clean: clean-fixtures


[group("debug")]
debug-env store_version=`echo "v$(dodder info store-version)"`:
  #! /bin/bash -ex
  dir="$(mktemp -d)"
  trap "rm -rf '$dir'" EXIT

  cp -r previous_versions/{{store_version}}/.xdg "$dir/.xdg"

  echo 'source_env "{{invocation_dir()}}/.envrc"' >> "$dir/.envrc"
  echo 'dotenv ./.env' >> "$dir/.envrc"
  direnv allow "$dir/.envrc"
  trap "direnv disallow \"$dir/.envrc\"" EXIT

  cat - > "$dir/.env" <<-EOM
    export XDG_DATA_HOME="$dir/.xdg/data"
    export XDG_CONFIG_HOME="$dir/.xdg/config"
    export XDG_STATE_HOME="$dir/.xdg/state"
    export XDG_CACHE_HOME="$dir/.xdg/cache"
    export XDG_RUNTIME_HOME="$dir/.xdg/runtime"
  EOM

  pushd "$dir"
  direnv exec . "$SHELL"

#   _____         _
#  |_   _|__  ___| |_
#    | |/ _ \/ __| __|
#    | |  __/\__ \ |_
#    |_|\___||___/\__|
#

[group("test")]
test-generate_fixtures:
  #! /bin/bash -e
  which dodder
  export DODDER_VERSION="v$(dodder info store-version)"
  ./previous_versions/generate_fixture.bash

bats_timeout := "30"

# runs specific bats test files, or a default of all.
[group("test")]
test-targets *targets="current_version/*.bats":
  BATS_TEST_TIMEOUT="{{bats_timeout}}" \
    bats {{_bin_dir_arg}} --jobs {{num_cpus()}} {{targets}}

# runs specific bats test tags
[group("test")]
test-tags *tags:
  BATS_TEST_TIMEOUT="{{bats_timeout}}" \
    bats {{_bin_dir_arg}} --jobs {{num_cpus()}} --filter-tags {{tags}} current_version/*.bats

# runs specific bats test tags without sandbox
[group("test")]
test-tags-no-sandbox *tags:
  BATS_TEST_TIMEOUT="{{bats_timeout}}" \
    bats {{_bin_dir_arg}} --no-sandbox --jobs {{num_cpus()}} --filter-tags {{tags}} current_version/*.bats

[group("test")]
test-integration: (test-targets "current_version/*.bats")

[group("test")]
test-migration: (test-targets "previous_versions/main.bats")

[group("test")]
test *flags: (test-targets flags _non_af_unix_bats "previous_versions/main.bats")

#   ____  _        _
#  / ___|| |_ __ _| |_ ___
#  \___ \| __/ _` | __/ __|
#   ___) | || (_| | |_\__ \
#  |____/ \__\__,_|\__|___/
#

[group("stats")]
@stats-skipped:
  echo -n "skipped bats tests: "
  ag '^\s+skip' -c | cut -d: -f2 | grep -v '^$' | paste -s -d + - | bc

[group("stats")]
@stats-todos:
  #! /usr/bin/env -S fish
  echo -n "todos: "
  count-pattern '#\s*todo[-\w]*' | sort -n -r

[group("stats")]
@stats-loc:
  echo -n "bats loc:"
  find . -type f -print0 | xargs -0 wc -l | tail -n 1

[group("stats")]
@stats: stats-skipped stats-todos stats-loc
