// Code generated by tommy 0.4.7 (68213be); DO NOT EDIT.

package workspace_config_value_blobs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/dodder/go/internal/charlie/repo_configs"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type V0Document struct {
	data   V0
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeV0(input []byte) (*V0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &V0Document{
		cstDoc: doc,
		model:  model,
	}

	if _vDefaults, _ok := model.Get("defaults"); _ok && _vDefaults.Kind == cst.VTable {
		_vDefaults.MarkSeen()
		if err := repo_configs.DecodeDefaultsV1OmitEmptyInto(&d.data.Defaults, _vDefaults); err != nil {
			return nil, fmt.Errorf("defaults: %w", err)
		}
	}
	if _vQuery, _ok := model.Get("query"); _ok && _vQuery.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vQuery.Leaf); _xok {
			d.data.Query = _x
			_vQuery.MarkConsumed()
		}
	}
	if _vDryRun, _ok := model.Get("dry-run"); _ok && _vDryRun.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vDryRun.Leaf); _xok {
			d.data.DryRun = _x
			_vDryRun.MarkConsumed()
		}
	}
	return d, nil
}

func (d *V0Document) Data() *V0 {
	return &d.data
}

func (d *V0Document) Encode() ([]byte, error) {
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "defaults")
		if err := repo_configs.EncodeDefaultsV1OmitEmptyFrom(&d.data.Defaults, d.cstDoc, tableNode); err != nil {
			return nil, fmt.Errorf("defaults: %w", err)
		}
	}
	if d.data.Query != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "query", d.data.Query); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "query")
	}
	if d.data.DryRun != false || cst.HasValue(d.cstDoc.Root(), "dry-run") {
		if err := cst.SetAny(d.cstDoc.Root(), "dry-run", d.data.DryRun); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *V0Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *V0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *V0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *V0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *V0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeV0Into(data *V0, sub *cst.Value) error {
	if _vDefaults, _ok := sub.Get("defaults"); _ok && _vDefaults.Kind == cst.VTable {
		_vDefaults.MarkSeen()
		if err := repo_configs.DecodeDefaultsV1OmitEmptyInto(&data.Defaults, _vDefaults); err != nil {
			return fmt.Errorf("defaults: %w", err)
		}
	}
	if _vQuery, _ok := sub.Get("query"); _ok && _vQuery.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vQuery.Leaf); _xok {
			data.Query = _x
			_vQuery.MarkConsumed()
		}
	}
	if _vDryRun, _ok := sub.Get("dry-run"); _ok && _vDryRun.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vDryRun.Leaf); _xok {
			data.DryRun = _x
			_vDryRun.MarkConsumed()
		}
	}
	return nil
}

func EncodeV0From(data *V0, doc *document.Document, container *cst.Node) error {
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "defaults")
		if err := repo_configs.EncodeDefaultsV1OmitEmptyFrom(&data.Defaults, doc, tableNode); err != nil {
			return fmt.Errorf("defaults: %w", err)
		}
	}
	if data.Query != "" {
		if err := cst.SetAny(container, "query", data.Query); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "query")
	}
	if data.DryRun != false || cst.HasValue(container, "dry-run") {
		if err := cst.SetAny(container, "dry-run", data.DryRun); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
