// Code generated by tommy 0.5.0 (47364f2); DO NOT EDIT.

package workspace_config_value_blobs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/dodder/go/internal/charlie/repo_configs"
	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type V1Document struct {
	data   V1
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeV1(input []byte) (*V1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	return decodeV1Parsed(doc)
}

// DecodeV1Strict is DecodeV1 for input that must be exactly what it
// claims: it returns a *cst.SyntaxError when input is not well-formed TOML and
// *cst.TypeError values when a key's TOML type does not match its field, where
// DecodeV1 would decode leniently. Keys no field claims are not errors; they
// stay in Undecoded.
func DecodeV1Strict(input []byte) (*V1Document, error) {
	doc, err := document.ParseStrict(input)
	if err != nil {
		return nil, err
	}
	d, err := decodeV1Parsed(doc)
	if err != nil {
		return nil, err
	}
	if err := d.model.TypeErrors(); err != nil {
		return nil, err
	}
	return d, nil
}

func decodeV1Parsed(doc *document.Document) (*V1Document, error) {
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &V1Document{
		cstDoc: doc,
		model:  model,
	}

	if _vDefaults, _ok := model.Field("defaults"); _ok && _vDefaults.Kind == cst.VTable {
		_vDefaults.MarkSeen()
		if err := repo_configs.DecodeDefaultsV1OmitEmptyInto(&d.data.Defaults, _vDefaults); err != nil {
			return nil, fmt.Errorf("defaults: %w", err)
		}
	}
	if _vQuery, _ok := model.Field("query"); _ok && _vQuery.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vQuery.Leaf); _xok {
			d.data.Query = _x
			_vQuery.MarkConsumedString()
		}
	}
	if _vDryRun, _ok := model.Field("dry-run"); _ok && _vDryRun.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vDryRun.Leaf); _xok {
			d.data.DryRun = _x
			_vDryRun.MarkConsumed()
		}
	}
	if _vParentPath, _ok := model.Field("parent-path"); _ok && _vParentPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vParentPath.Leaf); _xok {
			d.data.ParentPath = _x
			_vParentPath.MarkConsumedString()
		}
	}
	if _vParentPubkey, _ok := model.Field("parent-pubkey"); _ok && _vParentPubkey.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vParentPubkey.Leaf); _xok {
			d.data.ParentPubkey = _x
			_vParentPubkey.MarkConsumedString()
		}
	}
	if _vSyncTai, _ok := model.Field("sync-tai"); _ok && _vSyncTai.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vSyncTai.Leaf); _xok {
			d.data.SyncTai = _x
			_vSyncTai.MarkConsumedString()
		}
	}
	if _vSyncDigest, _ok := model.Field("sync-digest"); _ok && _vSyncDigest.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vSyncDigest.Leaf); _xok {
			d.data.SyncDigest = _x
			_vSyncDigest.MarkConsumedString()
		}
	}
	return d, nil
}

func (d *V1Document) Data() *V1 {
	return &d.data
}

func (d *V1Document) Encode() ([]byte, error) {
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "defaults")
		if err := repo_configs.EncodeDefaultsV1OmitEmptyFrom(&d.data.Defaults, d.cstDoc, tableNode); err != nil {
			return nil, fmt.Errorf("defaults: %w", err)
		}
	}
	if d.data.Query != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "query", d.data.Query); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "query")
	}
	if d.data.DryRun != false || cst.HasValue(d.cstDoc.Root(), "dry-run") {
		if err := cst.SetAny(d.cstDoc.Root(), "dry-run", d.data.DryRun); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.ParentPath != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "parent-path", d.data.ParentPath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "parent-path")
	}
	if d.data.ParentPubkey != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "parent-pubkey", d.data.ParentPubkey); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "parent-pubkey")
	}
	if d.data.SyncTai != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "sync-tai", d.data.SyncTai); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "sync-tai")
	}
	if d.data.SyncDigest != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "sync-digest", d.data.SyncDigest); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "sync-digest")
	}
	return d.cstDoc.Bytes(), nil
}

func (d *V1Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *V1Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *V1Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *V1Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *V1Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeV1Into(data *V1, sub *cst.Value) error {
	if _vDefaults, _ok := sub.Field("defaults"); _ok && _vDefaults.Kind == cst.VTable {
		_vDefaults.MarkSeen()
		if err := repo_configs.DecodeDefaultsV1OmitEmptyInto(&data.Defaults, _vDefaults); err != nil {
			return fmt.Errorf("defaults: %w", err)
		}
	}
	if _vQuery, _ok := sub.Field("query"); _ok && _vQuery.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vQuery.Leaf); _xok {
			data.Query = _x
			_vQuery.MarkConsumedString()
		}
	}
	if _vDryRun, _ok := sub.Field("dry-run"); _ok && _vDryRun.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vDryRun.Leaf); _xok {
			data.DryRun = _x
			_vDryRun.MarkConsumed()
		}
	}
	if _vParentPath, _ok := sub.Field("parent-path"); _ok && _vParentPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vParentPath.Leaf); _xok {
			data.ParentPath = _x
			_vParentPath.MarkConsumedString()
		}
	}
	if _vParentPubkey, _ok := sub.Field("parent-pubkey"); _ok && _vParentPubkey.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vParentPubkey.Leaf); _xok {
			data.ParentPubkey = _x
			_vParentPubkey.MarkConsumedString()
		}
	}
	if _vSyncTai, _ok := sub.Field("sync-tai"); _ok && _vSyncTai.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vSyncTai.Leaf); _xok {
			data.SyncTai = _x
			_vSyncTai.MarkConsumedString()
		}
	}
	if _vSyncDigest, _ok := sub.Field("sync-digest"); _ok && _vSyncDigest.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vSyncDigest.Leaf); _xok {
			data.SyncDigest = _x
			_vSyncDigest.MarkConsumedString()
		}
	}
	return nil
}

func EncodeV1From(data *V1, doc *document.Document, container *cst.Node) error {
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "defaults")
		if err := repo_configs.EncodeDefaultsV1OmitEmptyFrom(&data.Defaults, doc, tableNode); err != nil {
			return fmt.Errorf("defaults: %w", err)
		}
	}
	if data.Query != "" {
		if err := cst.SetAny(container, "query", data.Query); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "query")
	}
	if data.DryRun != false || cst.HasValue(container, "dry-run") {
		if err := cst.SetAny(container, "dry-run", data.DryRun); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.ParentPath != "" {
		if err := cst.SetAny(container, "parent-path", data.ParentPath); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "parent-path")
	}
	if data.ParentPubkey != "" {
		if err := cst.SetAny(container, "parent-pubkey", data.ParentPubkey); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "parent-pubkey")
	}
	if data.SyncTai != "" {
		if err := cst.SetAny(container, "sync-tai", data.SyncTai); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "sync-tai")
	}
	if data.SyncDigest != "" {
		if err := cst.SetAny(container, "sync-digest", data.SyncDigest); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "sync-digest")
	}
	return nil
}
