// Code generated by tommy 0.4.7 (14364c7); DO NOT EDIT.

package workspace_config_value_blobs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/dodder/go/internal/charlie/repo_configs"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type V3Document struct {
	data   V3
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeV3(input []byte) (*V3Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &V3Document{
		cstDoc: doc,
		model:  model,
	}

	if _vDefaults, _ok := model.Get("defaults"); _ok && _vDefaults.Kind == cst.VTable {
		_vDefaults.MarkSeen()
		if err := repo_configs.DecodeDefaultsV1OmitEmptyInto(&d.data.Defaults, _vDefaults); err != nil {
			return nil, fmt.Errorf("defaults: %w", err)
		}
	}
	if _vQuery, _ok := model.Get("query"); _ok && _vQuery.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vQuery.Leaf); _xok {
			d.data.Query = _x
			_vQuery.MarkConsumed()
		}
	}
	if _vDryRun, _ok := model.Get("dry-run"); _ok && _vDryRun.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vDryRun.Leaf); _xok {
			d.data.DryRun = _x
			_vDryRun.MarkConsumed()
		}
	}
	if _vParentPath, _ok := model.Get("parent-path"); _ok && _vParentPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vParentPath.Leaf); _xok {
			d.data.ParentPath = _x
			_vParentPath.MarkConsumed()
		}
	}
	if _vSyncTai, _ok := model.Get("sync-tai"); _ok && _vSyncTai.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vSyncTai.Leaf); _xok {
			d.data.SyncTai = _x
			_vSyncTai.MarkConsumed()
		}
	}
	if _vSyncDigest, _ok := model.Get("sync-digest"); _ok && _vSyncDigest.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vSyncDigest.Leaf); _xok {
			d.data.SyncDigest = _x
			_vSyncDigest.MarkConsumed()
		}
	}
	if _vHaustoria, _ok := model.Get("haustoria"); _ok && _vHaustoria.Kind == cst.VTable {
		_vHaustoria.MarkSeen()
		if _vHaustoriaType, _ok := _vHaustoria.Get("type"); _ok && _vHaustoriaType.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHaustoriaType.Leaf); _xok {
				d.data.Haustoria.Type = _x
				_vHaustoriaType.MarkConsumed()
			}
		}
		if _vHaustoriaCaldav, _ok := _vHaustoria.Get("caldav"); _ok && _vHaustoriaCaldav.Kind == cst.VTable {
			_vHaustoriaCaldav.MarkSeen()
			calDAVVal0 := &CalDAVConfig{}
			if _vHaustoriaCaldavUrl, _ok := _vHaustoriaCaldav.Get("url"); _ok && _vHaustoriaCaldavUrl.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vHaustoriaCaldavUrl.Leaf); _xok {
					calDAVVal0.URL = _x
					_vHaustoriaCaldavUrl.MarkConsumed()
				}
			}
			if _vHaustoriaCaldavUsername, _ok := _vHaustoriaCaldav.Get("username"); _ok && _vHaustoriaCaldavUsername.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vHaustoriaCaldavUsername.Leaf); _xok {
					calDAVVal0.Username = _x
					_vHaustoriaCaldavUsername.MarkConsumed()
				}
			}
			d.data.Haustoria.CalDAV = calDAVVal0
		} else {
			calDAVVal0 := &CalDAVConfig{}
			_foundHaustoriaCaldav := false
			if _vUrl, _ok := _vHaustoria.Get("url"); _ok && _vUrl.Kind == cst.VLeaf {
				_foundHaustoriaCaldav = true
				if _x, _xok := cst.ExtractString(_vUrl.Leaf); _xok {
					calDAVVal0.URL = _x
					_vUrl.MarkConsumed()
				}
			}
			if _vUsername, _ok := _vHaustoria.Get("username"); _ok && _vUsername.Kind == cst.VLeaf {
				_foundHaustoriaCaldav = true
				if _x, _xok := cst.ExtractString(_vUsername.Leaf); _xok {
					calDAVVal0.Username = _x
					_vUsername.MarkConsumed()
				}
			}
			if _foundHaustoriaCaldav {
				d.data.Haustoria.CalDAV = calDAVVal0
			}
		}
		if _vHaustoriaCalendars, _ok := _vHaustoria.Get("calendars"); _ok && _vHaustoriaCalendars.Kind == cst.VTable {
			_vHaustoriaCalendars.MarkSeen()
			d.data.Haustoria.Calendars = make(map[string]CalendarConfig)
			for _mk1i := range _vHaustoriaCalendars.Fields {
				_mk1e := &_vHaustoriaCalendars.Fields[_mk1i]
				if _mk1e.Val.Kind == cst.VTable {
					_mk1e.Val.MarkSeen()
					var entry2 CalendarConfig
					if _vHaustoriaCalendarsUrl, _ok := _mk1e.Val.Get("url"); _ok && _vHaustoriaCalendarsUrl.Kind == cst.VLeaf {
						if _x, _xok := cst.ExtractString(_vHaustoriaCalendarsUrl.Leaf); _xok {
							entry2.URL = _x
							_vHaustoriaCalendarsUrl.MarkConsumed()
						}
					}
					if _vHaustoriaCalendarsType, _ok := _mk1e.Val.Get("type"); _ok && _vHaustoriaCalendarsType.Kind == cst.VLeaf {
						if _x, _xok := cst.ExtractString(_vHaustoriaCalendarsType.Leaf); _xok {
							entry2.Type = _x
							_vHaustoriaCalendarsType.MarkConsumed()
						}
					}
					if _vHaustoriaCalendarsTags, _ok := _mk1e.Val.Get("tags"); _ok && _vHaustoriaCalendarsTags.Kind == cst.VLeaf {
						if _x, _xok := cst.ExtractStringSlice(_vHaustoriaCalendarsTags.Leaf); _xok {
							entry2.Tags = _x
							if entry2.Tags == nil {
								entry2.Tags = []string{}
							}
							_vHaustoriaCalendarsTags.MarkConsumed()
						}
					}
					d.data.Haustoria.Calendars[_mk1e.Key] = entry2
				}
			}
		}
		if _vHaustoriaOrgmode, _ok := _vHaustoria.Get("orgmode"); _ok && _vHaustoriaOrgmode.Kind == cst.VTable {
			_vHaustoriaOrgmode.MarkSeen()
			orgmodeVal3 := &OrgmodeConfig{}
			if _vHaustoriaOrgmodeTransport, _ok := _vHaustoriaOrgmode.Get("transport"); _ok && _vHaustoriaOrgmodeTransport.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vHaustoriaOrgmodeTransport.Leaf); _xok {
					orgmodeVal3.Transport = _x
					_vHaustoriaOrgmodeTransport.MarkConsumed()
				}
			}
			if _vHaustoriaOrgmodeWebdav, _ok := _vHaustoriaOrgmode.Get("webdav"); _ok && _vHaustoriaOrgmodeWebdav.Kind == cst.VTable {
				_vHaustoriaOrgmodeWebdav.MarkSeen()
				webDAVVal4 := &OrgmodeWebDAV{}
				if _vHaustoriaOrgmodeWebdavUrl, _ok := _vHaustoriaOrgmodeWebdav.Get("url"); _ok && _vHaustoriaOrgmodeWebdavUrl.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vHaustoriaOrgmodeWebdavUrl.Leaf); _xok {
						webDAVVal4.URL = _x
						_vHaustoriaOrgmodeWebdavUrl.MarkConsumed()
					}
				}
				if _vHaustoriaOrgmodeWebdavUsername, _ok := _vHaustoriaOrgmodeWebdav.Get("username"); _ok && _vHaustoriaOrgmodeWebdavUsername.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vHaustoriaOrgmodeWebdavUsername.Leaf); _xok {
						webDAVVal4.Username = _x
						_vHaustoriaOrgmodeWebdavUsername.MarkConsumed()
					}
				}
				orgmodeVal3.WebDAV = webDAVVal4
			} else {
				webDAVVal4 := &OrgmodeWebDAV{}
				_foundHaustoriaOrgmodeWebdav := false
				if _vUrl, _ok := _vHaustoriaOrgmode.Get("url"); _ok && _vUrl.Kind == cst.VLeaf {
					_foundHaustoriaOrgmodeWebdav = true
					if _x, _xok := cst.ExtractString(_vUrl.Leaf); _xok {
						webDAVVal4.URL = _x
						_vUrl.MarkConsumed()
					}
				}
				if _vUsername, _ok := _vHaustoriaOrgmode.Get("username"); _ok && _vUsername.Kind == cst.VLeaf {
					_foundHaustoriaOrgmodeWebdav = true
					if _x, _xok := cst.ExtractString(_vUsername.Leaf); _xok {
						webDAVVal4.Username = _x
						_vUsername.MarkConsumed()
					}
				}
				if _foundHaustoriaOrgmodeWebdav {
					orgmodeVal3.WebDAV = webDAVVal4
				}
			}
			if _vHaustoriaOrgmodeSftp, _ok := _vHaustoriaOrgmode.Get("sftp"); _ok && _vHaustoriaOrgmodeSftp.Kind == cst.VTable {
				_vHaustoriaOrgmodeSftp.MarkSeen()
				sFTPVal5 := &OrgmodeSFTP{}
				if _vHaustoriaOrgmodeSftpHost, _ok := _vHaustoriaOrgmodeSftp.Get("host"); _ok && _vHaustoriaOrgmodeSftpHost.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vHaustoriaOrgmodeSftpHost.Leaf); _xok {
						sFTPVal5.Host = _x
						_vHaustoriaOrgmodeSftpHost.MarkConsumed()
					}
				}
				if _vHaustoriaOrgmodeSftpPort, _ok := _vHaustoriaOrgmodeSftp.Get("port"); _ok && _vHaustoriaOrgmodeSftpPort.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractInt(_vHaustoriaOrgmodeSftpPort.Leaf); _xok {
						sFTPVal5.Port = _x
						_vHaustoriaOrgmodeSftpPort.MarkConsumed()
					}
				}
				if _vHaustoriaOrgmodeSftpUser, _ok := _vHaustoriaOrgmodeSftp.Get("user"); _ok && _vHaustoriaOrgmodeSftpUser.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vHaustoriaOrgmodeSftpUser.Leaf); _xok {
						sFTPVal5.User = _x
						_vHaustoriaOrgmodeSftpUser.MarkConsumed()
					}
				}
				if _vHaustoriaOrgmodeSftpPrivateKeyPath, _ok := _vHaustoriaOrgmodeSftp.Get("private-key-path"); _ok && _vHaustoriaOrgmodeSftpPrivateKeyPath.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vHaustoriaOrgmodeSftpPrivateKeyPath.Leaf); _xok {
						sFTPVal5.PrivateKeyPath = _x
						_vHaustoriaOrgmodeSftpPrivateKeyPath.MarkConsumed()
					}
				}
				if _vHaustoriaOrgmodeSftpKnownHostsFile, _ok := _vHaustoriaOrgmodeSftp.Get("known-hosts-file"); _ok && _vHaustoriaOrgmodeSftpKnownHostsFile.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vHaustoriaOrgmodeSftpKnownHostsFile.Leaf); _xok {
						sFTPVal5.KnownHostsFile = _x
						_vHaustoriaOrgmodeSftpKnownHostsFile.MarkConsumed()
					}
				}
				orgmodeVal3.SFTP = sFTPVal5
			} else {
				sFTPVal5 := &OrgmodeSFTP{}
				_foundHaustoriaOrgmodeSftp := false
				if _vHost, _ok := _vHaustoriaOrgmode.Get("host"); _ok && _vHost.Kind == cst.VLeaf {
					_foundHaustoriaOrgmodeSftp = true
					if _x, _xok := cst.ExtractString(_vHost.Leaf); _xok {
						sFTPVal5.Host = _x
						_vHost.MarkConsumed()
					}
				}
				if _vPort, _ok := _vHaustoriaOrgmode.Get("port"); _ok && _vPort.Kind == cst.VLeaf {
					_foundHaustoriaOrgmodeSftp = true
					if _x, _xok := cst.ExtractInt(_vPort.Leaf); _xok {
						sFTPVal5.Port = _x
						_vPort.MarkConsumed()
					}
				}
				if _vUser, _ok := _vHaustoriaOrgmode.Get("user"); _ok && _vUser.Kind == cst.VLeaf {
					_foundHaustoriaOrgmodeSftp = true
					if _x, _xok := cst.ExtractString(_vUser.Leaf); _xok {
						sFTPVal5.User = _x
						_vUser.MarkConsumed()
					}
				}
				if _vPrivateKeyPath, _ok := _vHaustoriaOrgmode.Get("private-key-path"); _ok && _vPrivateKeyPath.Kind == cst.VLeaf {
					_foundHaustoriaOrgmodeSftp = true
					if _x, _xok := cst.ExtractString(_vPrivateKeyPath.Leaf); _xok {
						sFTPVal5.PrivateKeyPath = _x
						_vPrivateKeyPath.MarkConsumed()
					}
				}
				if _vKnownHostsFile, _ok := _vHaustoriaOrgmode.Get("known-hosts-file"); _ok && _vKnownHostsFile.Kind == cst.VLeaf {
					_foundHaustoriaOrgmodeSftp = true
					if _x, _xok := cst.ExtractString(_vKnownHostsFile.Leaf); _xok {
						sFTPVal5.KnownHostsFile = _x
						_vKnownHostsFile.MarkConsumed()
					}
				}
				if _foundHaustoriaOrgmodeSftp {
					orgmodeVal3.SFTP = sFTPVal5
				}
			}
			d.data.Haustoria.Orgmode = orgmodeVal3
		} else {
			orgmodeVal3 := &OrgmodeConfig{}
			_foundHaustoriaOrgmode := false
			if _vTransport, _ok := _vHaustoria.Get("transport"); _ok && _vTransport.Kind == cst.VLeaf {
				_foundHaustoriaOrgmode = true
				if _x, _xok := cst.ExtractString(_vTransport.Leaf); _xok {
					orgmodeVal3.Transport = _x
					_vTransport.MarkConsumed()
				}
			}
			if _foundHaustoriaOrgmode {
				d.data.Haustoria.Orgmode = orgmodeVal3
			}
		}
		if _vHaustoriaFolders, _ok := _vHaustoria.Get("folders"); _ok && _vHaustoriaFolders.Kind == cst.VTable {
			_vHaustoriaFolders.MarkSeen()
			d.data.Haustoria.Folders = make(map[string]FolderConfig)
			for _mk6i := range _vHaustoriaFolders.Fields {
				_mk6e := &_vHaustoriaFolders.Fields[_mk6i]
				if _mk6e.Val.Kind == cst.VTable {
					_mk6e.Val.MarkSeen()
					var entry7 FolderConfig
					if _vHaustoriaFoldersPath, _ok := _mk6e.Val.Get("path"); _ok && _vHaustoriaFoldersPath.Kind == cst.VLeaf {
						if _x, _xok := cst.ExtractString(_vHaustoriaFoldersPath.Leaf); _xok {
							entry7.Path = _x
							_vHaustoriaFoldersPath.MarkConsumed()
						}
					}
					if _vHaustoriaFoldersType, _ok := _mk6e.Val.Get("type"); _ok && _vHaustoriaFoldersType.Kind == cst.VLeaf {
						if _x, _xok := cst.ExtractString(_vHaustoriaFoldersType.Leaf); _xok {
							entry7.Type = _x
							_vHaustoriaFoldersType.MarkConsumed()
						}
					}
					if _vHaustoriaFoldersTags, _ok := _mk6e.Val.Get("tags"); _ok && _vHaustoriaFoldersTags.Kind == cst.VLeaf {
						if _x, _xok := cst.ExtractStringSlice(_vHaustoriaFoldersTags.Leaf); _xok {
							entry7.Tags = _x
							if entry7.Tags == nil {
								entry7.Tags = []string{}
							}
							_vHaustoriaFoldersTags.MarkConsumed()
						}
					}
					d.data.Haustoria.Folders[_mk6e.Key] = entry7
				}
			}
		}
	} else {
		if _vType, _ok := model.Get("type"); _ok && _vType.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vType.Leaf); _xok {
				d.data.Haustoria.Type = _x
				_vType.MarkConsumed()
			}
		}
	}
	if _vIgnore, _ok := model.Get("ignore"); _ok && _vIgnore.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vIgnore.Leaf); _xok {
			d.data.Ignore = _x
			if d.data.Ignore == nil {
				d.data.Ignore = []string{}
			}
			_vIgnore.MarkConsumed()
		}
	}
	return d, nil
}

func (d *V3Document) Data() *V3 {
	return &d.data
}

func (d *V3Document) Encode() ([]byte, error) {
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "defaults")
		if err := repo_configs.EncodeDefaultsV1OmitEmptyFrom(&d.data.Defaults, d.cstDoc, tableNode); err != nil {
			return nil, fmt.Errorf("defaults: %w", err)
		}
	}
	if d.data.Query != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "query", d.data.Query); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "query")
	}
	if d.data.DryRun != false || cst.HasValue(d.cstDoc.Root(), "dry-run") {
		if err := cst.SetAny(d.cstDoc.Root(), "dry-run", d.data.DryRun); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.ParentPath != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "parent-path", d.data.ParentPath); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "parent-path")
	}
	if d.data.SyncTai != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "sync-tai", d.data.SyncTai); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "sync-tai")
	}
	if d.data.SyncDigest != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "sync-digest", d.data.SyncDigest); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "sync-digest")
	}
	{
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "haustoria")
		if d.data.Haustoria.Type != "" || cst.HasValue(tableNode, "type") {
			if err := cst.SetAny(tableNode, "type", d.data.Haustoria.Type); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Haustoria.CalDAV != nil {
			tableNode := cst.EnsureChildTable(d.cstDoc.Root(), tableNode, "caldav")
			if d.data.Haustoria.CalDAV.URL != "" || cst.HasValue(tableNode, "url") {
				if err := cst.SetAny(tableNode, "url", d.data.Haustoria.CalDAV.URL); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Haustoria.CalDAV.Username != "" || cst.HasValue(tableNode, "username") {
				if err := cst.SetAny(tableNode, "username", d.data.Haustoria.CalDAV.Username); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
		if len(d.data.Haustoria.Calendars) > 0 {
			for mapKey, mapVal := range d.data.Haustoria.Calendars {
				subTable := cst.EnsureChildSubTable(d.cstDoc.Root(), tableNode, "calendars", mapKey)
				if mapVal.URL != "" || cst.HasValue(subTable, "url") {
					if err := cst.SetAny(subTable, "url", mapVal.URL); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if mapVal.Type != "" || cst.HasValue(subTable, "type") {
					if err := cst.SetAny(subTable, "type", mapVal.Type); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				{
					if len(mapVal.Tags) > 0 || cst.HasValue(subTable, "tags") {
						if err := cst.SetAny(subTable, "tags", mapVal.Tags); err != nil {
							return nil, fmt.Errorf("%w", err)
						}
					}
				}
			}
		}
		if d.data.Haustoria.Orgmode != nil {
			tableNode := cst.EnsureChildTable(d.cstDoc.Root(), tableNode, "orgmode")
			if d.data.Haustoria.Orgmode.Transport != "" || cst.HasValue(tableNode, "transport") {
				if err := cst.SetAny(tableNode, "transport", d.data.Haustoria.Orgmode.Transport); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
			if d.data.Haustoria.Orgmode.WebDAV != nil {
				tableNode := cst.EnsureChildTable(d.cstDoc.Root(), tableNode, "webdav")
				if d.data.Haustoria.Orgmode.WebDAV.URL != "" || cst.HasValue(tableNode, "url") {
					if err := cst.SetAny(tableNode, "url", d.data.Haustoria.Orgmode.WebDAV.URL); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Haustoria.Orgmode.WebDAV.Username != "" || cst.HasValue(tableNode, "username") {
					if err := cst.SetAny(tableNode, "username", d.data.Haustoria.Orgmode.WebDAV.Username); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
			if d.data.Haustoria.Orgmode.SFTP != nil {
				tableNode := cst.EnsureChildTable(d.cstDoc.Root(), tableNode, "sftp")
				if d.data.Haustoria.Orgmode.SFTP.Host != "" || cst.HasValue(tableNode, "host") {
					if err := cst.SetAny(tableNode, "host", d.data.Haustoria.Orgmode.SFTP.Host); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Haustoria.Orgmode.SFTP.Port != 0 || cst.HasValue(tableNode, "port") {
					if err := cst.SetAny(tableNode, "port", d.data.Haustoria.Orgmode.SFTP.Port); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Haustoria.Orgmode.SFTP.User != "" || cst.HasValue(tableNode, "user") {
					if err := cst.SetAny(tableNode, "user", d.data.Haustoria.Orgmode.SFTP.User); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Haustoria.Orgmode.SFTP.PrivateKeyPath != "" || cst.HasValue(tableNode, "private-key-path") {
					if err := cst.SetAny(tableNode, "private-key-path", d.data.Haustoria.Orgmode.SFTP.PrivateKeyPath); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if d.data.Haustoria.Orgmode.SFTP.KnownHostsFile != "" || cst.HasValue(tableNode, "known-hosts-file") {
					if err := cst.SetAny(tableNode, "known-hosts-file", d.data.Haustoria.Orgmode.SFTP.KnownHostsFile); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
			}
		}
		if len(d.data.Haustoria.Folders) > 0 {
			for mapKey, mapVal := range d.data.Haustoria.Folders {
				subTable := cst.EnsureChildSubTable(d.cstDoc.Root(), tableNode, "folders", mapKey)
				if mapVal.Path != "" || cst.HasValue(subTable, "path") {
					if err := cst.SetAny(subTable, "path", mapVal.Path); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				if mapVal.Type != "" || cst.HasValue(subTable, "type") {
					if err := cst.SetAny(subTable, "type", mapVal.Type); err != nil {
						return nil, fmt.Errorf("%w", err)
					}
				}
				{
					if len(mapVal.Tags) > 0 || cst.HasValue(subTable, "tags") {
						if err := cst.SetAny(subTable, "tags", mapVal.Tags); err != nil {
							return nil, fmt.Errorf("%w", err)
						}
					}
				}
			}
		}
	}
	{
		if len(d.data.Ignore) > 0 || cst.HasValue(d.cstDoc.Root(), "ignore") {
			if err := cst.SetAny(d.cstDoc.Root(), "ignore", d.data.Ignore); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *V3Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *V3Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *V3Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *V3Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *V3Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeV3Into(data *V3, sub *cst.Value) error {
	if _vDefaults, _ok := sub.Get("defaults"); _ok && _vDefaults.Kind == cst.VTable {
		_vDefaults.MarkSeen()
		if err := repo_configs.DecodeDefaultsV1OmitEmptyInto(&data.Defaults, _vDefaults); err != nil {
			return fmt.Errorf("defaults: %w", err)
		}
	}
	if _vQuery, _ok := sub.Get("query"); _ok && _vQuery.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vQuery.Leaf); _xok {
			data.Query = _x
			_vQuery.MarkConsumed()
		}
	}
	if _vDryRun, _ok := sub.Get("dry-run"); _ok && _vDryRun.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vDryRun.Leaf); _xok {
			data.DryRun = _x
			_vDryRun.MarkConsumed()
		}
	}
	if _vParentPath, _ok := sub.Get("parent-path"); _ok && _vParentPath.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vParentPath.Leaf); _xok {
			data.ParentPath = _x
			_vParentPath.MarkConsumed()
		}
	}
	if _vSyncTai, _ok := sub.Get("sync-tai"); _ok && _vSyncTai.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vSyncTai.Leaf); _xok {
			data.SyncTai = _x
			_vSyncTai.MarkConsumed()
		}
	}
	if _vSyncDigest, _ok := sub.Get("sync-digest"); _ok && _vSyncDigest.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vSyncDigest.Leaf); _xok {
			data.SyncDigest = _x
			_vSyncDigest.MarkConsumed()
		}
	}
	if _vHaustoria, _ok := sub.Get("haustoria"); _ok && _vHaustoria.Kind == cst.VTable {
		_vHaustoria.MarkSeen()
		if _vHaustoriaType, _ok := _vHaustoria.Get("type"); _ok && _vHaustoriaType.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vHaustoriaType.Leaf); _xok {
				data.Haustoria.Type = _x
				_vHaustoriaType.MarkConsumed()
			}
		}
		if _vHaustoriaCaldav, _ok := _vHaustoria.Get("caldav"); _ok && _vHaustoriaCaldav.Kind == cst.VTable {
			_vHaustoriaCaldav.MarkSeen()
			calDAVVal0 := &CalDAVConfig{}
			if _vHaustoriaCaldavUrl, _ok := _vHaustoriaCaldav.Get("url"); _ok && _vHaustoriaCaldavUrl.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vHaustoriaCaldavUrl.Leaf); _xok {
					calDAVVal0.URL = _x
					_vHaustoriaCaldavUrl.MarkConsumed()
				}
			}
			if _vHaustoriaCaldavUsername, _ok := _vHaustoriaCaldav.Get("username"); _ok && _vHaustoriaCaldavUsername.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vHaustoriaCaldavUsername.Leaf); _xok {
					calDAVVal0.Username = _x
					_vHaustoriaCaldavUsername.MarkConsumed()
				}
			}
			data.Haustoria.CalDAV = calDAVVal0
		} else {
			calDAVVal0 := &CalDAVConfig{}
			_foundHaustoriaCaldav := false
			if _vUrl, _ok := _vHaustoria.Get("url"); _ok && _vUrl.Kind == cst.VLeaf {
				_foundHaustoriaCaldav = true
				if _x, _xok := cst.ExtractString(_vUrl.Leaf); _xok {
					calDAVVal0.URL = _x
					_vUrl.MarkConsumed()
				}
			}
			if _vUsername, _ok := _vHaustoria.Get("username"); _ok && _vUsername.Kind == cst.VLeaf {
				_foundHaustoriaCaldav = true
				if _x, _xok := cst.ExtractString(_vUsername.Leaf); _xok {
					calDAVVal0.Username = _x
					_vUsername.MarkConsumed()
				}
			}
			if _foundHaustoriaCaldav {
				data.Haustoria.CalDAV = calDAVVal0
			}
		}
		if _vHaustoriaCalendars, _ok := _vHaustoria.Get("calendars"); _ok && _vHaustoriaCalendars.Kind == cst.VTable {
			_vHaustoriaCalendars.MarkSeen()
			data.Haustoria.Calendars = make(map[string]CalendarConfig)
			for _mk1i := range _vHaustoriaCalendars.Fields {
				_mk1e := &_vHaustoriaCalendars.Fields[_mk1i]
				if _mk1e.Val.Kind == cst.VTable {
					_mk1e.Val.MarkSeen()
					var entry2 CalendarConfig
					if _vHaustoriaCalendarsUrl, _ok := _mk1e.Val.Get("url"); _ok && _vHaustoriaCalendarsUrl.Kind == cst.VLeaf {
						if _x, _xok := cst.ExtractString(_vHaustoriaCalendarsUrl.Leaf); _xok {
							entry2.URL = _x
							_vHaustoriaCalendarsUrl.MarkConsumed()
						}
					}
					if _vHaustoriaCalendarsType, _ok := _mk1e.Val.Get("type"); _ok && _vHaustoriaCalendarsType.Kind == cst.VLeaf {
						if _x, _xok := cst.ExtractString(_vHaustoriaCalendarsType.Leaf); _xok {
							entry2.Type = _x
							_vHaustoriaCalendarsType.MarkConsumed()
						}
					}
					if _vHaustoriaCalendarsTags, _ok := _mk1e.Val.Get("tags"); _ok && _vHaustoriaCalendarsTags.Kind == cst.VLeaf {
						if _x, _xok := cst.ExtractStringSlice(_vHaustoriaCalendarsTags.Leaf); _xok {
							entry2.Tags = _x
							if entry2.Tags == nil {
								entry2.Tags = []string{}
							}
							_vHaustoriaCalendarsTags.MarkConsumed()
						}
					}
					data.Haustoria.Calendars[_mk1e.Key] = entry2
				}
			}
		}
		if _vHaustoriaOrgmode, _ok := _vHaustoria.Get("orgmode"); _ok && _vHaustoriaOrgmode.Kind == cst.VTable {
			_vHaustoriaOrgmode.MarkSeen()
			orgmodeVal3 := &OrgmodeConfig{}
			if _vHaustoriaOrgmodeTransport, _ok := _vHaustoriaOrgmode.Get("transport"); _ok && _vHaustoriaOrgmodeTransport.Kind == cst.VLeaf {
				if _x, _xok := cst.ExtractString(_vHaustoriaOrgmodeTransport.Leaf); _xok {
					orgmodeVal3.Transport = _x
					_vHaustoriaOrgmodeTransport.MarkConsumed()
				}
			}
			if _vHaustoriaOrgmodeWebdav, _ok := _vHaustoriaOrgmode.Get("webdav"); _ok && _vHaustoriaOrgmodeWebdav.Kind == cst.VTable {
				_vHaustoriaOrgmodeWebdav.MarkSeen()
				webDAVVal4 := &OrgmodeWebDAV{}
				if _vHaustoriaOrgmodeWebdavUrl, _ok := _vHaustoriaOrgmodeWebdav.Get("url"); _ok && _vHaustoriaOrgmodeWebdavUrl.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vHaustoriaOrgmodeWebdavUrl.Leaf); _xok {
						webDAVVal4.URL = _x
						_vHaustoriaOrgmodeWebdavUrl.MarkConsumed()
					}
				}
				if _vHaustoriaOrgmodeWebdavUsername, _ok := _vHaustoriaOrgmodeWebdav.Get("username"); _ok && _vHaustoriaOrgmodeWebdavUsername.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vHaustoriaOrgmodeWebdavUsername.Leaf); _xok {
						webDAVVal4.Username = _x
						_vHaustoriaOrgmodeWebdavUsername.MarkConsumed()
					}
				}
				orgmodeVal3.WebDAV = webDAVVal4
			} else {
				webDAVVal4 := &OrgmodeWebDAV{}
				_foundHaustoriaOrgmodeWebdav := false
				if _vUrl, _ok := _vHaustoriaOrgmode.Get("url"); _ok && _vUrl.Kind == cst.VLeaf {
					_foundHaustoriaOrgmodeWebdav = true
					if _x, _xok := cst.ExtractString(_vUrl.Leaf); _xok {
						webDAVVal4.URL = _x
						_vUrl.MarkConsumed()
					}
				}
				if _vUsername, _ok := _vHaustoriaOrgmode.Get("username"); _ok && _vUsername.Kind == cst.VLeaf {
					_foundHaustoriaOrgmodeWebdav = true
					if _x, _xok := cst.ExtractString(_vUsername.Leaf); _xok {
						webDAVVal4.Username = _x
						_vUsername.MarkConsumed()
					}
				}
				if _foundHaustoriaOrgmodeWebdav {
					orgmodeVal3.WebDAV = webDAVVal4
				}
			}
			if _vHaustoriaOrgmodeSftp, _ok := _vHaustoriaOrgmode.Get("sftp"); _ok && _vHaustoriaOrgmodeSftp.Kind == cst.VTable {
				_vHaustoriaOrgmodeSftp.MarkSeen()
				sFTPVal5 := &OrgmodeSFTP{}
				if _vHaustoriaOrgmodeSftpHost, _ok := _vHaustoriaOrgmodeSftp.Get("host"); _ok && _vHaustoriaOrgmodeSftpHost.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vHaustoriaOrgmodeSftpHost.Leaf); _xok {
						sFTPVal5.Host = _x
						_vHaustoriaOrgmodeSftpHost.MarkConsumed()
					}
				}
				if _vHaustoriaOrgmodeSftpPort, _ok := _vHaustoriaOrgmodeSftp.Get("port"); _ok && _vHaustoriaOrgmodeSftpPort.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractInt(_vHaustoriaOrgmodeSftpPort.Leaf); _xok {
						sFTPVal5.Port = _x
						_vHaustoriaOrgmodeSftpPort.MarkConsumed()
					}
				}
				if _vHaustoriaOrgmodeSftpUser, _ok := _vHaustoriaOrgmodeSftp.Get("user"); _ok && _vHaustoriaOrgmodeSftpUser.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vHaustoriaOrgmodeSftpUser.Leaf); _xok {
						sFTPVal5.User = _x
						_vHaustoriaOrgmodeSftpUser.MarkConsumed()
					}
				}
				if _vHaustoriaOrgmodeSftpPrivateKeyPath, _ok := _vHaustoriaOrgmodeSftp.Get("private-key-path"); _ok && _vHaustoriaOrgmodeSftpPrivateKeyPath.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vHaustoriaOrgmodeSftpPrivateKeyPath.Leaf); _xok {
						sFTPVal5.PrivateKeyPath = _x
						_vHaustoriaOrgmodeSftpPrivateKeyPath.MarkConsumed()
					}
				}
				if _vHaustoriaOrgmodeSftpKnownHostsFile, _ok := _vHaustoriaOrgmodeSftp.Get("known-hosts-file"); _ok && _vHaustoriaOrgmodeSftpKnownHostsFile.Kind == cst.VLeaf {
					if _x, _xok := cst.ExtractString(_vHaustoriaOrgmodeSftpKnownHostsFile.Leaf); _xok {
						sFTPVal5.KnownHostsFile = _x
						_vHaustoriaOrgmodeSftpKnownHostsFile.MarkConsumed()
					}
				}
				orgmodeVal3.SFTP = sFTPVal5
			} else {
				sFTPVal5 := &OrgmodeSFTP{}
				_foundHaustoriaOrgmodeSftp := false
				if _vHost, _ok := _vHaustoriaOrgmode.Get("host"); _ok && _vHost.Kind == cst.VLeaf {
					_foundHaustoriaOrgmodeSftp = true
					if _x, _xok := cst.ExtractString(_vHost.Leaf); _xok {
						sFTPVal5.Host = _x
						_vHost.MarkConsumed()
					}
				}
				if _vPort, _ok := _vHaustoriaOrgmode.Get("port"); _ok && _vPort.Kind == cst.VLeaf {
					_foundHaustoriaOrgmodeSftp = true
					if _x, _xok := cst.ExtractInt(_vPort.Leaf); _xok {
						sFTPVal5.Port = _x
						_vPort.MarkConsumed()
					}
				}
				if _vUser, _ok := _vHaustoriaOrgmode.Get("user"); _ok && _vUser.Kind == cst.VLeaf {
					_foundHaustoriaOrgmodeSftp = true
					if _x, _xok := cst.ExtractString(_vUser.Leaf); _xok {
						sFTPVal5.User = _x
						_vUser.MarkConsumed()
					}
				}
				if _vPrivateKeyPath, _ok := _vHaustoriaOrgmode.Get("private-key-path"); _ok && _vPrivateKeyPath.Kind == cst.VLeaf {
					_foundHaustoriaOrgmodeSftp = true
					if _x, _xok := cst.ExtractString(_vPrivateKeyPath.Leaf); _xok {
						sFTPVal5.PrivateKeyPath = _x
						_vPrivateKeyPath.MarkConsumed()
					}
				}
				if _vKnownHostsFile, _ok := _vHaustoriaOrgmode.Get("known-hosts-file"); _ok && _vKnownHostsFile.Kind == cst.VLeaf {
					_foundHaustoriaOrgmodeSftp = true
					if _x, _xok := cst.ExtractString(_vKnownHostsFile.Leaf); _xok {
						sFTPVal5.KnownHostsFile = _x
						_vKnownHostsFile.MarkConsumed()
					}
				}
				if _foundHaustoriaOrgmodeSftp {
					orgmodeVal3.SFTP = sFTPVal5
				}
			}
			data.Haustoria.Orgmode = orgmodeVal3
		} else {
			orgmodeVal3 := &OrgmodeConfig{}
			_foundHaustoriaOrgmode := false
			if _vTransport, _ok := _vHaustoria.Get("transport"); _ok && _vTransport.Kind == cst.VLeaf {
				_foundHaustoriaOrgmode = true
				if _x, _xok := cst.ExtractString(_vTransport.Leaf); _xok {
					orgmodeVal3.Transport = _x
					_vTransport.MarkConsumed()
				}
			}
			if _foundHaustoriaOrgmode {
				data.Haustoria.Orgmode = orgmodeVal3
			}
		}
		if _vHaustoriaFolders, _ok := _vHaustoria.Get("folders"); _ok && _vHaustoriaFolders.Kind == cst.VTable {
			_vHaustoriaFolders.MarkSeen()
			data.Haustoria.Folders = make(map[string]FolderConfig)
			for _mk6i := range _vHaustoriaFolders.Fields {
				_mk6e := &_vHaustoriaFolders.Fields[_mk6i]
				if _mk6e.Val.Kind == cst.VTable {
					_mk6e.Val.MarkSeen()
					var entry7 FolderConfig
					if _vHaustoriaFoldersPath, _ok := _mk6e.Val.Get("path"); _ok && _vHaustoriaFoldersPath.Kind == cst.VLeaf {
						if _x, _xok := cst.ExtractString(_vHaustoriaFoldersPath.Leaf); _xok {
							entry7.Path = _x
							_vHaustoriaFoldersPath.MarkConsumed()
						}
					}
					if _vHaustoriaFoldersType, _ok := _mk6e.Val.Get("type"); _ok && _vHaustoriaFoldersType.Kind == cst.VLeaf {
						if _x, _xok := cst.ExtractString(_vHaustoriaFoldersType.Leaf); _xok {
							entry7.Type = _x
							_vHaustoriaFoldersType.MarkConsumed()
						}
					}
					if _vHaustoriaFoldersTags, _ok := _mk6e.Val.Get("tags"); _ok && _vHaustoriaFoldersTags.Kind == cst.VLeaf {
						if _x, _xok := cst.ExtractStringSlice(_vHaustoriaFoldersTags.Leaf); _xok {
							entry7.Tags = _x
							if entry7.Tags == nil {
								entry7.Tags = []string{}
							}
							_vHaustoriaFoldersTags.MarkConsumed()
						}
					}
					data.Haustoria.Folders[_mk6e.Key] = entry7
				}
			}
		}
	} else {
		if _vType, _ok := sub.Get("type"); _ok && _vType.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractString(_vType.Leaf); _xok {
				data.Haustoria.Type = _x
				_vType.MarkConsumed()
			}
		}
	}
	if _vIgnore, _ok := sub.Get("ignore"); _ok && _vIgnore.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vIgnore.Leaf); _xok {
			data.Ignore = _x
			if data.Ignore == nil {
				data.Ignore = []string{}
			}
			_vIgnore.MarkConsumed()
		}
	}
	return nil
}

func EncodeV3From(data *V3, doc *document.Document, container *cst.Node) error {
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "defaults")
		if err := repo_configs.EncodeDefaultsV1OmitEmptyFrom(&data.Defaults, doc, tableNode); err != nil {
			return fmt.Errorf("defaults: %w", err)
		}
	}
	if data.Query != "" {
		if err := cst.SetAny(container, "query", data.Query); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "query")
	}
	if data.DryRun != false || cst.HasValue(container, "dry-run") {
		if err := cst.SetAny(container, "dry-run", data.DryRun); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.ParentPath != "" {
		if err := cst.SetAny(container, "parent-path", data.ParentPath); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "parent-path")
	}
	if data.SyncTai != "" {
		if err := cst.SetAny(container, "sync-tai", data.SyncTai); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "sync-tai")
	}
	if data.SyncDigest != "" {
		if err := cst.SetAny(container, "sync-digest", data.SyncDigest); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "sync-digest")
	}
	{
		tableNode := cst.EnsureChildTable(doc.Root(), container, "haustoria")
		if data.Haustoria.Type != "" || cst.HasValue(tableNode, "type") {
			if err := cst.SetAny(tableNode, "type", data.Haustoria.Type); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Haustoria.CalDAV != nil {
			tableNode := cst.EnsureChildTable(doc.Root(), tableNode, "caldav")
			if data.Haustoria.CalDAV.URL != "" || cst.HasValue(tableNode, "url") {
				if err := cst.SetAny(tableNode, "url", data.Haustoria.CalDAV.URL); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Haustoria.CalDAV.Username != "" || cst.HasValue(tableNode, "username") {
				if err := cst.SetAny(tableNode, "username", data.Haustoria.CalDAV.Username); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
		if len(data.Haustoria.Calendars) > 0 {
			for mapKey, mapVal := range data.Haustoria.Calendars {
				subTable := cst.EnsureChildSubTable(doc.Root(), tableNode, "calendars", mapKey)
				if mapVal.URL != "" || cst.HasValue(subTable, "url") {
					if err := cst.SetAny(subTable, "url", mapVal.URL); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if mapVal.Type != "" || cst.HasValue(subTable, "type") {
					if err := cst.SetAny(subTable, "type", mapVal.Type); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				{
					if len(mapVal.Tags) > 0 || cst.HasValue(subTable, "tags") {
						if err := cst.SetAny(subTable, "tags", mapVal.Tags); err != nil {
							return fmt.Errorf("%w", err)
						}
					}
				}
			}
		}
		if data.Haustoria.Orgmode != nil {
			tableNode := cst.EnsureChildTable(doc.Root(), tableNode, "orgmode")
			if data.Haustoria.Orgmode.Transport != "" || cst.HasValue(tableNode, "transport") {
				if err := cst.SetAny(tableNode, "transport", data.Haustoria.Orgmode.Transport); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
			if data.Haustoria.Orgmode.WebDAV != nil {
				tableNode := cst.EnsureChildTable(doc.Root(), tableNode, "webdav")
				if data.Haustoria.Orgmode.WebDAV.URL != "" || cst.HasValue(tableNode, "url") {
					if err := cst.SetAny(tableNode, "url", data.Haustoria.Orgmode.WebDAV.URL); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Haustoria.Orgmode.WebDAV.Username != "" || cst.HasValue(tableNode, "username") {
					if err := cst.SetAny(tableNode, "username", data.Haustoria.Orgmode.WebDAV.Username); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
			if data.Haustoria.Orgmode.SFTP != nil {
				tableNode := cst.EnsureChildTable(doc.Root(), tableNode, "sftp")
				if data.Haustoria.Orgmode.SFTP.Host != "" || cst.HasValue(tableNode, "host") {
					if err := cst.SetAny(tableNode, "host", data.Haustoria.Orgmode.SFTP.Host); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Haustoria.Orgmode.SFTP.Port != 0 || cst.HasValue(tableNode, "port") {
					if err := cst.SetAny(tableNode, "port", data.Haustoria.Orgmode.SFTP.Port); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Haustoria.Orgmode.SFTP.User != "" || cst.HasValue(tableNode, "user") {
					if err := cst.SetAny(tableNode, "user", data.Haustoria.Orgmode.SFTP.User); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Haustoria.Orgmode.SFTP.PrivateKeyPath != "" || cst.HasValue(tableNode, "private-key-path") {
					if err := cst.SetAny(tableNode, "private-key-path", data.Haustoria.Orgmode.SFTP.PrivateKeyPath); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if data.Haustoria.Orgmode.SFTP.KnownHostsFile != "" || cst.HasValue(tableNode, "known-hosts-file") {
					if err := cst.SetAny(tableNode, "known-hosts-file", data.Haustoria.Orgmode.SFTP.KnownHostsFile); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
			}
		}
		if len(data.Haustoria.Folders) > 0 {
			for mapKey, mapVal := range data.Haustoria.Folders {
				subTable := cst.EnsureChildSubTable(doc.Root(), tableNode, "folders", mapKey)
				if mapVal.Path != "" || cst.HasValue(subTable, "path") {
					if err := cst.SetAny(subTable, "path", mapVal.Path); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				if mapVal.Type != "" || cst.HasValue(subTable, "type") {
					if err := cst.SetAny(subTable, "type", mapVal.Type); err != nil {
						return fmt.Errorf("%w", err)
					}
				}
				{
					if len(mapVal.Tags) > 0 || cst.HasValue(subTable, "tags") {
						if err := cst.SetAny(subTable, "tags", mapVal.Tags); err != nil {
							return fmt.Errorf("%w", err)
						}
					}
				}
			}
		}
	}
	{
		if len(data.Ignore) > 0 || cst.HasValue(container, "ignore") {
			if err := cst.SetAny(container, "ignore", data.Ignore); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	return nil
}
