// Code generated by tommy; DO NOT EDIT.

package type_blobs

import (
	"fmt"

	"code.linenisgreat.com/dodder/go/lib/delta/script_config"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type TomlV0Document struct {
	data     TomlV0
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlV0(input []byte) (*TomlV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlV0Document{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "inline-akte"); err == nil {
		d.data.InlineBlob = v
		d.consumed["inline-akte"] = true
	}
	if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "archived"); err == nil {
		d.data.Archived = v
		d.consumed["archived"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "file-extension"); err == nil {
		d.data.FileExtension = v
		d.consumed["file-extension"] = true
	}
	if tableNode := d.cstDoc.FindTable("exec-command"); tableNode != nil {
		d.consumed["exec-command"] = true
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "description"); err == nil {
			d.data.ExecCommand.Description = v
			d.consumed["exec-command.description"] = true
		}
		if v, err := document.GetFromContainer[[]string](d.cstDoc, tableNode, "shell"); err == nil {
			d.data.ExecCommand.Shell = v
			d.consumed["exec-command.shell"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "script"); err == nil {
			d.data.ExecCommand.Script = v
			d.consumed["exec-command.script"] = true
		}
		if tableNode := d.cstDoc.FindTable("env"); tableNode != nil {
			d.data.ExecCommand.Env = document.GetStringMapFromTable(tableNode)
			d.consumed["exec-command.env"] = true
			document.MarkAllConsumed(tableNode, "exec-command.env", d.consumed)
		}
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "vim-syntax-type"); err == nil {
		d.data.VimSyntaxType = v
		d.consumed["vim-syntax-type"] = true
	}
	{
		subTables := d.cstDoc.FindSubTables("formatter-uti-groups")
		if len(subTables) > 0 {
			d.consumed["formatter-uti-groups"] = true
			d.data.FormatterUTIGroups = make(map[string]UTIGroup)
			for _, subTable := range subTables {
				mapKey := document.SubTableKey(subTable, "formatter-uti-groups")
				d.consumed["formatter-uti-groups"+"."+mapKey] = true
				inner := document.GetStringMapFromTable(subTable)
				document.MarkAllConsumed(subTable, "formatter-uti-groups"+"."+mapKey, d.consumed)
				d.data.FormatterUTIGroups[mapKey] = UTIGroup(inner)
			}
		}
	}
	{
		subTables := d.cstDoc.FindSubTables("formatters")
		if len(subTables) > 0 {
			d.consumed["formatters"] = true
			d.data.Formatters = make(map[string]script_config.WithOutputFormat)
			for _, subTable := range subTables {
				mapKey := document.SubTableKey(subTable, "formatters")
				d.consumed["formatters"+"."+mapKey] = true
				var entry script_config.WithOutputFormat
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "description"); err == nil {
					entry.Description = v
					d.consumed["formatters.\" + mapKey + \".description"] = true
				}
				if v, err := document.GetFromContainer[[]string](d.cstDoc, subTable, "shell"); err == nil {
					entry.Shell = v
					d.consumed["formatters.\" + mapKey + \".shell"] = true
				}
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "script"); err == nil {
					entry.Script = v
					d.consumed["formatters.\" + mapKey + \".script"] = true
				}
				if tableNode := d.cstDoc.FindTable("env"); tableNode != nil {
					entry.Env = document.GetStringMapFromTable(tableNode)
					d.consumed["formatters.\" + mapKey + \".env"] = true
					document.MarkAllConsumed(tableNode, "formatters.\" + mapKey + \".env", d.consumed)
				}
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "uti"); err == nil {
					entry.UTI = v
					d.consumed["formatters.\" + mapKey + \".uti"] = true
				}
				if v, err := document.GetFromContainer[[]string](d.cstDoc, subTable, "utis"); err == nil {
					entry.UTIS = v
					d.consumed["formatters.\" + mapKey + \".utis"] = true
				}
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "file-extension"); err == nil {
					entry.FileExtension = v
					d.consumed["formatters.\" + mapKey + \".file-extension"] = true
				}
				d.data.Formatters[mapKey] = entry
			}
		}
	}
	{
		subTables := d.cstDoc.FindSubTables("actions")
		if len(subTables) > 0 {
			d.consumed["actions"] = true
			d.data.Actions = make(map[string]script_config.ScriptConfig)
			for _, subTable := range subTables {
				mapKey := document.SubTableKey(subTable, "actions")
				d.consumed["actions"+"."+mapKey] = true
				var entry script_config.ScriptConfig
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "description"); err == nil {
					entry.Description = v
					d.consumed["actions.\" + mapKey + \".description"] = true
				}
				if v, err := document.GetFromContainer[[]string](d.cstDoc, subTable, "shell"); err == nil {
					entry.Shell = v
					d.consumed["actions.\" + mapKey + \".shell"] = true
				}
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "script"); err == nil {
					entry.Script = v
					d.consumed["actions.\" + mapKey + \".script"] = true
				}
				if tableNode := d.cstDoc.FindTable("env"); tableNode != nil {
					entry.Env = document.GetStringMapFromTable(tableNode)
					d.consumed["actions.\" + mapKey + \".env"] = true
					document.MarkAllConsumed(tableNode, "actions.\" + mapKey + \".env", d.consumed)
				}
				d.data.Actions[mapKey] = entry
			}
		}
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "hooks"); err == nil {
		d.data.Hooks = v
		d.consumed["hooks"] = true
	}

	return d, nil
}

func (d *TomlV0Document) Data() *TomlV0 { return &d.data }

func (d *TomlV0Document) Encode() ([]byte, error) {
	if d.data.InlineBlob != false {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "inline-akte", d.data.InlineBlob); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "inline-akte")
	}
	if d.data.Archived != false {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "archived", d.data.Archived); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "archived")
	}
	if d.data.FileExtension != "" {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "file-extension", d.data.FileExtension); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "file-extension")
	}
	if tableNode := d.cstDoc.FindTable("exec-command"); tableNode != nil {
		if d.data.ExecCommand.Description != "" || d.cstDoc.HasInContainer(tableNode, "description") {
			if err := d.cstDoc.SetInContainer(tableNode, "description", d.data.ExecCommand.Description); err != nil {
				return nil, err
			}
		}
		if len(d.data.ExecCommand.Shell) > 0 || d.cstDoc.HasInContainer(tableNode, "shell") {
			if err := d.cstDoc.SetInContainer(tableNode, "shell", d.data.ExecCommand.Shell); err != nil {
				return nil, err
			}
		}
		if d.data.ExecCommand.Script != "" {
			if err := d.cstDoc.SetMultilineInContainer(tableNode, "script", d.data.ExecCommand.Script); err != nil {
				return nil, err
			}
		} else {
			_ = d.cstDoc.DeleteFromContainer(tableNode, "script")
		}
		if len(d.data.ExecCommand.Env) > 0 {
			tableNode := d.cstDoc.EnsureTable("env")
			document.DeleteAllInContainer(tableNode)
			for k, v := range d.data.ExecCommand.Env {
				if err := d.cstDoc.SetInContainer(tableNode, k, v); err != nil {
					return nil, err
				}
			}
		}
	}
	if d.data.VimSyntaxType != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "vim-syntax-type") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "vim-syntax-type", d.data.VimSyntaxType); err != nil {
			return nil, err
		}
	}
	if len(d.data.FormatterUTIGroups) > 0 {
		for mapKey, mapVal := range d.data.FormatterUTIGroups {
			subTable := d.cstDoc.EnsureSubTable("formatter-uti-groups", mapKey)
			document.DeleteAllInContainer(subTable)
			for k, v := range map[string]string(mapVal) {
				if err := d.cstDoc.SetInContainer(subTable, k, v); err != nil {
					return nil, err
				}
			}
		}
	}
	if len(d.data.Formatters) > 0 {
		for mapKey, mapVal := range d.data.Formatters {
			subTable := d.cstDoc.EnsureSubTable("formatters", mapKey)
			if mapVal.Description != "" || d.cstDoc.HasInContainer(subTable, "description") {
				if err := d.cstDoc.SetInContainer(subTable, "description", mapVal.Description); err != nil {
					return nil, err
				}
			}
			if len(mapVal.Shell) > 0 || d.cstDoc.HasInContainer(subTable, "shell") {
				if err := d.cstDoc.SetInContainer(subTable, "shell", mapVal.Shell); err != nil {
					return nil, err
				}
			}
			if mapVal.Script != "" {
				if err := d.cstDoc.SetMultilineInContainer(subTable, "script", mapVal.Script); err != nil {
					return nil, err
				}
			} else {
				_ = d.cstDoc.DeleteFromContainer(subTable, "script")
			}
			if len(mapVal.Env) > 0 {
				tableNode := d.cstDoc.EnsureTable("env")
				document.DeleteAllInContainer(tableNode)
				for k, v := range mapVal.Env {
					if err := d.cstDoc.SetInContainer(tableNode, k, v); err != nil {
						return nil, err
					}
				}
			}
			if mapVal.UTI != "" || d.cstDoc.HasInContainer(subTable, "uti") {
				if err := d.cstDoc.SetInContainer(subTable, "uti", mapVal.UTI); err != nil {
					return nil, err
				}
			}
			if err := d.cstDoc.SetInContainer(subTable, "utis", mapVal.UTIS); err != nil {
				return nil, err
			}
			if mapVal.FileExtension != "" || d.cstDoc.HasInContainer(subTable, "file-extension") {
				if err := d.cstDoc.SetInContainer(subTable, "file-extension", mapVal.FileExtension); err != nil {
					return nil, err
				}
			}
		}
	}
	if len(d.data.Actions) > 0 {
		for mapKey, mapVal := range d.data.Actions {
			subTable := d.cstDoc.EnsureSubTable("actions", mapKey)
			if mapVal.Description != "" || d.cstDoc.HasInContainer(subTable, "description") {
				if err := d.cstDoc.SetInContainer(subTable, "description", mapVal.Description); err != nil {
					return nil, err
				}
			}
			if len(mapVal.Shell) > 0 || d.cstDoc.HasInContainer(subTable, "shell") {
				if err := d.cstDoc.SetInContainer(subTable, "shell", mapVal.Shell); err != nil {
					return nil, err
				}
			}
			if mapVal.Script != "" {
				if err := d.cstDoc.SetMultilineInContainer(subTable, "script", mapVal.Script); err != nil {
					return nil, err
				}
			} else {
				_ = d.cstDoc.DeleteFromContainer(subTable, "script")
			}
			if len(mapVal.Env) > 0 {
				tableNode := d.cstDoc.EnsureTable("env")
				document.DeleteAllInContainer(tableNode)
				for k, v := range mapVal.Env {
					if err := d.cstDoc.SetInContainer(tableNode, k, v); err != nil {
						return nil, err
					}
				}
			}
		}
	}
	if d.data.Hooks != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "hooks") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "hooks", d.data.Hooks); err != nil {
			return nil, err
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *TomlV0Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
