// Code generated by tommy; DO NOT EDIT.

package type_blobs

import (
	"fmt"

	"code.linenisgreat.com/dodder/go/lib/delta/script_config"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type TomlV1Document struct {
	data     TomlV1
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlV1(input []byte) (*TomlV1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlV1Document{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "binary"); err == nil {
		d.data.Binary = v
		d.consumed["binary"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "file-extension"); err == nil {
		d.data.FileExtension = v
		d.consumed["file-extension"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "mime-type"); err == nil {
		d.data.MimeType = v
		d.consumed["mime-type"] = true
	}
	if tableNode := d.cstDoc.FindTableInContainer(d.cstDoc.Root(), "exec-command"); tableNode != nil {
		d.consumed["exec-command"] = true
		execCommandVal := &script_config.ScriptConfig{}
		if err := script_config.DecodeScriptConfigInto(execCommandVal, d.cstDoc, tableNode, d.consumed, "exec-command."); err != nil {
			return nil, fmt.Errorf("exec-command: %w", err)
		}
		d.data.ExecCommand = execCommandVal
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "vim-syntax-type"); err == nil {
		d.data.VimSyntaxType = v
		d.consumed["vim-syntax-type"] = true
	}
	{
		subTables := d.cstDoc.FindSubTables("uti-groups")
		if len(subTables) > 0 {
			d.consumed["uti-groups"] = true
			d.data.UTIGroups = make(map[string]UTIGroup)
			for _, subTable := range subTables {
				mapKey := document.SubTableKey(subTable, "uti-groups")
				d.consumed["uti-groups"+"."+mapKey] = true
				inner := document.GetStringMapFromTable(subTable)
				document.MarkAllConsumed(subTable, "uti-groups"+"."+mapKey, d.consumed)
				d.data.UTIGroups[mapKey] = UTIGroup(inner)
			}
		}
	}
	{
		subTables := d.cstDoc.FindSubTables("formatters")
		if len(subTables) > 0 {
			d.consumed["formatters"] = true
			d.data.Formatters = make(map[string]script_config.WithOutputFormat)
			for _, subTable := range subTables {
				mapKey := document.SubTableKey(subTable, "formatters")
				d.consumed["formatters"+"."+mapKey] = true
				var entry script_config.WithOutputFormat
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "description"); err == nil {
					entry.Description = v
					d.consumed["formatters.\" + mapKey + \".description"] = true
				}
				if v, err := document.GetFromContainer[[]string](d.cstDoc, subTable, "shell"); err == nil {
					entry.Shell = v
					d.consumed["formatters.\" + mapKey + \".shell"] = true
				}
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "script"); err == nil {
					entry.Script = v
					d.consumed["formatters.\" + mapKey + \".script"] = true
				}
				if tableNode := d.cstDoc.FindTable("env"); tableNode != nil {
					entry.Env = document.GetStringMapFromTable(tableNode)
					d.consumed["formatters.\" + mapKey + \".env"] = true
					document.MarkAllConsumed(tableNode, "formatters.\" + mapKey + \".env", d.consumed)
				}
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "uti"); err == nil {
					entry.UTI = v
					d.consumed["formatters.\" + mapKey + \".uti"] = true
				}
				if v, err := document.GetFromContainer[[]string](d.cstDoc, subTable, "utis"); err == nil {
					entry.UTIS = v
					d.consumed["formatters.\" + mapKey + \".utis"] = true
				}
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "file-extension"); err == nil {
					entry.FileExtension = v
					d.consumed["formatters.\" + mapKey + \".file-extension"] = true
				}
				d.data.Formatters[mapKey] = entry
			}
		}
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "hooks"); err == nil {
		d.data.Hooks = v
		d.consumed["hooks"] = true
	}
	if tableNode := d.cstDoc.FindTableInContainer(d.cstDoc.Root(), "references"); tableNode != nil {
		d.consumed["references"] = true
		referencesVal := &ReferencesConfig{}
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "description"); err == nil {
			referencesVal.Description = v
			d.consumed["references.description"] = true
		}
		if v, err := document.GetFromContainer[[]string](d.cstDoc, tableNode, "shell"); err == nil {
			referencesVal.Shell = v
			d.consumed["references.shell"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "script"); err == nil {
			referencesVal.Script = v
			d.consumed["references.script"] = true
		}
		if tableNode := d.cstDoc.FindTable("env"); tableNode != nil {
			referencesVal.Env = document.GetStringMapFromTable(tableNode)
			d.consumed["references.env"] = true
			document.MarkAllConsumed(tableNode, "references.env", d.consumed)
		}
		if v, err := document.GetFromContainer[bool](d.cstDoc, tableNode, "optional"); err == nil {
			referencesVal.Optional = v
			d.consumed["references.optional"] = true
		}
		d.data.References = referencesVal
	} else {
		referencesVal := &ReferencesConfig{}
		found := false
		if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "description"); err == nil {
			referencesVal.Description = v
			found = true
			d.consumed["description"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "script"); err == nil {
			referencesVal.Script = v
			found = true
			d.consumed["script"] = true
		}
		if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "optional"); err == nil {
			referencesVal.Optional = v
			found = true
			d.consumed["optional"] = true
		}
		if found {
			d.data.References = referencesVal
		}
	}

	return d, nil
}

func (d *TomlV1Document) Data() *TomlV1 { return &d.data }

func (d *TomlV1Document) Encode() ([]byte, error) {
	if d.data.Binary != false {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "binary", d.data.Binary); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "binary")
	}
	if d.data.FileExtension != "" {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "file-extension", d.data.FileExtension); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "file-extension")
	}
	if d.data.MimeType != "" {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "mime-type", d.data.MimeType); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "mime-type")
	}
	if d.data.ExecCommand != nil {
		tableNode := d.cstDoc.EnsureTableInContainer(d.cstDoc.Root(), "exec-command")
		if err := script_config.EncodeScriptConfigFrom(d.data.ExecCommand, d.cstDoc, tableNode); err != nil {
			return nil, fmt.Errorf("exec-command: %w", err)
		}
	}
	if d.data.VimSyntaxType != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "vim-syntax-type") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "vim-syntax-type", d.data.VimSyntaxType); err != nil {
			return nil, err
		}
	}
	if len(d.data.UTIGroups) > 0 {
		for mapKey, mapVal := range d.data.UTIGroups {
			subTable := d.cstDoc.EnsureSubTable("uti-groups", mapKey)
			document.DeleteAllInContainer(subTable)
			for k, v := range map[string]string(mapVal) {
				if err := d.cstDoc.SetInContainer(subTable, k, v); err != nil {
					return nil, err
				}
			}
		}
	}
	if len(d.data.Formatters) > 0 {
		for mapKey, mapVal := range d.data.Formatters {
			subTable := d.cstDoc.EnsureSubTable("formatters", mapKey)
			if mapVal.Description != "" || d.cstDoc.HasInContainer(subTable, "description") {
				if err := d.cstDoc.SetInContainer(subTable, "description", mapVal.Description); err != nil {
					return nil, err
				}
			}
			if len(mapVal.Shell) > 0 || d.cstDoc.HasInContainer(subTable, "shell") {
				if err := d.cstDoc.SetInContainer(subTable, "shell", mapVal.Shell); err != nil {
					return nil, err
				}
			}
			if mapVal.Script != "" {
				if err := d.cstDoc.SetMultilineInContainer(subTable, "script", mapVal.Script); err != nil {
					return nil, err
				}
			} else {
				_ = d.cstDoc.DeleteFromContainer(subTable, "script")
			}
			if len(mapVal.Env) > 0 {
				tableNode := d.cstDoc.EnsureTable("env")
				document.DeleteAllInContainer(tableNode)
				for k, v := range mapVal.Env {
					if err := d.cstDoc.SetInContainer(tableNode, k, v); err != nil {
						return nil, err
					}
				}
			}
			if mapVal.UTI != "" || d.cstDoc.HasInContainer(subTable, "uti") {
				if err := d.cstDoc.SetInContainer(subTable, "uti", mapVal.UTI); err != nil {
					return nil, err
				}
			}
			if err := d.cstDoc.SetInContainer(subTable, "utis", mapVal.UTIS); err != nil {
				return nil, err
			}
			if mapVal.FileExtension != "" || d.cstDoc.HasInContainer(subTable, "file-extension") {
				if err := d.cstDoc.SetInContainer(subTable, "file-extension", mapVal.FileExtension); err != nil {
					return nil, err
				}
			}
		}
	}
	if d.data.Hooks != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "hooks") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "hooks", d.data.Hooks); err != nil {
			return nil, err
		}
	}
	if d.data.References != nil {
		tableNode := d.cstDoc.EnsureTableInContainer(d.cstDoc.Root(), "references")
		if d.data.References.Description != "" || d.cstDoc.HasInContainer(tableNode, "description") {
			if err := d.cstDoc.SetInContainer(tableNode, "description", d.data.References.Description); err != nil {
				return nil, err
			}
		}
		if len(d.data.References.Shell) > 0 || d.cstDoc.HasInContainer(tableNode, "shell") {
			if err := d.cstDoc.SetInContainer(tableNode, "shell", d.data.References.Shell); err != nil {
				return nil, err
			}
		}
		if d.data.References.Script != "" {
			if err := d.cstDoc.SetMultilineInContainer(tableNode, "script", d.data.References.Script); err != nil {
				return nil, err
			}
		} else {
			_ = d.cstDoc.DeleteFromContainer(tableNode, "script")
		}
		if len(d.data.References.Env) > 0 {
			tableNode := d.cstDoc.EnsureTable("env")
			document.DeleteAllInContainer(tableNode)
			for k, v := range d.data.References.Env {
				if err := d.cstDoc.SetInContainer(tableNode, k, v); err != nil {
					return nil, err
				}
			}
		}
		if d.data.References.Optional != false {
			if err := d.cstDoc.SetInContainer(tableNode, "optional", d.data.References.Optional); err != nil {
				return nil, err
			}
		} else {
			_ = d.cstDoc.DeleteFromContainer(tableNode, "optional")
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *TomlV1Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func (d *TomlV1Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlV1Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlV1Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlV1Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlV1Into(data *TomlV1, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	if v, err := document.GetFromContainer[bool](doc, container, "binary"); err == nil {
		data.Binary = v
		consumed[keyPrefix+"binary"] = true
	}
	if v, err := document.GetFromContainer[string](doc, container, "file-extension"); err == nil {
		data.FileExtension = v
		consumed[keyPrefix+"file-extension"] = true
	}
	if v, err := document.GetFromContainer[string](doc, container, "mime-type"); err == nil {
		data.MimeType = v
		consumed[keyPrefix+"mime-type"] = true
	}
	if tableNode := doc.FindTableInContainer(container, "exec-command"); tableNode != nil {
		consumed[keyPrefix+"exec-command"] = true
		execCommandVal := &script_config.ScriptConfig{}
		if err := script_config.DecodeScriptConfigInto(execCommandVal, doc, tableNode, consumed, "exec-command."); err != nil {
			return fmt.Errorf("exec-command: %w", err)
		}
		data.ExecCommand = execCommandVal
	}
	if v, err := document.GetFromContainer[string](doc, container, "vim-syntax-type"); err == nil {
		data.VimSyntaxType = v
		consumed[keyPrefix+"vim-syntax-type"] = true
	}
	{
		subTables := doc.FindSubTables("uti-groups")
		if len(subTables) > 0 {
			consumed[keyPrefix+"uti-groups"] = true
			data.UTIGroups = make(map[string]UTIGroup)
			for _, subTable := range subTables {
				mapKey := document.SubTableKey(subTable, "uti-groups")
				consumed[keyPrefix+"uti-groups"+"."+mapKey] = true
				inner := document.GetStringMapFromTable(subTable)
				document.MarkAllConsumed(subTable, "uti-groups"+"."+mapKey, consumed)
				data.UTIGroups[mapKey] = UTIGroup(inner)
			}
		}
	}
	{
		subTables := doc.FindSubTables("formatters")
		if len(subTables) > 0 {
			consumed[keyPrefix+"formatters"] = true
			data.Formatters = make(map[string]script_config.WithOutputFormat)
			for _, subTable := range subTables {
				mapKey := document.SubTableKey(subTable, "formatters")
				consumed[keyPrefix+"formatters"+"."+mapKey] = true
				var entry script_config.WithOutputFormat
				if v, err := document.GetFromContainer[string](doc, subTable, "description"); err == nil {
					entry.Description = v
					consumed[keyPrefix+"formatters.\" + mapKey + \".description"] = true
				}
				if v, err := document.GetFromContainer[[]string](doc, subTable, "shell"); err == nil {
					entry.Shell = v
					consumed[keyPrefix+"formatters.\" + mapKey + \".shell"] = true
				}
				if v, err := document.GetFromContainer[string](doc, subTable, "script"); err == nil {
					entry.Script = v
					consumed[keyPrefix+"formatters.\" + mapKey + \".script"] = true
				}
				if tableNode := doc.FindTable("env"); tableNode != nil {
					entry.Env = document.GetStringMapFromTable(tableNode)
					consumed[keyPrefix+"formatters.\" + mapKey + \".env"] = true
					document.MarkAllConsumed(tableNode, "formatters.\" + mapKey + \".env", consumed)
				}
				if v, err := document.GetFromContainer[string](doc, subTable, "uti"); err == nil {
					entry.UTI = v
					consumed[keyPrefix+"formatters.\" + mapKey + \".uti"] = true
				}
				if v, err := document.GetFromContainer[[]string](doc, subTable, "utis"); err == nil {
					entry.UTIS = v
					consumed[keyPrefix+"formatters.\" + mapKey + \".utis"] = true
				}
				if v, err := document.GetFromContainer[string](doc, subTable, "file-extension"); err == nil {
					entry.FileExtension = v
					consumed[keyPrefix+"formatters.\" + mapKey + \".file-extension"] = true
				}
				data.Formatters[mapKey] = entry
			}
		}
	}
	if v, err := document.GetFromContainer[string](doc, container, "hooks"); err == nil {
		data.Hooks = v
		consumed[keyPrefix+"hooks"] = true
	}
	if tableNode := doc.FindTableInContainer(container, "references"); tableNode != nil {
		consumed[keyPrefix+"references"] = true
		referencesVal := &ReferencesConfig{}
		if v, err := document.GetFromContainer[string](doc, tableNode, "description"); err == nil {
			referencesVal.Description = v
			consumed[keyPrefix+"references.description"] = true
		}
		if v, err := document.GetFromContainer[[]string](doc, tableNode, "shell"); err == nil {
			referencesVal.Shell = v
			consumed[keyPrefix+"references.shell"] = true
		}
		if v, err := document.GetFromContainer[string](doc, tableNode, "script"); err == nil {
			referencesVal.Script = v
			consumed[keyPrefix+"references.script"] = true
		}
		if tableNode := doc.FindTable("env"); tableNode != nil {
			referencesVal.Env = document.GetStringMapFromTable(tableNode)
			consumed[keyPrefix+"references.env"] = true
			document.MarkAllConsumed(tableNode, "references.env", consumed)
		}
		if v, err := document.GetFromContainer[bool](doc, tableNode, "optional"); err == nil {
			referencesVal.Optional = v
			consumed[keyPrefix+"references.optional"] = true
		}
		data.References = referencesVal
	} else {
		referencesVal := &ReferencesConfig{}
		found := false
		if v, err := document.GetFromContainer[string](doc, container, "description"); err == nil {
			referencesVal.Description = v
			found = true
			consumed[keyPrefix+"description"] = true
		}
		if v, err := document.GetFromContainer[string](doc, container, "script"); err == nil {
			referencesVal.Script = v
			found = true
			consumed[keyPrefix+"script"] = true
		}
		if v, err := document.GetFromContainer[bool](doc, container, "optional"); err == nil {
			referencesVal.Optional = v
			found = true
			consumed[keyPrefix+"optional"] = true
		}
		if found {
			data.References = referencesVal
		}
	}

	return nil
}

func EncodeTomlV1From(data *TomlV1, doc *document.Document, container *cst.Node) error {
	if data.Binary != false {
		if err := doc.SetInContainer(container, "binary", data.Binary); err != nil {
			return err
		}
	} else {
		_ = doc.DeleteFromContainer(container, "binary")
	}
	if data.FileExtension != "" {
		if err := doc.SetInContainer(container, "file-extension", data.FileExtension); err != nil {
			return err
		}
	} else {
		_ = doc.DeleteFromContainer(container, "file-extension")
	}
	if data.MimeType != "" {
		if err := doc.SetInContainer(container, "mime-type", data.MimeType); err != nil {
			return err
		}
	} else {
		_ = doc.DeleteFromContainer(container, "mime-type")
	}
	if data.ExecCommand != nil {
		tableNode := doc.EnsureTableInContainer(container, "exec-command")
		if err := script_config.EncodeScriptConfigFrom(data.ExecCommand, doc, tableNode); err != nil {
			return fmt.Errorf("exec-command: %w", err)
		}
	}
	if data.VimSyntaxType != "" || doc.HasInContainer(container, "vim-syntax-type") {
		if err := doc.SetInContainer(container, "vim-syntax-type", data.VimSyntaxType); err != nil {
			return err
		}
	}
	if len(data.UTIGroups) > 0 {
		for mapKey, mapVal := range data.UTIGroups {
			subTable := doc.EnsureSubTable("uti-groups", mapKey)
			document.DeleteAllInContainer(subTable)
			for k, v := range map[string]string(mapVal) {
				if err := doc.SetInContainer(subTable, k, v); err != nil {
					return err
				}
			}
		}
	}
	if len(data.Formatters) > 0 {
		for mapKey, mapVal := range data.Formatters {
			subTable := doc.EnsureSubTable("formatters", mapKey)
			if mapVal.Description != "" || doc.HasInContainer(subTable, "description") {
				if err := doc.SetInContainer(subTable, "description", mapVal.Description); err != nil {
					return err
				}
			}
			if len(mapVal.Shell) > 0 || doc.HasInContainer(subTable, "shell") {
				if err := doc.SetInContainer(subTable, "shell", mapVal.Shell); err != nil {
					return err
				}
			}
			if mapVal.Script != "" {
				if err := doc.SetMultilineInContainer(subTable, "script", mapVal.Script); err != nil {
					return err
				}
			} else {
				_ = doc.DeleteFromContainer(subTable, "script")
			}
			if len(mapVal.Env) > 0 {
				tableNode := doc.EnsureTable("env")
				document.DeleteAllInContainer(tableNode)
				for k, v := range mapVal.Env {
					if err := doc.SetInContainer(tableNode, k, v); err != nil {
						return err
					}
				}
			}
			if mapVal.UTI != "" || doc.HasInContainer(subTable, "uti") {
				if err := doc.SetInContainer(subTable, "uti", mapVal.UTI); err != nil {
					return err
				}
			}
			if err := doc.SetInContainer(subTable, "utis", mapVal.UTIS); err != nil {
				return err
			}
			if mapVal.FileExtension != "" || doc.HasInContainer(subTable, "file-extension") {
				if err := doc.SetInContainer(subTable, "file-extension", mapVal.FileExtension); err != nil {
					return err
				}
			}
		}
	}
	if data.Hooks != "" || doc.HasInContainer(container, "hooks") {
		if err := doc.SetInContainer(container, "hooks", data.Hooks); err != nil {
			return err
		}
	}
	if data.References != nil {
		tableNode := doc.EnsureTableInContainer(container, "references")
		if data.References.Description != "" || doc.HasInContainer(tableNode, "description") {
			if err := doc.SetInContainer(tableNode, "description", data.References.Description); err != nil {
				return err
			}
		}
		if len(data.References.Shell) > 0 || doc.HasInContainer(tableNode, "shell") {
			if err := doc.SetInContainer(tableNode, "shell", data.References.Shell); err != nil {
				return err
			}
		}
		if data.References.Script != "" {
			if err := doc.SetMultilineInContainer(tableNode, "script", data.References.Script); err != nil {
				return err
			}
		} else {
			_ = doc.DeleteFromContainer(tableNode, "script")
		}
		if len(data.References.Env) > 0 {
			tableNode := doc.EnsureTable("env")
			document.DeleteAllInContainer(tableNode)
			for k, v := range data.References.Env {
				if err := doc.SetInContainer(tableNode, k, v); err != nil {
					return err
				}
			}
		}
		if data.References.Optional != false {
			if err := doc.SetInContainer(tableNode, "optional", data.References.Optional); err != nil {
				return err
			}
		} else {
			_ = doc.DeleteFromContainer(tableNode, "optional")
		}
	}

	return nil
}
