// Code generated by tommy; DO NOT EDIT.

package type_blobs

import (
	"fmt"

	"code.linenisgreat.com/dodder/go/lib/delta/script_config"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type TomlV1Document struct {
	data     TomlV1
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlV1(input []byte) (*TomlV1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlV1Document{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "binary"); err == nil {
		d.data.Binary = v
		d.consumed["binary"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "file-extension"); err == nil {
		d.data.FileExtension = v
		d.consumed["file-extension"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "mime-type"); err == nil {
		d.data.MimeType = v
		d.consumed["mime-type"] = true
	}
	if tableNode := d.cstDoc.FindTable("exec-command"); tableNode != nil {
		d.consumed["exec-command"] = true
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "description"); err == nil {
			d.data.ExecCommand.Description = v
			d.consumed["exec-command.description"] = true
		}
		if v, err := document.GetFromContainer[[]string](d.cstDoc, tableNode, "shell"); err == nil {
			d.data.ExecCommand.Shell = v
			d.consumed["exec-command.shell"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "script"); err == nil {
			d.data.ExecCommand.Script = v
			d.consumed["exec-command.script"] = true
		}
		if tableNode := d.cstDoc.FindTable("env"); tableNode != nil {
			d.data.ExecCommand.Env = document.GetStringMapFromTable(tableNode)
			d.consumed["exec-command.env"] = true
			document.MarkAllConsumed(tableNode, "exec-command.env", d.consumed)
		}
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "vim-syntax-type"); err == nil {
		d.data.VimSyntaxType = v
		d.consumed["vim-syntax-type"] = true
	}
	{
		subTables := d.cstDoc.FindSubTables("uti-groups")
		if len(subTables) > 0 {
			d.consumed["uti-groups"] = true
			d.data.UTIGroups = make(map[string]UTIGroup)
			for _, subTable := range subTables {
				mapKey := document.SubTableKey(subTable, "uti-groups")
				d.consumed["uti-groups"+"."+mapKey] = true
				inner := document.GetStringMapFromTable(subTable)
				document.MarkAllConsumed(subTable, "uti-groups"+"."+mapKey, d.consumed)
				d.data.UTIGroups[mapKey] = UTIGroup(inner)
			}
		}
	}
	{
		subTables := d.cstDoc.FindSubTables("formatters")
		if len(subTables) > 0 {
			d.consumed["formatters"] = true
			d.data.Formatters = make(map[string]script_config.WithOutputFormat)
			for _, subTable := range subTables {
				mapKey := document.SubTableKey(subTable, "formatters")
				d.consumed["formatters"+"."+mapKey] = true
				var entry script_config.WithOutputFormat
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "description"); err == nil {
					entry.Description = v
					d.consumed["formatters.\" + mapKey + \".description"] = true
				}
				if v, err := document.GetFromContainer[[]string](d.cstDoc, subTable, "shell"); err == nil {
					entry.Shell = v
					d.consumed["formatters.\" + mapKey + \".shell"] = true
				}
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "script"); err == nil {
					entry.Script = v
					d.consumed["formatters.\" + mapKey + \".script"] = true
				}
				if tableNode := d.cstDoc.FindTable("env"); tableNode != nil {
					entry.Env = document.GetStringMapFromTable(tableNode)
					d.consumed["formatters.\" + mapKey + \".env"] = true
					document.MarkAllConsumed(tableNode, "formatters.\" + mapKey + \".env", d.consumed)
				}
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "uti"); err == nil {
					entry.UTI = v
					d.consumed["formatters.\" + mapKey + \".uti"] = true
				}
				if v, err := document.GetFromContainer[[]string](d.cstDoc, subTable, "utis"); err == nil {
					entry.UTIS = v
					d.consumed["formatters.\" + mapKey + \".utis"] = true
				}
				if v, err := document.GetFromContainer[string](d.cstDoc, subTable, "file-extension"); err == nil {
					entry.FileExtension = v
					d.consumed["formatters.\" + mapKey + \".file-extension"] = true
				}
				d.data.Formatters[mapKey] = entry
			}
		}
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "hooks"); err == nil {
		d.data.Hooks = v
		d.consumed["hooks"] = true
	}
	if tableNode := d.cstDoc.FindTableInContainer(d.cstDoc.Root(), "references"); tableNode != nil {
		d.consumed["references"] = true
		referencesVal := &ReferencesConfig{}
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "description"); err == nil {
			referencesVal.Description = v
			d.consumed["references.description"] = true
		}
		if v, err := document.GetFromContainer[[]string](d.cstDoc, tableNode, "shell"); err == nil {
			referencesVal.Shell = v
			d.consumed["references.shell"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "script"); err == nil {
			referencesVal.Script = v
			d.consumed["references.script"] = true
		}
		if tableNode := d.cstDoc.FindTable("env"); tableNode != nil {
			referencesVal.Env = document.GetStringMapFromTable(tableNode)
			d.consumed["references.env"] = true
			document.MarkAllConsumed(tableNode, "references.env", d.consumed)
		}
		if v, err := document.GetFromContainer[bool](d.cstDoc, tableNode, "optional"); err == nil {
			referencesVal.Optional = v
			d.consumed["references.optional"] = true
		}
		d.data.References = referencesVal
	} else {
		referencesVal := &ReferencesConfig{}
		found := false
		if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "description"); err == nil {
			referencesVal.Description = v
			found = true
			d.consumed["description"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "script"); err == nil {
			referencesVal.Script = v
			found = true
			d.consumed["script"] = true
		}
		if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "optional"); err == nil {
			referencesVal.Optional = v
			found = true
			d.consumed["optional"] = true
		}
		if found {
			d.data.References = referencesVal
		}
	}

	return d, nil
}

func (d *TomlV1Document) Data() *TomlV1 { return &d.data }

func (d *TomlV1Document) Encode() ([]byte, error) {
	if d.data.Binary != false {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "binary", d.data.Binary); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "binary")
	}
	if d.data.FileExtension != "" {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "file-extension", d.data.FileExtension); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "file-extension")
	}
	if d.data.MimeType != "" {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "mime-type", d.data.MimeType); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "mime-type")
	}
	if tableNode := d.cstDoc.FindTable("exec-command"); tableNode != nil {
		if d.data.ExecCommand.Description != "" || d.cstDoc.HasInContainer(tableNode, "description") {
			if err := d.cstDoc.SetInContainer(tableNode, "description", d.data.ExecCommand.Description); err != nil {
				return nil, err
			}
		}
		if len(d.data.ExecCommand.Shell) > 0 || d.cstDoc.HasInContainer(tableNode, "shell") {
			if err := d.cstDoc.SetInContainer(tableNode, "shell", d.data.ExecCommand.Shell); err != nil {
				return nil, err
			}
		}
		if d.data.ExecCommand.Script != "" {
			if err := d.cstDoc.SetMultilineInContainer(tableNode, "script", d.data.ExecCommand.Script); err != nil {
				return nil, err
			}
		} else {
			_ = d.cstDoc.DeleteFromContainer(tableNode, "script")
		}
		if len(d.data.ExecCommand.Env) > 0 {
			tableNode := d.cstDoc.EnsureTable("env")
			document.DeleteAllInContainer(tableNode)
			for k, v := range d.data.ExecCommand.Env {
				if err := d.cstDoc.SetInContainer(tableNode, k, v); err != nil {
					return nil, err
				}
			}
		}
	}
	if d.data.VimSyntaxType != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "vim-syntax-type") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "vim-syntax-type", d.data.VimSyntaxType); err != nil {
			return nil, err
		}
	}
	if len(d.data.UTIGroups) > 0 {
		for mapKey, mapVal := range d.data.UTIGroups {
			subTable := d.cstDoc.EnsureSubTable("uti-groups", mapKey)
			document.DeleteAllInContainer(subTable)
			for k, v := range map[string]string(mapVal) {
				if err := d.cstDoc.SetInContainer(subTable, k, v); err != nil {
					return nil, err
				}
			}
		}
	}
	if len(d.data.Formatters) > 0 {
		for mapKey, mapVal := range d.data.Formatters {
			subTable := d.cstDoc.EnsureSubTable("formatters", mapKey)
			if mapVal.Description != "" || d.cstDoc.HasInContainer(subTable, "description") {
				if err := d.cstDoc.SetInContainer(subTable, "description", mapVal.Description); err != nil {
					return nil, err
				}
			}
			if len(mapVal.Shell) > 0 || d.cstDoc.HasInContainer(subTable, "shell") {
				if err := d.cstDoc.SetInContainer(subTable, "shell", mapVal.Shell); err != nil {
					return nil, err
				}
			}
			if mapVal.Script != "" {
				if err := d.cstDoc.SetMultilineInContainer(subTable, "script", mapVal.Script); err != nil {
					return nil, err
				}
			} else {
				_ = d.cstDoc.DeleteFromContainer(subTable, "script")
			}
			if len(mapVal.Env) > 0 {
				tableNode := d.cstDoc.EnsureTable("env")
				document.DeleteAllInContainer(tableNode)
				for k, v := range mapVal.Env {
					if err := d.cstDoc.SetInContainer(tableNode, k, v); err != nil {
						return nil, err
					}
				}
			}
			if mapVal.UTI != "" || d.cstDoc.HasInContainer(subTable, "uti") {
				if err := d.cstDoc.SetInContainer(subTable, "uti", mapVal.UTI); err != nil {
					return nil, err
				}
			}
			if err := d.cstDoc.SetInContainer(subTable, "utis", mapVal.UTIS); err != nil {
				return nil, err
			}
			if mapVal.FileExtension != "" || d.cstDoc.HasInContainer(subTable, "file-extension") {
				if err := d.cstDoc.SetInContainer(subTable, "file-extension", mapVal.FileExtension); err != nil {
					return nil, err
				}
			}
		}
	}
	if d.data.Hooks != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "hooks") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "hooks", d.data.Hooks); err != nil {
			return nil, err
		}
	}
	if d.data.References != nil {
		if tableNode := d.cstDoc.FindTableInContainer(d.cstDoc.Root(), "references"); tableNode != nil {
			if d.data.References.Description != "" || d.cstDoc.HasInContainer(tableNode, "description") {
				if err := d.cstDoc.SetInContainer(tableNode, "description", d.data.References.Description); err != nil {
					return nil, err
				}
			}
			if len(d.data.References.Shell) > 0 || d.cstDoc.HasInContainer(tableNode, "shell") {
				if err := d.cstDoc.SetInContainer(tableNode, "shell", d.data.References.Shell); err != nil {
					return nil, err
				}
			}
			if d.data.References.Script != "" {
				if err := d.cstDoc.SetMultilineInContainer(tableNode, "script", d.data.References.Script); err != nil {
					return nil, err
				}
			} else {
				_ = d.cstDoc.DeleteFromContainer(tableNode, "script")
			}
			if len(d.data.References.Env) > 0 {
				tableNode := d.cstDoc.EnsureTable("env")
				document.DeleteAllInContainer(tableNode)
				for k, v := range d.data.References.Env {
					if err := d.cstDoc.SetInContainer(tableNode, k, v); err != nil {
						return nil, err
					}
				}
			}
			if d.data.References.Optional != false {
				if err := d.cstDoc.SetInContainer(tableNode, "optional", d.data.References.Optional); err != nil {
					return nil, err
				}
			} else {
				_ = d.cstDoc.DeleteFromContainer(tableNode, "optional")
			}
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *TomlV1Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
