// Code generated by tommy; DO NOT EDIT.

package blob_store_configs

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type SignatureConfigDocument struct {
	data     SignatureConfig
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeSignatureConfig(input []byte) (*SignatureConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &SignatureConfigDocument{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "type"); err == nil {
		d.data.Type = v
		d.consumed["type"] = true
	}
	if v, err := document.GetFromContainer[int](d.cstDoc, d.cstDoc.Root(), "signature-len"); err == nil {
		d.data.SignatureLen = v
		d.consumed["signature-len"] = true
	}
	if v, err := document.GetFromContainer[int](d.cstDoc, d.cstDoc.Root(), "avg-chunk-size"); err == nil {
		d.data.AvgChunkSize = v
		d.consumed["avg-chunk-size"] = true
	}
	if v, err := document.GetFromContainer[int](d.cstDoc, d.cstDoc.Root(), "min-chunk-size"); err == nil {
		d.data.MinChunkSize = v
		d.consumed["min-chunk-size"] = true
	}
	if v, err := document.GetFromContainer[int](d.cstDoc, d.cstDoc.Root(), "max-chunk-size"); err == nil {
		d.data.MaxChunkSize = v
		d.consumed["max-chunk-size"] = true
	}

	return d, nil
}

func (d *SignatureConfigDocument) Data() *SignatureConfig { return &d.data }

func (d *SignatureConfigDocument) Encode() ([]byte, error) {
	if d.data.Type != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "type") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "type", d.data.Type); err != nil {
			return nil, err
		}
	}
	if d.data.SignatureLen != 0 || d.cstDoc.HasInContainer(d.cstDoc.Root(), "signature-len") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "signature-len", d.data.SignatureLen); err != nil {
			return nil, err
		}
	}
	if d.data.AvgChunkSize != 0 || d.cstDoc.HasInContainer(d.cstDoc.Root(), "avg-chunk-size") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "avg-chunk-size", d.data.AvgChunkSize); err != nil {
			return nil, err
		}
	}
	if d.data.MinChunkSize != 0 || d.cstDoc.HasInContainer(d.cstDoc.Root(), "min-chunk-size") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "min-chunk-size", d.data.MinChunkSize); err != nil {
			return nil, err
		}
	}
	if d.data.MaxChunkSize != 0 || d.cstDoc.HasInContainer(d.cstDoc.Root(), "max-chunk-size") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "max-chunk-size", d.data.MaxChunkSize); err != nil {
			return nil, err
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *SignatureConfigDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

type SelectorConfigDocument struct {
	data     SelectorConfig
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeSelectorConfig(input []byte) (*SelectorConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &SelectorConfigDocument{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "type"); err == nil {
		d.data.Type = v
		d.consumed["type"] = true
	}
	if v, err := document.GetFromContainer[int](d.cstDoc, d.cstDoc.Root(), "bands"); err == nil {
		d.data.Bands = v
		d.consumed["bands"] = true
	}
	if v, err := document.GetFromContainer[int](d.cstDoc, d.cstDoc.Root(), "rows-per-band"); err == nil {
		d.data.RowsPerBand = v
		d.consumed["rows-per-band"] = true
	}
	if v, err := document.GetFromContainer[uint64](d.cstDoc, d.cstDoc.Root(), "min-blob-size"); err == nil {
		d.data.MinBlobSize = v
		d.consumed["min-blob-size"] = true
	}
	if v, err := document.GetFromContainer[uint64](d.cstDoc, d.cstDoc.Root(), "max-blob-size"); err == nil {
		d.data.MaxBlobSize = v
		d.consumed["max-blob-size"] = true
	}

	return d, nil
}

func (d *SelectorConfigDocument) Data() *SelectorConfig { return &d.data }

func (d *SelectorConfigDocument) Encode() ([]byte, error) {
	if d.data.Type != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "type") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "type", d.data.Type); err != nil {
			return nil, err
		}
	}
	if d.data.Bands != 0 || d.cstDoc.HasInContainer(d.cstDoc.Root(), "bands") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "bands", d.data.Bands); err != nil {
			return nil, err
		}
	}
	if d.data.RowsPerBand != 0 || d.cstDoc.HasInContainer(d.cstDoc.Root(), "rows-per-band") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "rows-per-band", d.data.RowsPerBand); err != nil {
			return nil, err
		}
	}
	if d.data.MinBlobSize != 0 || d.cstDoc.HasInContainer(d.cstDoc.Root(), "min-blob-size") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "min-blob-size", d.data.MinBlobSize); err != nil {
			return nil, err
		}
	}
	if d.data.MaxBlobSize != 0 || d.cstDoc.HasInContainer(d.cstDoc.Root(), "max-blob-size") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "max-blob-size", d.data.MaxBlobSize); err != nil {
			return nil, err
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *SelectorConfigDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

type DeltaConfigDocument struct {
	data     DeltaConfig
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeDeltaConfig(input []byte) (*DeltaConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &DeltaConfigDocument{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "enabled"); err == nil {
		d.data.Enabled = v
		d.consumed["enabled"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "algorithm"); err == nil {
		d.data.Algorithm = v
		d.consumed["algorithm"] = true
	}
	if v, err := document.GetFromContainer[uint64](d.cstDoc, d.cstDoc.Root(), "min-blob-size"); err == nil {
		d.data.MinBlobSize = v
		d.consumed["min-blob-size"] = true
	}
	if v, err := document.GetFromContainer[uint64](d.cstDoc, d.cstDoc.Root(), "max-blob-size"); err == nil {
		d.data.MaxBlobSize = v
		d.consumed["max-blob-size"] = true
	}
	if v, err := document.GetFromContainer[float64](d.cstDoc, d.cstDoc.Root(), "size-ratio"); err == nil {
		d.data.SizeRatio = v
		d.consumed["size-ratio"] = true
	}
	if tableNode := d.cstDoc.FindTable("signature"); tableNode != nil {
		d.consumed["signature"] = true
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "type"); err == nil {
			d.data.Signature.Type = v
			d.consumed["signature.type"] = true
		}
		if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "signature-len"); err == nil {
			d.data.Signature.SignatureLen = v
			d.consumed["signature.signature-len"] = true
		}
		if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "avg-chunk-size"); err == nil {
			d.data.Signature.AvgChunkSize = v
			d.consumed["signature.avg-chunk-size"] = true
		}
		if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "min-chunk-size"); err == nil {
			d.data.Signature.MinChunkSize = v
			d.consumed["signature.min-chunk-size"] = true
		}
		if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "max-chunk-size"); err == nil {
			d.data.Signature.MaxChunkSize = v
			d.consumed["signature.max-chunk-size"] = true
		}
	}
	if tableNode := d.cstDoc.FindTable("selector"); tableNode != nil {
		d.consumed["selector"] = true
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "type"); err == nil {
			d.data.Selector.Type = v
			d.consumed["selector.type"] = true
		}
		if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "bands"); err == nil {
			d.data.Selector.Bands = v
			d.consumed["selector.bands"] = true
		}
		if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "rows-per-band"); err == nil {
			d.data.Selector.RowsPerBand = v
			d.consumed["selector.rows-per-band"] = true
		}
		if v, err := document.GetFromContainer[uint64](d.cstDoc, tableNode, "min-blob-size"); err == nil {
			d.data.Selector.MinBlobSize = v
			d.consumed["selector.min-blob-size"] = true
		}
		if v, err := document.GetFromContainer[uint64](d.cstDoc, tableNode, "max-blob-size"); err == nil {
			d.data.Selector.MaxBlobSize = v
			d.consumed["selector.max-blob-size"] = true
		}
	}

	return d, nil
}

func (d *DeltaConfigDocument) Data() *DeltaConfig { return &d.data }

func (d *DeltaConfigDocument) Encode() ([]byte, error) {
	if d.data.Enabled != false || d.cstDoc.HasInContainer(d.cstDoc.Root(), "enabled") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "enabled", d.data.Enabled); err != nil {
			return nil, err
		}
	}
	if d.data.Algorithm != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "algorithm") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "algorithm", d.data.Algorithm); err != nil {
			return nil, err
		}
	}
	if d.data.MinBlobSize != 0 || d.cstDoc.HasInContainer(d.cstDoc.Root(), "min-blob-size") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "min-blob-size", d.data.MinBlobSize); err != nil {
			return nil, err
		}
	}
	if d.data.MaxBlobSize != 0 || d.cstDoc.HasInContainer(d.cstDoc.Root(), "max-blob-size") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "max-blob-size", d.data.MaxBlobSize); err != nil {
			return nil, err
		}
	}
	if d.data.SizeRatio != 0.0 || d.cstDoc.HasInContainer(d.cstDoc.Root(), "size-ratio") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "size-ratio", d.data.SizeRatio); err != nil {
			return nil, err
		}
	}
	if tableNode := d.cstDoc.FindTable("signature"); tableNode != nil {
		if d.data.Signature.Type != "" || d.cstDoc.HasInContainer(tableNode, "type") {
			if err := d.cstDoc.SetInContainer(tableNode, "type", d.data.Signature.Type); err != nil {
				return nil, err
			}
		}
		if d.data.Signature.SignatureLen != 0 || d.cstDoc.HasInContainer(tableNode, "signature-len") {
			if err := d.cstDoc.SetInContainer(tableNode, "signature-len", d.data.Signature.SignatureLen); err != nil {
				return nil, err
			}
		}
		if d.data.Signature.AvgChunkSize != 0 || d.cstDoc.HasInContainer(tableNode, "avg-chunk-size") {
			if err := d.cstDoc.SetInContainer(tableNode, "avg-chunk-size", d.data.Signature.AvgChunkSize); err != nil {
				return nil, err
			}
		}
		if d.data.Signature.MinChunkSize != 0 || d.cstDoc.HasInContainer(tableNode, "min-chunk-size") {
			if err := d.cstDoc.SetInContainer(tableNode, "min-chunk-size", d.data.Signature.MinChunkSize); err != nil {
				return nil, err
			}
		}
		if d.data.Signature.MaxChunkSize != 0 || d.cstDoc.HasInContainer(tableNode, "max-chunk-size") {
			if err := d.cstDoc.SetInContainer(tableNode, "max-chunk-size", d.data.Signature.MaxChunkSize); err != nil {
				return nil, err
			}
		}
	}
	if tableNode := d.cstDoc.FindTable("selector"); tableNode != nil {
		if d.data.Selector.Type != "" || d.cstDoc.HasInContainer(tableNode, "type") {
			if err := d.cstDoc.SetInContainer(tableNode, "type", d.data.Selector.Type); err != nil {
				return nil, err
			}
		}
		if d.data.Selector.Bands != 0 || d.cstDoc.HasInContainer(tableNode, "bands") {
			if err := d.cstDoc.SetInContainer(tableNode, "bands", d.data.Selector.Bands); err != nil {
				return nil, err
			}
		}
		if d.data.Selector.RowsPerBand != 0 || d.cstDoc.HasInContainer(tableNode, "rows-per-band") {
			if err := d.cstDoc.SetInContainer(tableNode, "rows-per-band", d.data.Selector.RowsPerBand); err != nil {
				return nil, err
			}
		}
		if d.data.Selector.MinBlobSize != 0 || d.cstDoc.HasInContainer(tableNode, "min-blob-size") {
			if err := d.cstDoc.SetInContainer(tableNode, "min-blob-size", d.data.Selector.MinBlobSize); err != nil {
				return nil, err
			}
		}
		if d.data.Selector.MaxBlobSize != 0 || d.cstDoc.HasInContainer(tableNode, "max-blob-size") {
			if err := d.cstDoc.SetInContainer(tableNode, "max-blob-size", d.data.Selector.MaxBlobSize); err != nil {
				return nil, err
			}
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *DeltaConfigDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

type TomlInventoryArchiveV1Document struct {
	data     TomlInventoryArchiveV1
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlInventoryArchiveV1(input []byte) (*TomlInventoryArchiveV1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlInventoryArchiveV1Document{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "hash_type-id"); err == nil {
		if err := d.data.HashTypeId.UnmarshalText([]byte(v)); err != nil {
			return nil, fmt.Errorf("hash_type-id: %w", err)
		}
		d.consumed["hash_type-id"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "compression-type"); err == nil {
		if err := d.data.CompressionType.UnmarshalText([]byte(v)); err != nil {
			return nil, fmt.Errorf("compression-type: %w", err)
		}
		d.consumed["compression-type"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "loose-blob-store-id"); err == nil {
		if err := d.data.LooseBlobStoreId.UnmarshalText([]byte(v)); err != nil {
			return nil, fmt.Errorf("loose-blob-store-id: %w", err)
		}
		d.consumed["loose-blob-store-id"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "encryption"); err == nil {
		if err := d.data.Encryption.UnmarshalText([]byte(v)); err != nil {
			return nil, fmt.Errorf("encryption: %w", err)
		}
		d.consumed["encryption"] = true
	}
	if tableNode := d.cstDoc.FindTable("delta"); tableNode != nil {
		d.consumed["delta"] = true
		if v, err := document.GetFromContainer[bool](d.cstDoc, tableNode, "enabled"); err == nil {
			d.data.Delta.Enabled = v
			d.consumed["delta.enabled"] = true
		}
		if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "algorithm"); err == nil {
			d.data.Delta.Algorithm = v
			d.consumed["delta.algorithm"] = true
		}
		if v, err := document.GetFromContainer[uint64](d.cstDoc, tableNode, "min-blob-size"); err == nil {
			d.data.Delta.MinBlobSize = v
			d.consumed["delta.min-blob-size"] = true
		}
		if v, err := document.GetFromContainer[uint64](d.cstDoc, tableNode, "max-blob-size"); err == nil {
			d.data.Delta.MaxBlobSize = v
			d.consumed["delta.max-blob-size"] = true
		}
		if v, err := document.GetFromContainer[float64](d.cstDoc, tableNode, "size-ratio"); err == nil {
			d.data.Delta.SizeRatio = v
			d.consumed["delta.size-ratio"] = true
		}
		if tableNode := d.cstDoc.FindTable("signature"); tableNode != nil {
			d.consumed["delta.signature"] = true
			if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "type"); err == nil {
				d.data.Delta.Signature.Type = v
				d.consumed["delta.signature.type"] = true
			}
			if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "signature-len"); err == nil {
				d.data.Delta.Signature.SignatureLen = v
				d.consumed["delta.signature.signature-len"] = true
			}
			if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "avg-chunk-size"); err == nil {
				d.data.Delta.Signature.AvgChunkSize = v
				d.consumed["delta.signature.avg-chunk-size"] = true
			}
			if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "min-chunk-size"); err == nil {
				d.data.Delta.Signature.MinChunkSize = v
				d.consumed["delta.signature.min-chunk-size"] = true
			}
			if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "max-chunk-size"); err == nil {
				d.data.Delta.Signature.MaxChunkSize = v
				d.consumed["delta.signature.max-chunk-size"] = true
			}
		}
		if tableNode := d.cstDoc.FindTable("selector"); tableNode != nil {
			d.consumed["delta.selector"] = true
			if v, err := document.GetFromContainer[string](d.cstDoc, tableNode, "type"); err == nil {
				d.data.Delta.Selector.Type = v
				d.consumed["delta.selector.type"] = true
			}
			if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "bands"); err == nil {
				d.data.Delta.Selector.Bands = v
				d.consumed["delta.selector.bands"] = true
			}
			if v, err := document.GetFromContainer[int](d.cstDoc, tableNode, "rows-per-band"); err == nil {
				d.data.Delta.Selector.RowsPerBand = v
				d.consumed["delta.selector.rows-per-band"] = true
			}
			if v, err := document.GetFromContainer[uint64](d.cstDoc, tableNode, "min-blob-size"); err == nil {
				d.data.Delta.Selector.MinBlobSize = v
				d.consumed["delta.selector.min-blob-size"] = true
			}
			if v, err := document.GetFromContainer[uint64](d.cstDoc, tableNode, "max-blob-size"); err == nil {
				d.data.Delta.Selector.MaxBlobSize = v
				d.consumed["delta.selector.max-blob-size"] = true
			}
		}
	}
	if v, err := document.GetFromContainer[uint64](d.cstDoc, d.cstDoc.Root(), "max-pack-size"); err == nil {
		d.data.MaxPackSize = v
		d.consumed["max-pack-size"] = true
	}

	return d, nil
}

func (d *TomlInventoryArchiveV1Document) Data() *TomlInventoryArchiveV1 { return &d.data }

func (d *TomlInventoryArchiveV1Document) Encode() ([]byte, error) {
	{
		v, err := d.data.HashTypeId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("hash_type-id: %w", err)
		}
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "hash_type-id", string(v)); err != nil {
			return nil, err
		}
	}
	{
		v, err := d.data.CompressionType.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("compression-type: %w", err)
		}
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "compression-type", string(v)); err != nil {
			return nil, err
		}
	}
	{
		v, err := d.data.LooseBlobStoreId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("loose-blob-store-id: %w", err)
		}
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "loose-blob-store-id", string(v)); err != nil {
			return nil, err
		}
	}
	{
		v, err := d.data.Encryption.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("encryption: %w", err)
		}
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "encryption", string(v)); err != nil {
			return nil, err
		}
	}
	if tableNode := d.cstDoc.FindTable("delta"); tableNode != nil {
		if d.data.Delta.Enabled != false || d.cstDoc.HasInContainer(tableNode, "enabled") {
			if err := d.cstDoc.SetInContainer(tableNode, "enabled", d.data.Delta.Enabled); err != nil {
				return nil, err
			}
		}
		if d.data.Delta.Algorithm != "" || d.cstDoc.HasInContainer(tableNode, "algorithm") {
			if err := d.cstDoc.SetInContainer(tableNode, "algorithm", d.data.Delta.Algorithm); err != nil {
				return nil, err
			}
		}
		if d.data.Delta.MinBlobSize != 0 || d.cstDoc.HasInContainer(tableNode, "min-blob-size") {
			if err := d.cstDoc.SetInContainer(tableNode, "min-blob-size", d.data.Delta.MinBlobSize); err != nil {
				return nil, err
			}
		}
		if d.data.Delta.MaxBlobSize != 0 || d.cstDoc.HasInContainer(tableNode, "max-blob-size") {
			if err := d.cstDoc.SetInContainer(tableNode, "max-blob-size", d.data.Delta.MaxBlobSize); err != nil {
				return nil, err
			}
		}
		if d.data.Delta.SizeRatio != 0.0 || d.cstDoc.HasInContainer(tableNode, "size-ratio") {
			if err := d.cstDoc.SetInContainer(tableNode, "size-ratio", d.data.Delta.SizeRatio); err != nil {
				return nil, err
			}
		}
		if tableNode := d.cstDoc.FindTable("signature"); tableNode != nil {
			if d.data.Delta.Signature.Type != "" || d.cstDoc.HasInContainer(tableNode, "type") {
				if err := d.cstDoc.SetInContainer(tableNode, "type", d.data.Delta.Signature.Type); err != nil {
					return nil, err
				}
			}
			if d.data.Delta.Signature.SignatureLen != 0 || d.cstDoc.HasInContainer(tableNode, "signature-len") {
				if err := d.cstDoc.SetInContainer(tableNode, "signature-len", d.data.Delta.Signature.SignatureLen); err != nil {
					return nil, err
				}
			}
			if d.data.Delta.Signature.AvgChunkSize != 0 || d.cstDoc.HasInContainer(tableNode, "avg-chunk-size") {
				if err := d.cstDoc.SetInContainer(tableNode, "avg-chunk-size", d.data.Delta.Signature.AvgChunkSize); err != nil {
					return nil, err
				}
			}
			if d.data.Delta.Signature.MinChunkSize != 0 || d.cstDoc.HasInContainer(tableNode, "min-chunk-size") {
				if err := d.cstDoc.SetInContainer(tableNode, "min-chunk-size", d.data.Delta.Signature.MinChunkSize); err != nil {
					return nil, err
				}
			}
			if d.data.Delta.Signature.MaxChunkSize != 0 || d.cstDoc.HasInContainer(tableNode, "max-chunk-size") {
				if err := d.cstDoc.SetInContainer(tableNode, "max-chunk-size", d.data.Delta.Signature.MaxChunkSize); err != nil {
					return nil, err
				}
			}
		}
		if tableNode := d.cstDoc.FindTable("selector"); tableNode != nil {
			if d.data.Delta.Selector.Type != "" || d.cstDoc.HasInContainer(tableNode, "type") {
				if err := d.cstDoc.SetInContainer(tableNode, "type", d.data.Delta.Selector.Type); err != nil {
					return nil, err
				}
			}
			if d.data.Delta.Selector.Bands != 0 || d.cstDoc.HasInContainer(tableNode, "bands") {
				if err := d.cstDoc.SetInContainer(tableNode, "bands", d.data.Delta.Selector.Bands); err != nil {
					return nil, err
				}
			}
			if d.data.Delta.Selector.RowsPerBand != 0 || d.cstDoc.HasInContainer(tableNode, "rows-per-band") {
				if err := d.cstDoc.SetInContainer(tableNode, "rows-per-band", d.data.Delta.Selector.RowsPerBand); err != nil {
					return nil, err
				}
			}
			if d.data.Delta.Selector.MinBlobSize != 0 || d.cstDoc.HasInContainer(tableNode, "min-blob-size") {
				if err := d.cstDoc.SetInContainer(tableNode, "min-blob-size", d.data.Delta.Selector.MinBlobSize); err != nil {
					return nil, err
				}
			}
			if d.data.Delta.Selector.MaxBlobSize != 0 || d.cstDoc.HasInContainer(tableNode, "max-blob-size") {
				if err := d.cstDoc.SetInContainer(tableNode, "max-blob-size", d.data.Delta.Selector.MaxBlobSize); err != nil {
					return nil, err
				}
			}
		}
	}
	if d.data.MaxPackSize != 0 || d.cstDoc.HasInContainer(d.cstDoc.Root(), "max-pack-size") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "max-pack-size", d.data.MaxPackSize); err != nil {
			return nil, err
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *TomlInventoryArchiveV1Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
