// Code generated by tommy; DO NOT EDIT.

package blob_store_configs

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type TomlSFTPViaSSHConfigV0Document struct {
	data     TomlSFTPViaSSHConfigV0
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlSFTPViaSSHConfigV0(input []byte) (*TomlSFTPViaSSHConfigV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlSFTPViaSSHConfigV0Document{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "uri"); err == nil {
		if err := d.data.Uri.UnmarshalText([]byte(v)); err != nil {
			return nil, fmt.Errorf("uri: %w", err)
		}
		d.consumed["uri"] = true
	}

	return d, nil
}

func (d *TomlSFTPViaSSHConfigV0Document) Data() *TomlSFTPViaSSHConfigV0 { return &d.data }

func (d *TomlSFTPViaSSHConfigV0Document) Encode() ([]byte, error) {
	{
		v, err := d.data.Uri.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("uri: %w", err)
		}
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "uri", string(v)); err != nil {
			return nil, err
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *TomlSFTPViaSSHConfigV0Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func (d *TomlSFTPViaSSHConfigV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlSFTPViaSSHConfigV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlSFTPViaSSHConfigV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlSFTPViaSSHConfigV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlSFTPViaSSHConfigV0Into(data *TomlSFTPViaSSHConfigV0, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	if v, err := document.GetFromContainer[string](doc, container, "uri"); err == nil {
		if err := data.Uri.UnmarshalText([]byte(v)); err != nil {
			return fmt.Errorf("uri: %w", err)
		}
		consumed[keyPrefix+"uri"] = true
	}

	return nil
}

func EncodeTomlSFTPViaSSHConfigV0From(data *TomlSFTPViaSSHConfigV0, doc *document.Document, container *cst.Node) error {
	{
		v, err := data.Uri.MarshalText()
		if err != nil {
			return fmt.Errorf("uri: %w", err)
		}
		if err := doc.SetInContainer(container, "uri", string(v)); err != nil {
			return err
		}
	}

	return nil
}
