// Code generated by tommy; DO NOT EDIT.

package blob_store_configs

import (
	"fmt"

	"code.linenisgreat.com/dodder/go/internal/bravo/markl"
	"code.linenisgreat.com/dodder/go/lib/charlie/values"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type TomlV3Document struct {
	data     TomlV3
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlV3(input []byte) (*TomlV3Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlV3Document{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[[]int](d.cstDoc, d.cstDoc.Root(), "hash_buckets"); err == nil {
		d.data.HashBuckets = values.IntSlice(v)
		d.consumed["hash_buckets"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "base_path"); err == nil {
		d.data.BasePath = v
		d.consumed["base_path"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "hash_type-id"); err == nil {
		if err := d.data.HashTypeId.UnmarshalText([]byte(v)); err != nil {
			return nil, fmt.Errorf("hash_type-id: %w", err)
		}
		d.consumed["hash_type-id"] = true
	}
	if v, err := document.GetFromContainer[[]string](d.cstDoc, d.cstDoc.Root(), "encryption"); err == nil {
		d.data.Encryption = make([]markl.Id, len(v))
		for i, s := range v {
			if err := d.data.Encryption[i].UnmarshalText([]byte(s)); err != nil {
				return nil, fmt.Errorf("encryption[%d]: %w", i, err)
			}
		}
		d.consumed["encryption"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "compression-type"); err == nil {
		if err := d.data.CompressionType.UnmarshalText([]byte(v)); err != nil {
			return nil, fmt.Errorf("compression-type: %w", err)
		}
		d.consumed["compression-type"] = true
	}
	if v, err := document.GetFromContainer[bool](d.cstDoc, d.cstDoc.Root(), "lock-internal-files"); err == nil {
		d.data.LockInternalFiles = v
		d.consumed["lock-internal-files"] = true
	}

	return d, nil
}

func (d *TomlV3Document) Data() *TomlV3 { return &d.data }

func (d *TomlV3Document) Encode() ([]byte, error) {
	if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "hash_buckets", []int(d.data.HashBuckets)); err != nil {
		return nil, err
	}
	if d.data.BasePath != "" {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "base_path", d.data.BasePath); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "base_path")
	}
	{
		v, err := d.data.HashTypeId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("hash_type-id: %w", err)
		}
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "hash_type-id", string(v)); err != nil {
			return nil, err
		}
	}
	{
		vals := make([]string, len(d.data.Encryption))
		for i, item := range d.data.Encryption {
			v, err := item.MarshalText()
			if err != nil {
				return nil, fmt.Errorf("encryption[%d]: %w", i, err)
			}
			vals[i] = string(v)
		}
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "encryption", vals); err != nil {
			return nil, err
		}
	}
	{
		v, err := d.data.CompressionType.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("compression-type: %w", err)
		}
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "compression-type", string(v)); err != nil {
			return nil, err
		}
	}
	if d.data.LockInternalFiles != false || d.cstDoc.HasInContainer(d.cstDoc.Root(), "lock-internal-files") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "lock-internal-files", d.data.LockInternalFiles); err != nil {
			return nil, err
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *TomlV3Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}

func DecodeTomlV3Into(data *TomlV3, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	if v, err := document.GetFromContainer[[]int](doc, container, "hash_buckets"); err == nil {
		data.HashBuckets = values.IntSlice(v)
		consumed[keyPrefix+"hash_buckets"] = true
	}
	if v, err := document.GetFromContainer[string](doc, container, "base_path"); err == nil {
		data.BasePath = v
		consumed[keyPrefix+"base_path"] = true
	}
	if v, err := document.GetFromContainer[string](doc, container, "hash_type-id"); err == nil {
		if err := data.HashTypeId.UnmarshalText([]byte(v)); err != nil {
			return fmt.Errorf("hash_type-id: %w", err)
		}
		consumed[keyPrefix+"hash_type-id"] = true
	}
	if v, err := document.GetFromContainer[[]string](doc, container, "encryption"); err == nil {
		data.Encryption = make([]markl.Id, len(v))
		for i, s := range v {
			if err := data.Encryption[i].UnmarshalText([]byte(s)); err != nil {
				return fmt.Errorf("encryption[%d]: %w", i, err)
			}
		}
		consumed[keyPrefix+"encryption"] = true
	}
	if v, err := document.GetFromContainer[string](doc, container, "compression-type"); err == nil {
		if err := data.CompressionType.UnmarshalText([]byte(v)); err != nil {
			return fmt.Errorf("compression-type: %w", err)
		}
		consumed[keyPrefix+"compression-type"] = true
	}
	if v, err := document.GetFromContainer[bool](doc, container, "lock-internal-files"); err == nil {
		data.LockInternalFiles = v
		consumed[keyPrefix+"lock-internal-files"] = true
	}

	return nil
}

func EncodeTomlV3From(data *TomlV3, doc *document.Document, container *cst.Node) error {
	if err := doc.SetInContainer(container, "hash_buckets", []int(data.HashBuckets)); err != nil {
		return err
	}
	if data.BasePath != "" {
		if err := doc.SetInContainer(container, "base_path", data.BasePath); err != nil {
			return err
		}
	} else {
		_ = doc.DeleteFromContainer(container, "base_path")
	}
	{
		v, err := data.HashTypeId.MarshalText()
		if err != nil {
			return fmt.Errorf("hash_type-id: %w", err)
		}
		if err := doc.SetInContainer(container, "hash_type-id", string(v)); err != nil {
			return err
		}
	}
	{
		vals := make([]string, len(data.Encryption))
		for i, item := range data.Encryption {
			v, err := item.MarshalText()
			if err != nil {
				return fmt.Errorf("encryption[%d]: %w", i, err)
			}
			vals[i] = string(v)
		}
		if err := doc.SetInContainer(container, "encryption", vals); err != nil {
			return err
		}
	}
	{
		v, err := data.CompressionType.MarshalText()
		if err != nil {
			return fmt.Errorf("compression-type: %w", err)
		}
		if err := doc.SetInContainer(container, "compression-type", string(v)); err != nil {
			return err
		}
	}
	if data.LockInternalFiles != false || doc.HasInContainer(container, "lock-internal-files") {
		if err := doc.SetInContainer(container, "lock-internal-files", data.LockInternalFiles); err != nil {
			return err
		}
	}

	return nil
}
