// Code generated by tommy 0.5.0 (47364f2); DO NOT EDIT.

package type_blobs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type FieldDefinitionDocument struct {
	data   FieldDefinition
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeFieldDefinition(input []byte) (*FieldDefinitionDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	return decodeFieldDefinitionParsed(doc)
}

// DecodeFieldDefinitionStrict is DecodeFieldDefinition for input that must be exactly what it
// claims: it returns a *cst.SyntaxError when input is not well-formed TOML and
// *cst.TypeError values when a key's TOML type does not match its field, where
// DecodeFieldDefinition would decode leniently. Keys no field claims are not errors; they
// stay in Undecoded.
func DecodeFieldDefinitionStrict(input []byte) (*FieldDefinitionDocument, error) {
	doc, err := document.ParseStrict(input)
	if err != nil {
		return nil, err
	}
	d, err := decodeFieldDefinitionParsed(doc)
	if err != nil {
		return nil, err
	}
	if err := d.model.TypeErrors(); err != nil {
		return nil, err
	}
	return d, nil
}

func decodeFieldDefinitionParsed(doc *document.Document) (*FieldDefinitionDocument, error) {
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &FieldDefinitionDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vName, _ok := model.Field("name"); _ok && _vName.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vName.Leaf); _xok {
			d.data.Name = _x
			_vName.MarkConsumedString()
		}
	}
	if _vKind, _ok := model.Field("kind"); _ok && _vKind.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vKind.Leaf); _xok {
			d.data.Kind = _x
			_vKind.MarkConsumedString()
		}
	}
	if _vValues, _ok := model.Field("values"); _ok && _vValues.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vValues.Leaf); _xok {
			d.data.Values = _x
			if d.data.Values == nil {
				d.data.Values = []string{}
			}
			_vValues.MarkConsumed()
		}
	}
	if _vDefault, _ok := model.Field("default"); _ok && _vDefault.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDefault.Leaf); _xok {
			d.data.Default = _x
			_vDefault.MarkConsumedString()
		}
	}
	if _vRequired, _ok := model.Field("required"); _ok && _vRequired.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vRequired.Leaf); _xok {
			d.data.Required = _x
			_vRequired.MarkConsumed()
		}
	}
	if _vTerminal, _ok := model.Field("terminal"); _ok && _vTerminal.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vTerminal.Leaf); _xok {
			d.data.Terminal = _x
			if d.data.Terminal == nil {
				d.data.Terminal = []string{}
			}
			_vTerminal.MarkConsumed()
		}
	}
	if _vOmitEmpty, _ok := model.Field("omit-empty"); _ok && _vOmitEmpty.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vOmitEmpty.Leaf); _xok {
			d.data.OmitEmpty = _x
			_vOmitEmpty.MarkConsumed()
		}
	}
	return d, nil
}

func (d *FieldDefinitionDocument) Data() *FieldDefinition {
	return &d.data
}

func (d *FieldDefinitionDocument) Encode() ([]byte, error) {
	if d.data.Name != "" || cst.HasValue(d.cstDoc.Root(), "name") {
		if err := cst.SetAny(d.cstDoc.Root(), "name", d.data.Name); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Kind != "" || cst.HasValue(d.cstDoc.Root(), "kind") {
		if err := cst.SetAny(d.cstDoc.Root(), "kind", d.data.Kind); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		if len(d.data.Values) > 0 || cst.HasValue(d.cstDoc.Root(), "values") {
			if err := cst.SetAny(d.cstDoc.Root(), "values", d.data.Values); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.Default != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "default", d.data.Default); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "default")
	}
	if d.data.Required != false {
		if err := cst.SetAny(d.cstDoc.Root(), "required", d.data.Required); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "required")
	}
	{
		if len(d.data.Terminal) > 0 || cst.HasValue(d.cstDoc.Root(), "terminal") {
			if err := cst.SetAny(d.cstDoc.Root(), "terminal", d.data.Terminal); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.OmitEmpty != false {
		if err := cst.SetAny(d.cstDoc.Root(), "omit-empty", d.data.OmitEmpty); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "omit-empty")
	}
	return d.cstDoc.Bytes(), nil
}

func (d *FieldDefinitionDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *FieldDefinitionDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *FieldDefinitionDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *FieldDefinitionDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *FieldDefinitionDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeFieldDefinitionInto(data *FieldDefinition, sub *cst.Value) error {
	if _vName, _ok := sub.Field("name"); _ok && _vName.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vName.Leaf); _xok {
			data.Name = _x
			_vName.MarkConsumedString()
		}
	}
	if _vKind, _ok := sub.Field("kind"); _ok && _vKind.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vKind.Leaf); _xok {
			data.Kind = _x
			_vKind.MarkConsumedString()
		}
	}
	if _vValues, _ok := sub.Field("values"); _ok && _vValues.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vValues.Leaf); _xok {
			data.Values = _x
			if data.Values == nil {
				data.Values = []string{}
			}
			_vValues.MarkConsumed()
		}
	}
	if _vDefault, _ok := sub.Field("default"); _ok && _vDefault.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDefault.Leaf); _xok {
			data.Default = _x
			_vDefault.MarkConsumedString()
		}
	}
	if _vRequired, _ok := sub.Field("required"); _ok && _vRequired.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vRequired.Leaf); _xok {
			data.Required = _x
			_vRequired.MarkConsumed()
		}
	}
	if _vTerminal, _ok := sub.Field("terminal"); _ok && _vTerminal.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vTerminal.Leaf); _xok {
			data.Terminal = _x
			if data.Terminal == nil {
				data.Terminal = []string{}
			}
			_vTerminal.MarkConsumed()
		}
	}
	if _vOmitEmpty, _ok := sub.Field("omit-empty"); _ok && _vOmitEmpty.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vOmitEmpty.Leaf); _xok {
			data.OmitEmpty = _x
			_vOmitEmpty.MarkConsumed()
		}
	}
	return nil
}

func EncodeFieldDefinitionFrom(data *FieldDefinition, doc *document.Document, container *cst.Node) error {
	if data.Name != "" || cst.HasValue(container, "name") {
		if err := cst.SetAny(container, "name", data.Name); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Kind != "" || cst.HasValue(container, "kind") {
		if err := cst.SetAny(container, "kind", data.Kind); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		if len(data.Values) > 0 || cst.HasValue(container, "values") {
			if err := cst.SetAny(container, "values", data.Values); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.Default != "" {
		if err := cst.SetAny(container, "default", data.Default); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "default")
	}
	if data.Required != false {
		if err := cst.SetAny(container, "required", data.Required); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "required")
	}
	{
		if len(data.Terminal) > 0 || cst.HasValue(container, "terminal") {
			if err := cst.SetAny(container, "terminal", data.Terminal); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.OmitEmpty != false {
		if err := cst.SetAny(container, "omit-empty", data.OmitEmpty); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "omit-empty")
	}
	return nil
}
