// Code generated by tommy 0.5.0 (a5d3780); DO NOT EDIT.

package type_blobs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type FieldDefinitionDocument struct {
	data   FieldDefinition
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeFieldDefinition(input []byte) (*FieldDefinitionDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &FieldDefinitionDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vName, _ok := model.Get("name"); _ok && _vName.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vName.Leaf); _xok {
			d.data.Name = _x
			_vName.MarkConsumed()
		}
	}
	if _vKind, _ok := model.Get("kind"); _ok && _vKind.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vKind.Leaf); _xok {
			d.data.Kind = _x
			_vKind.MarkConsumed()
		}
	}
	if _vValues, _ok := model.Get("values"); _ok && _vValues.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vValues.Leaf); _xok {
			d.data.Values = _x
			if d.data.Values == nil {
				d.data.Values = []string{}
			}
			_vValues.MarkConsumed()
		}
	}
	if _vDefault, _ok := model.Get("default"); _ok && _vDefault.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDefault.Leaf); _xok {
			d.data.Default = _x
			_vDefault.MarkConsumed()
		}
	}
	if _vRequired, _ok := model.Get("required"); _ok && _vRequired.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vRequired.Leaf); _xok {
			d.data.Required = _x
			_vRequired.MarkConsumed()
		}
	}
	return d, nil
}

func (d *FieldDefinitionDocument) Data() *FieldDefinition {
	return &d.data
}

func (d *FieldDefinitionDocument) Encode() ([]byte, error) {
	if d.data.Name != "" || cst.HasValue(d.cstDoc.Root(), "name") {
		if err := cst.SetAny(d.cstDoc.Root(), "name", d.data.Name); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Kind != "" || cst.HasValue(d.cstDoc.Root(), "kind") {
		if err := cst.SetAny(d.cstDoc.Root(), "kind", d.data.Kind); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		if len(d.data.Values) > 0 || cst.HasValue(d.cstDoc.Root(), "values") {
			if err := cst.SetAny(d.cstDoc.Root(), "values", d.data.Values); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.Default != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "default", d.data.Default); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "default")
	}
	if d.data.Required != false {
		if err := cst.SetAny(d.cstDoc.Root(), "required", d.data.Required); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "required")
	}
	return d.cstDoc.Bytes(), nil
}

func (d *FieldDefinitionDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *FieldDefinitionDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *FieldDefinitionDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *FieldDefinitionDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *FieldDefinitionDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeFieldDefinitionInto(data *FieldDefinition, sub *cst.Value) error {
	if _vName, _ok := sub.Get("name"); _ok && _vName.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vName.Leaf); _xok {
			data.Name = _x
			_vName.MarkConsumed()
		}
	}
	if _vKind, _ok := sub.Get("kind"); _ok && _vKind.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vKind.Leaf); _xok {
			data.Kind = _x
			_vKind.MarkConsumed()
		}
	}
	if _vValues, _ok := sub.Get("values"); _ok && _vValues.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vValues.Leaf); _xok {
			data.Values = _x
			if data.Values == nil {
				data.Values = []string{}
			}
			_vValues.MarkConsumed()
		}
	}
	if _vDefault, _ok := sub.Get("default"); _ok && _vDefault.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDefault.Leaf); _xok {
			data.Default = _x
			_vDefault.MarkConsumed()
		}
	}
	if _vRequired, _ok := sub.Get("required"); _ok && _vRequired.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vRequired.Leaf); _xok {
			data.Required = _x
			_vRequired.MarkConsumed()
		}
	}
	return nil
}

func EncodeFieldDefinitionFrom(data *FieldDefinition, doc *document.Document, container *cst.Node) error {
	if data.Name != "" || cst.HasValue(container, "name") {
		if err := cst.SetAny(container, "name", data.Name); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Kind != "" || cst.HasValue(container, "kind") {
		if err := cst.SetAny(container, "kind", data.Kind); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		if len(data.Values) > 0 || cst.HasValue(container, "values") {
			if err := cst.SetAny(container, "values", data.Values); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.Default != "" {
		if err := cst.SetAny(container, "default", data.Default); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "default")
	}
	if data.Required != false {
		if err := cst.SetAny(container, "required", data.Required); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "required")
	}
	return nil
}
