// Code generated by tommy 0.5.0 (47364f2); DO NOT EDIT.

package type_blobs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type ReferencesConfigDocument struct {
	data   ReferencesConfig
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeReferencesConfig(input []byte) (*ReferencesConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	return decodeReferencesConfigParsed(doc)
}

// DecodeReferencesConfigStrict is DecodeReferencesConfig for input that must be exactly what it
// claims: it returns a *cst.SyntaxError when input is not well-formed TOML and
// *cst.TypeError values when a key's TOML type does not match its field, where
// DecodeReferencesConfig would decode leniently. Keys no field claims are not errors; they
// stay in Undecoded.
func DecodeReferencesConfigStrict(input []byte) (*ReferencesConfigDocument, error) {
	doc, err := document.ParseStrict(input)
	if err != nil {
		return nil, err
	}
	d, err := decodeReferencesConfigParsed(doc)
	if err != nil {
		return nil, err
	}
	if err := d.model.TypeErrors(); err != nil {
		return nil, err
	}
	return d, nil
}

func decodeReferencesConfigParsed(doc *document.Document) (*ReferencesConfigDocument, error) {
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &ReferencesConfigDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vDescription, _ok := model.Field("description"); _ok && _vDescription.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDescription.Leaf); _xok {
			d.data.Description = _x
			_vDescription.MarkConsumedString()
		}
	}
	if _vShell, _ok := model.Field("shell"); _ok && _vShell.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vShell.Leaf); _xok {
			d.data.Shell = _x
			if d.data.Shell == nil {
				d.data.Shell = []string{}
			}
			_vShell.MarkConsumed()
		}
	}
	if _vScript, _ok := model.Field("script"); _ok && _vScript.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vScript.Leaf); _xok {
			d.data.Script = _x
			_vScript.MarkConsumedString()
		}
	}
	if _vEnv, _ok := model.Field("env"); _ok && _vEnv.Kind == cst.VTable {
		_vEnv.MarkSeen()
		_vEnv.MarkEntriesKnown()
		d.data.Env = make(map[string]string)
		for _iEnv := range _vEnv.Fields {
			_fEnv := &_vEnv.Fields[_iEnv]
			if _fEnv.Val.Kind == cst.VLeaf {
				if _s, _sok := cst.ExtractString(_fEnv.Val.Leaf); _sok {
					d.data.Env[_fEnv.Key] = _s
					_fEnv.Val.MarkConsumedString()
				}
			}
		}
	}
	if _vOptional, _ok := model.Field("optional"); _ok && _vOptional.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vOptional.Leaf); _xok {
			d.data.Optional = _x
			_vOptional.MarkConsumed()
		}
	}
	return d, nil
}

func (d *ReferencesConfigDocument) Data() *ReferencesConfig {
	return &d.data
}

func (d *ReferencesConfigDocument) Encode() ([]byte, error) {
	if d.data.Description != "" || cst.HasValue(d.cstDoc.Root(), "description") {
		if err := cst.SetAny(d.cstDoc.Root(), "description", d.data.Description); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		if len(d.data.Shell) > 0 || cst.HasValue(d.cstDoc.Root(), "shell") {
			if err := cst.SetAny(d.cstDoc.Root(), "shell", d.data.Shell); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.Script != "" {
		if err := cst.SetMultilineString(d.cstDoc.Root(), "script", d.data.Script); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "script")
	}
	if len(d.data.Env) > 0 || cst.FindChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "env") != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "env")
		cst.DeleteAllValues(tableNode)
		for k, v := range d.data.Env {
			if err := cst.SetAny(tableNode, k, v); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.Optional != false {
		if err := cst.SetAny(d.cstDoc.Root(), "optional", d.data.Optional); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "optional")
	}
	return d.cstDoc.Bytes(), nil
}

func (d *ReferencesConfigDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *ReferencesConfigDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *ReferencesConfigDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *ReferencesConfigDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *ReferencesConfigDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeReferencesConfigInto(data *ReferencesConfig, sub *cst.Value) error {
	if _vDescription, _ok := sub.Field("description"); _ok && _vDescription.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vDescription.Leaf); _xok {
			data.Description = _x
			_vDescription.MarkConsumedString()
		}
	}
	if _vShell, _ok := sub.Field("shell"); _ok && _vShell.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vShell.Leaf); _xok {
			data.Shell = _x
			if data.Shell == nil {
				data.Shell = []string{}
			}
			_vShell.MarkConsumed()
		}
	}
	if _vScript, _ok := sub.Field("script"); _ok && _vScript.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vScript.Leaf); _xok {
			data.Script = _x
			_vScript.MarkConsumedString()
		}
	}
	if _vEnv, _ok := sub.Field("env"); _ok && _vEnv.Kind == cst.VTable {
		_vEnv.MarkSeen()
		_vEnv.MarkEntriesKnown()
		data.Env = make(map[string]string)
		for _iEnv := range _vEnv.Fields {
			_fEnv := &_vEnv.Fields[_iEnv]
			if _fEnv.Val.Kind == cst.VLeaf {
				if _s, _sok := cst.ExtractString(_fEnv.Val.Leaf); _sok {
					data.Env[_fEnv.Key] = _s
					_fEnv.Val.MarkConsumedString()
				}
			}
		}
	}
	if _vOptional, _ok := sub.Field("optional"); _ok && _vOptional.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vOptional.Leaf); _xok {
			data.Optional = _x
			_vOptional.MarkConsumed()
		}
	}
	return nil
}

func EncodeReferencesConfigFrom(data *ReferencesConfig, doc *document.Document, container *cst.Node) error {
	if data.Description != "" || cst.HasValue(container, "description") {
		if err := cst.SetAny(container, "description", data.Description); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		if len(data.Shell) > 0 || cst.HasValue(container, "shell") {
			if err := cst.SetAny(container, "shell", data.Shell); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.Script != "" {
		if err := cst.SetMultilineString(container, "script", data.Script); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "script")
	}
	if len(data.Env) > 0 || cst.FindChildTable(doc.Root(), container, "env") != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "env")
		cst.DeleteAllValues(tableNode)
		for k, v := range data.Env {
			if err := cst.SetAny(tableNode, k, v); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.Optional != false {
		if err := cst.SetAny(container, "optional", data.Optional); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "optional")
	}
	return nil
}
