// Code generated by tommy; DO NOT EDIT.

package type_blobs

import (
	"code.linenisgreat.com/dodder/go/lib/bravo/script_config"
	"fmt"
	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
	"strings"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlV0Document struct {
	data     TomlV0
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlV0(input []byte) (*TomlV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlV0Document{
		consumed: make(map[string]bool),
		cstDoc:   doc,
	}

	for _, _kv := range d.cstDoc.Root().Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "inline-akte":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.InlineBlob = v
				d.consumed["inline-akte"] = true
			}
		case "archived":
			if v, ok := cst.ExtractBool(_kv); ok {
				d.data.Archived = v
				d.consumed["archived"] = true
			}
		case "file-extension":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.FileExtension = v
				d.consumed["file-extension"] = true
			}
		case "vim-syntax-type":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.VimSyntaxType = v
				d.consumed["vim-syntax-type"] = true
			}
		case "hooks":
			if v, ok := cst.ExtractString(_kv); ok {
				d.data.Hooks = v
				d.consumed["hooks"] = true
			}
		}
	}
	{
		var _tbl *cst.Node
		for _, _ch := range d.cstDoc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == "exec-command" {
				_tbl = _ch
				break
			}
		}
		if _tbl != nil {
			d.consumed["exec-command"] = true
			scriptConfigVal := &script_config.ScriptConfig{}
			if err := script_config.DecodeScriptConfigInto(scriptConfigVal, d.cstDoc, _tbl, d.consumed, "exec-command."); err != nil {
				return nil, fmt.Errorf("exec-command: %w", err)
			}
			d.data.ExecCommand = scriptConfigVal
		}
	}
	{
		var _mr map[string]UTIGroup
		for _, _ch := range d.cstDoc.Root().Children {
			if _ch.Kind != cst.NodeTable {
				continue
			}
			_hdr := cst.TableHeaderKey(_ch)
			if !strings.HasPrefix(_hdr, "formatter-uti-groups.") {
				continue
			}
			_mk := _hdr[21:]
			if _mr == nil {
				d.consumed["formatter-uti-groups"] = true
				_mr = make(map[string]UTIGroup)
			}
			d.consumed["formatter-uti-groups"+"."+_mk] = true
			_inner := cst.ExtractStringMap(_ch)
			for _ik := range _inner {
				d.consumed["formatter-uti-groups"+"."+_mk+"."+_ik] = true
			}
			_mr[_mk] = UTIGroup(_inner)
		}
		if _mr != nil {
			d.data.FormatterUTIGroups = _mr
		}
	}
	{
		for _, _ch := range d.cstDoc.Root().Children {
			if _ch.Kind != cst.NodeTable {
				continue
			}
			_hdr := cst.TableHeaderKey(_ch)
			if !strings.HasPrefix(_hdr, "formatters.") {
				continue
			}
			_mk := _hdr[11:]
			if strings.Contains(_mk, ".") {
				continue
			}
			if d.data.Formatters == nil {
				d.consumed["formatters"] = true
				d.data.Formatters = make(map[string]script_config.WithOutputFormat)
			}
			d.consumed["formatters"+"."+_mk] = true
			var entry script_config.WithOutputFormat
			if err := script_config.DecodeWithOutputFormatInto(&entry, d.cstDoc, _ch, d.consumed, "formatters."+_mk+"."); err != nil {
				return nil, fmt.Errorf("formatters.%s: %w", _mk, err)
			}
			d.data.Formatters[_mk] = entry
		}
	}
	{
		for _, _ch := range d.cstDoc.Root().Children {
			if _ch.Kind != cst.NodeTable {
				continue
			}
			_hdr := cst.TableHeaderKey(_ch)
			if !strings.HasPrefix(_hdr, "actions.") {
				continue
			}
			_mk := _hdr[8:]
			if strings.Contains(_mk, ".") {
				continue
			}
			if d.data.Actions == nil {
				d.consumed["actions"] = true
				d.data.Actions = make(map[string]script_config.ScriptConfig)
			}
			d.consumed["actions"+"."+_mk] = true
			var entry script_config.ScriptConfig
			if err := script_config.DecodeScriptConfigInto(&entry, d.cstDoc, _ch, d.consumed, "actions."+_mk+"."); err != nil {
				return nil, fmt.Errorf("actions.%s: %w", _mk, err)
			}
			d.data.Actions[_mk] = entry
		}
	}
	return d, nil
}
func (d *TomlV0Document) Data() *TomlV0 {
	return &d.data
}
func (d *TomlV0Document) Encode() ([]byte, error) {
	if d.data.InlineBlob != false {
		if err := cst.SetAny(d.cstDoc.Root(), "inline-akte", d.data.InlineBlob); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "inline-akte")
	}
	if d.data.Archived != false {
		if err := cst.SetAny(d.cstDoc.Root(), "archived", d.data.Archived); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "archived")
	}
	if d.data.FileExtension != "" {
		if err := cst.SetAny(d.cstDoc.Root(), "file-extension", d.data.FileExtension); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(d.cstDoc.Root(), "file-extension")
	}
	if d.data.ExecCommand != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "exec-command")
		if err := script_config.EncodeScriptConfigFrom(d.data.ExecCommand, d.cstDoc, tableNode); err != nil {
			return nil, fmt.Errorf("exec-command: %w", err)
		}
	}
	if d.data.VimSyntaxType != "" || cst.HasValue(d.cstDoc.Root(), "vim-syntax-type") {
		if err := cst.SetAny(d.cstDoc.Root(), "vim-syntax-type", d.data.VimSyntaxType); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if len(d.data.FormatterUTIGroups) > 0 {
		for mapKey, mapVal := range d.data.FormatterUTIGroups {
			subTable := cst.EnsureChildSubTable(d.cstDoc.Root(), d.cstDoc.Root(), "formatter-uti-groups", mapKey)
			cst.DeleteAllValues(subTable)
			for k, v := range map[string]string(mapVal) {
				if err := cst.SetAny(subTable, k, v); err != nil {
					return nil, fmt.Errorf("%w", err)
				}
			}
		}
	}
	if len(d.data.Formatters) > 0 {
		for mapKey, mapVal := range d.data.Formatters {
			subTable := cst.EnsureChildSubTable(d.cstDoc.Root(), d.cstDoc.Root(), "formatters", mapKey)
			if err := script_config.EncodeWithOutputFormatFrom(&mapVal, d.cstDoc, subTable); err != nil {
				return nil, fmt.Errorf("formatters.%s: %w", mapKey, err)
			}
		}
	}
	if len(d.data.Actions) > 0 {
		for mapKey, mapVal := range d.data.Actions {
			subTable := cst.EnsureChildSubTable(d.cstDoc.Root(), d.cstDoc.Root(), "actions", mapKey)
			if err := script_config.EncodeScriptConfigFrom(&mapVal, d.cstDoc, subTable); err != nil {
				return nil, fmt.Errorf("actions.%s: %w", mapKey, err)
			}
		}
	}
	if d.data.Hooks != "" || cst.HasValue(d.cstDoc.Root(), "hooks") {
		if err := cst.SetAny(d.cstDoc.Root(), "hooks", d.data.Hooks); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}
func (d *TomlV0Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
func (d *TomlV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}
func (d *TomlV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}
func (d *TomlV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}
func (d *TomlV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}
func DecodeTomlV0Into(data *TomlV0, doc *document.Document, container *cst.Node, consumed map[string]bool, keyPrefix string) error {
	for _, _kv := range container.Children {
		if _kv.Kind != cst.NodeKeyValue {
			continue
		}
		switch cst.KeyValueName(_kv) {
		case "inline-akte":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.InlineBlob = v
				consumed[keyPrefix+"inline-akte"] = true
			}
		case "archived":
			if v, ok := cst.ExtractBool(_kv); ok {
				data.Archived = v
				consumed[keyPrefix+"archived"] = true
			}
		case "file-extension":
			if v, ok := cst.ExtractString(_kv); ok {
				data.FileExtension = v
				consumed[keyPrefix+"file-extension"] = true
			}
		case "vim-syntax-type":
			if v, ok := cst.ExtractString(_kv); ok {
				data.VimSyntaxType = v
				consumed[keyPrefix+"vim-syntax-type"] = true
			}
		case "hooks":
			if v, ok := cst.ExtractString(_kv); ok {
				data.Hooks = v
				consumed[keyPrefix+"hooks"] = true
			}
		}
	}
	{
		var _tbl *cst.Node
		for _, _ch := range doc.Root().Children {
			if _ch.Kind == cst.NodeTable && cst.TableHeaderKey(_ch) == keyPrefix+"exec-command" {
				_tbl = _ch
				break
			}
		}
		if _tbl != nil {
			consumed[keyPrefix+"exec-command"] = true
			scriptConfigVal := &script_config.ScriptConfig{}
			if err := script_config.DecodeScriptConfigInto(scriptConfigVal, doc, _tbl, consumed, keyPrefix+"exec-command."); err != nil {
				return fmt.Errorf("exec-command: %w", err)
			}
			data.ExecCommand = scriptConfigVal
		}
	}
	{
		var _mr map[string]UTIGroup
		for _, _ch := range doc.Root().Children {
			if _ch.Kind != cst.NodeTable {
				continue
			}
			_hdr := cst.TableHeaderKey(_ch)
			if !strings.HasPrefix(_hdr, keyPrefix+"formatter-uti-groups.") {
				continue
			}
			_mk := _hdr[len(keyPrefix)+len("formatter-uti-groups."):]
			if _mr == nil {
				consumed[keyPrefix+"formatter-uti-groups"] = true
				_mr = make(map[string]UTIGroup)
			}
			consumed[keyPrefix+"formatter-uti-groups"+"."+_mk] = true
			_inner := cst.ExtractStringMap(_ch)
			for _ik := range _inner {
				consumed[keyPrefix+"formatter-uti-groups"+"."+_mk+"."+_ik] = true
			}
			_mr[_mk] = UTIGroup(_inner)
		}
		if _mr != nil {
			data.FormatterUTIGroups = _mr
		}
	}
	{
		for _, _ch := range doc.Root().Children {
			if _ch.Kind != cst.NodeTable {
				continue
			}
			_hdr := cst.TableHeaderKey(_ch)
			if !strings.HasPrefix(_hdr, keyPrefix+"formatters.") {
				continue
			}
			_mk := _hdr[len(keyPrefix)+len("formatters."):]
			if strings.Contains(_mk, ".") {
				continue
			}
			if data.Formatters == nil {
				consumed[keyPrefix+"formatters"] = true
				data.Formatters = make(map[string]script_config.WithOutputFormat)
			}
			consumed[keyPrefix+"formatters"+"."+_mk] = true
			var entry script_config.WithOutputFormat
			if err := script_config.DecodeWithOutputFormatInto(&entry, doc, _ch, consumed, keyPrefix+"formatters."+_mk+"."); err != nil {
				return fmt.Errorf("formatters.%s: %w", _mk, err)
			}
			data.Formatters[_mk] = entry
		}
	}
	{
		for _, _ch := range doc.Root().Children {
			if _ch.Kind != cst.NodeTable {
				continue
			}
			_hdr := cst.TableHeaderKey(_ch)
			if !strings.HasPrefix(_hdr, keyPrefix+"actions.") {
				continue
			}
			_mk := _hdr[len(keyPrefix)+len("actions."):]
			if strings.Contains(_mk, ".") {
				continue
			}
			if data.Actions == nil {
				consumed[keyPrefix+"actions"] = true
				data.Actions = make(map[string]script_config.ScriptConfig)
			}
			consumed[keyPrefix+"actions"+"."+_mk] = true
			var entry script_config.ScriptConfig
			if err := script_config.DecodeScriptConfigInto(&entry, doc, _ch, consumed, keyPrefix+"actions."+_mk+"."); err != nil {
				return fmt.Errorf("actions.%s: %w", _mk, err)
			}
			data.Actions[_mk] = entry
		}
	}
	return nil
}
func EncodeTomlV0From(data *TomlV0, doc *document.Document, container *cst.Node) error {
	if data.InlineBlob != false {
		if err := cst.SetAny(container, "inline-akte", data.InlineBlob); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "inline-akte")
	}
	if data.Archived != false {
		if err := cst.SetAny(container, "archived", data.Archived); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "archived")
	}
	if data.FileExtension != "" {
		if err := cst.SetAny(container, "file-extension", data.FileExtension); err != nil {
			return fmt.Errorf("%w", err)
		}
	} else {
		cst.DeleteValue(container, "file-extension")
	}
	if data.ExecCommand != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "exec-command")
		if err := script_config.EncodeScriptConfigFrom(data.ExecCommand, doc, tableNode); err != nil {
			return fmt.Errorf("exec-command: %w", err)
		}
	}
	if data.VimSyntaxType != "" || cst.HasValue(container, "vim-syntax-type") {
		if err := cst.SetAny(container, "vim-syntax-type", data.VimSyntaxType); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if len(data.FormatterUTIGroups) > 0 {
		for mapKey, mapVal := range data.FormatterUTIGroups {
			subTable := cst.EnsureChildSubTable(doc.Root(), doc.Root(), "formatter-uti-groups", mapKey)
			cst.DeleteAllValues(subTable)
			for k, v := range map[string]string(mapVal) {
				if err := cst.SetAny(subTable, k, v); err != nil {
					return fmt.Errorf("%w", err)
				}
			}
		}
	}
	if len(data.Formatters) > 0 {
		for mapKey, mapVal := range data.Formatters {
			subTable := cst.EnsureChildSubTable(doc.Root(), container, "formatters", mapKey)
			if err := script_config.EncodeWithOutputFormatFrom(&mapVal, doc, subTable); err != nil {
				return fmt.Errorf("formatters.%s: %w", mapKey, err)
			}
		}
	}
	if len(data.Actions) > 0 {
		for mapKey, mapVal := range data.Actions {
			subTable := cst.EnsureChildSubTable(doc.Root(), container, "actions", mapKey)
			if err := script_config.EncodeScriptConfigFrom(&mapVal, doc, subTable); err != nil {
				return fmt.Errorf("actions.%s: %w", mapKey, err)
			}
		}
	}
	if data.Hooks != "" || cst.HasValue(container, "hooks") {
		if err := cst.SetAny(container, "hooks", data.Hooks); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
