// Code generated by tommy; DO NOT EDIT.

package script_config

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type ScriptConfigDocument struct {
	data     ScriptConfig
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeScriptConfig(input []byte) (*ScriptConfigDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &ScriptConfigDocument{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "description"); err == nil {
		d.data.Description = v
		d.consumed["description"] = true
	}
	if v, err := document.GetFromContainer[[]string](d.cstDoc, d.cstDoc.Root(), "shell"); err == nil {
		d.data.Shell = v
		d.consumed["shell"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "script"); err == nil {
		d.data.Script = v
		d.consumed["script"] = true
	}
	if tableNode := d.cstDoc.FindTable("env"); tableNode != nil {
		d.data.Env = document.GetStringMapFromTable(tableNode)
		d.consumed["env"] = true
		document.MarkAllConsumed(tableNode, "env", d.consumed)
	}

	return d, nil
}

func (d *ScriptConfigDocument) Data() *ScriptConfig { return &d.data }

func (d *ScriptConfigDocument) Encode() ([]byte, error) {
	if d.data.Description != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "description") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "description", d.data.Description); err != nil {
			return nil, err
		}
	}
	if len(d.data.Shell) > 0 || d.cstDoc.HasInContainer(d.cstDoc.Root(), "shell") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "shell", d.data.Shell); err != nil {
			return nil, err
		}
	}
	if d.data.Script != "" {
		if err := d.cstDoc.SetMultilineInContainer(d.cstDoc.Root(), "script", d.data.Script); err != nil {
			return nil, err
		}
	} else {
		_ = d.cstDoc.DeleteFromContainer(d.cstDoc.Root(), "script")
	}
	if len(d.data.Env) > 0 {
		tableNode := d.cstDoc.EnsureTable("env")
		document.DeleteAllInContainer(tableNode)
		for k, v := range d.data.Env {
			if err := d.cstDoc.SetInContainer(tableNode, k, v); err != nil {
				return nil, err
			}
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *ScriptConfigDocument) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
