// Code generated by tommy 0.4.3 (1ae69d3); DO NOT EDIT.

package options_print

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type V0Document struct {
	data   V0
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeV0(input []byte) (*V0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &V0Document{
		cstDoc: doc,
		model:  model,
	}

	if _vAbbreviations, _ok := model.Get("abbreviations"); _ok && _vAbbreviations.Kind == cst.VTable {
		_vAbbreviations.MarkSeen()
		abbreviationsVal0 := &abbreviationsV0{}
		if _vAbbreviationsHinweisen, _ok := _vAbbreviations.Get("hinweisen"); _ok && _vAbbreviationsHinweisen.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vAbbreviationsHinweisen.Leaf); _xok {
				abbreviationsVal0.ZettelIds = &_x
				_vAbbreviationsHinweisen.MarkConsumed()
			}
		}
		if _vAbbreviationsShas, _ok := _vAbbreviations.Get("shas"); _ok && _vAbbreviationsShas.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vAbbreviationsShas.Leaf); _xok {
				abbreviationsVal0.Shas = &_x
				_vAbbreviationsShas.MarkConsumed()
			}
		}
		d.data.Abbreviations = abbreviationsVal0
	} else {
		abbreviationsVal0 := &abbreviationsV0{}
		_foundAbbreviations := false
		if _vHinweisen, _ok := model.Get("hinweisen"); _ok && _vHinweisen.Kind == cst.VLeaf {
			_foundAbbreviations = true
			if _x, _xok := cst.ExtractBool(_vHinweisen.Leaf); _xok {
				abbreviationsVal0.ZettelIds = &_x
				_vHinweisen.MarkConsumed()
			}
		}
		if _vShas, _ok := model.Get("shas"); _ok && _vShas.Kind == cst.VLeaf {
			_foundAbbreviations = true
			if _x, _xok := cst.ExtractBool(_vShas.Leaf); _xok {
				abbreviationsVal0.Shas = &_x
				_vShas.MarkConsumed()
			}
		}
		if _foundAbbreviations {
			d.data.Abbreviations = abbreviationsVal0
		}
	}
	if _vPrintIncludeDescription, _ok := model.Get("print-include-description"); _ok && _vPrintIncludeDescription.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintIncludeDescription.Leaf); _xok {
			d.data.PrintIncludeDescription = &_x
			_vPrintIncludeDescription.MarkConsumed()
		}
	}
	if _vPrintTime, _ok := model.Get("print-time"); _ok && _vPrintTime.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintTime.Leaf); _xok {
			d.data.PrintTime = &_x
			_vPrintTime.MarkConsumed()
		}
	}
	if _vPrintEtikettenAlways, _ok := model.Get("print-etiketten-always"); _ok && _vPrintEtikettenAlways.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintEtikettenAlways.Leaf); _xok {
			d.data.PrintTagsAlways = &_x
			_vPrintEtikettenAlways.MarkConsumed()
		}
	}
	if _vPrintEmptyShas, _ok := model.Get("print-empty-shas"); _ok && _vPrintEmptyShas.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintEmptyShas.Leaf); _xok {
			d.data.PrintEmptyShas = &_x
			_vPrintEmptyShas.MarkConsumed()
		}
	}
	if _vPrintIncludeTypen, _ok := model.Get("print-include-typen"); _ok && _vPrintIncludeTypen.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintIncludeTypen.Leaf); _xok {
			d.data.PrintIncludeTypes = &_x
			_vPrintIncludeTypen.MarkConsumed()
		}
	}
	if _vPrintMatchedArchiviert, _ok := model.Get("print-matched-archiviert"); _ok && _vPrintMatchedArchiviert.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintMatchedArchiviert.Leaf); _xok {
			d.data.PrintMatchedDormant = &_x
			_vPrintMatchedArchiviert.MarkConsumed()
		}
	}
	if _vPrintShas, _ok := model.Get("print-shas"); _ok && _vPrintShas.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintShas.Leaf); _xok {
			d.data.PrintShas = &_x
			_vPrintShas.MarkConsumed()
		}
	}
	if _vPrintFlush, _ok := model.Get("print-flush"); _ok && _vPrintFlush.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintFlush.Leaf); _xok {
			d.data.PrintFlush = &_x
			_vPrintFlush.MarkConsumed()
		}
	}
	if _vPrintUnchanged, _ok := model.Get("print-unchanged"); _ok && _vPrintUnchanged.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintUnchanged.Leaf); _xok {
			d.data.PrintUnchanged = &_x
			_vPrintUnchanged.MarkConsumed()
		}
	}
	if _vPrintColors, _ok := model.Get("print-colors"); _ok && _vPrintColors.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintColors.Leaf); _xok {
			d.data.PrintColors = &_x
			_vPrintColors.MarkConsumed()
		}
	}
	if _vPrintBestandsaufnahme, _ok := model.Get("print-bestandsaufnahme"); _ok && _vPrintBestandsaufnahme.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintBestandsaufnahme.Leaf); _xok {
			d.data.PrintInventoryLists = &_x
			_vPrintBestandsaufnahme.MarkConsumed()
		}
	}
	return d, nil
}

func (d *V0Document) Data() *V0 {
	return &d.data
}

func (d *V0Document) Encode() ([]byte, error) {
	if d.data.Abbreviations != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "abbreviations")
		if d.data.Abbreviations.ZettelIds != nil {
			if err := cst.SetAny(tableNode, "hinweisen", *d.data.Abbreviations.ZettelIds); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Abbreviations.Shas != nil {
			if err := cst.SetAny(tableNode, "shas", *d.data.Abbreviations.Shas); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.PrintIncludeDescription != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-include-description", *d.data.PrintIncludeDescription); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintTime != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-time", *d.data.PrintTime); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintTagsAlways != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-etiketten-always", *d.data.PrintTagsAlways); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintEmptyShas != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-empty-shas", *d.data.PrintEmptyShas); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintIncludeTypes != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-include-typen", *d.data.PrintIncludeTypes); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintMatchedDormant != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-matched-archiviert", *d.data.PrintMatchedDormant); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintShas != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-shas", *d.data.PrintShas); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintFlush != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-flush", *d.data.PrintFlush); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintUnchanged != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-unchanged", *d.data.PrintUnchanged); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintColors != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-colors", *d.data.PrintColors); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintInventoryLists != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-bestandsaufnahme", *d.data.PrintInventoryLists); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *V0Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *V0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *V0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *V0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *V0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeV0Into(data *V0, sub *cst.Value) error {
	if _vAbbreviations, _ok := sub.Get("abbreviations"); _ok && _vAbbreviations.Kind == cst.VTable {
		_vAbbreviations.MarkSeen()
		abbreviationsVal0 := &abbreviationsV0{}
		if _vAbbreviationsHinweisen, _ok := _vAbbreviations.Get("hinweisen"); _ok && _vAbbreviationsHinweisen.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vAbbreviationsHinweisen.Leaf); _xok {
				abbreviationsVal0.ZettelIds = &_x
				_vAbbreviationsHinweisen.MarkConsumed()
			}
		}
		if _vAbbreviationsShas, _ok := _vAbbreviations.Get("shas"); _ok && _vAbbreviationsShas.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vAbbreviationsShas.Leaf); _xok {
				abbreviationsVal0.Shas = &_x
				_vAbbreviationsShas.MarkConsumed()
			}
		}
		data.Abbreviations = abbreviationsVal0
	} else {
		abbreviationsVal0 := &abbreviationsV0{}
		_foundAbbreviations := false
		if _vHinweisen, _ok := sub.Get("hinweisen"); _ok && _vHinweisen.Kind == cst.VLeaf {
			_foundAbbreviations = true
			if _x, _xok := cst.ExtractBool(_vHinweisen.Leaf); _xok {
				abbreviationsVal0.ZettelIds = &_x
				_vHinweisen.MarkConsumed()
			}
		}
		if _vShas, _ok := sub.Get("shas"); _ok && _vShas.Kind == cst.VLeaf {
			_foundAbbreviations = true
			if _x, _xok := cst.ExtractBool(_vShas.Leaf); _xok {
				abbreviationsVal0.Shas = &_x
				_vShas.MarkConsumed()
			}
		}
		if _foundAbbreviations {
			data.Abbreviations = abbreviationsVal0
		}
	}
	if _vPrintIncludeDescription, _ok := sub.Get("print-include-description"); _ok && _vPrintIncludeDescription.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintIncludeDescription.Leaf); _xok {
			data.PrintIncludeDescription = &_x
			_vPrintIncludeDescription.MarkConsumed()
		}
	}
	if _vPrintTime, _ok := sub.Get("print-time"); _ok && _vPrintTime.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintTime.Leaf); _xok {
			data.PrintTime = &_x
			_vPrintTime.MarkConsumed()
		}
	}
	if _vPrintEtikettenAlways, _ok := sub.Get("print-etiketten-always"); _ok && _vPrintEtikettenAlways.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintEtikettenAlways.Leaf); _xok {
			data.PrintTagsAlways = &_x
			_vPrintEtikettenAlways.MarkConsumed()
		}
	}
	if _vPrintEmptyShas, _ok := sub.Get("print-empty-shas"); _ok && _vPrintEmptyShas.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintEmptyShas.Leaf); _xok {
			data.PrintEmptyShas = &_x
			_vPrintEmptyShas.MarkConsumed()
		}
	}
	if _vPrintIncludeTypen, _ok := sub.Get("print-include-typen"); _ok && _vPrintIncludeTypen.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintIncludeTypen.Leaf); _xok {
			data.PrintIncludeTypes = &_x
			_vPrintIncludeTypen.MarkConsumed()
		}
	}
	if _vPrintMatchedArchiviert, _ok := sub.Get("print-matched-archiviert"); _ok && _vPrintMatchedArchiviert.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintMatchedArchiviert.Leaf); _xok {
			data.PrintMatchedDormant = &_x
			_vPrintMatchedArchiviert.MarkConsumed()
		}
	}
	if _vPrintShas, _ok := sub.Get("print-shas"); _ok && _vPrintShas.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintShas.Leaf); _xok {
			data.PrintShas = &_x
			_vPrintShas.MarkConsumed()
		}
	}
	if _vPrintFlush, _ok := sub.Get("print-flush"); _ok && _vPrintFlush.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintFlush.Leaf); _xok {
			data.PrintFlush = &_x
			_vPrintFlush.MarkConsumed()
		}
	}
	if _vPrintUnchanged, _ok := sub.Get("print-unchanged"); _ok && _vPrintUnchanged.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintUnchanged.Leaf); _xok {
			data.PrintUnchanged = &_x
			_vPrintUnchanged.MarkConsumed()
		}
	}
	if _vPrintColors, _ok := sub.Get("print-colors"); _ok && _vPrintColors.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintColors.Leaf); _xok {
			data.PrintColors = &_x
			_vPrintColors.MarkConsumed()
		}
	}
	if _vPrintBestandsaufnahme, _ok := sub.Get("print-bestandsaufnahme"); _ok && _vPrintBestandsaufnahme.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintBestandsaufnahme.Leaf); _xok {
			data.PrintInventoryLists = &_x
			_vPrintBestandsaufnahme.MarkConsumed()
		}
	}
	return nil
}

func EncodeV0From(data *V0, doc *document.Document, container *cst.Node) error {
	if data.Abbreviations != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "abbreviations")
		if data.Abbreviations.ZettelIds != nil {
			if err := cst.SetAny(tableNode, "hinweisen", *data.Abbreviations.ZettelIds); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Abbreviations.Shas != nil {
			if err := cst.SetAny(tableNode, "shas", *data.Abbreviations.Shas); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.PrintIncludeDescription != nil {
		if err := cst.SetAny(container, "print-include-description", *data.PrintIncludeDescription); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintTime != nil {
		if err := cst.SetAny(container, "print-time", *data.PrintTime); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintTagsAlways != nil {
		if err := cst.SetAny(container, "print-etiketten-always", *data.PrintTagsAlways); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintEmptyShas != nil {
		if err := cst.SetAny(container, "print-empty-shas", *data.PrintEmptyShas); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintIncludeTypes != nil {
		if err := cst.SetAny(container, "print-include-typen", *data.PrintIncludeTypes); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintMatchedDormant != nil {
		if err := cst.SetAny(container, "print-matched-archiviert", *data.PrintMatchedDormant); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintShas != nil {
		if err := cst.SetAny(container, "print-shas", *data.PrintShas); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintFlush != nil {
		if err := cst.SetAny(container, "print-flush", *data.PrintFlush); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintUnchanged != nil {
		if err := cst.SetAny(container, "print-unchanged", *data.PrintUnchanged); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintColors != nil {
		if err := cst.SetAny(container, "print-colors", *data.PrintColors); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintInventoryLists != nil {
		if err := cst.SetAny(container, "print-bestandsaufnahme", *data.PrintInventoryLists); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}

type abbreviationsV0Document struct {
	data   abbreviationsV0
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeabbreviationsV0(input []byte) (*abbreviationsV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &abbreviationsV0Document{
		cstDoc: doc,
		model:  model,
	}

	if _vHinweisen, _ok := model.Get("hinweisen"); _ok && _vHinweisen.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vHinweisen.Leaf); _xok {
			d.data.ZettelIds = &_x
			_vHinweisen.MarkConsumed()
		}
	}
	if _vShas, _ok := model.Get("shas"); _ok && _vShas.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vShas.Leaf); _xok {
			d.data.Shas = &_x
			_vShas.MarkConsumed()
		}
	}
	return d, nil
}

func (d *abbreviationsV0Document) Data() *abbreviationsV0 {
	return &d.data
}

func (d *abbreviationsV0Document) Encode() ([]byte, error) {
	if d.data.ZettelIds != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "hinweisen", *d.data.ZettelIds); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Shas != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "shas", *d.data.Shas); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *abbreviationsV0Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *abbreviationsV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *abbreviationsV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *abbreviationsV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *abbreviationsV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeabbreviationsV0Into(data *abbreviationsV0, sub *cst.Value) error {
	if _vHinweisen, _ok := sub.Get("hinweisen"); _ok && _vHinweisen.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vHinweisen.Leaf); _xok {
			data.ZettelIds = &_x
			_vHinweisen.MarkConsumed()
		}
	}
	if _vShas, _ok := sub.Get("shas"); _ok && _vShas.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vShas.Leaf); _xok {
			data.Shas = &_x
			_vShas.MarkConsumed()
		}
	}
	return nil
}

func EncodeabbreviationsV0From(data *abbreviationsV0, doc *document.Document, container *cst.Node) error {
	if data.ZettelIds != nil {
		if err := cst.SetAny(container, "hinweisen", *data.ZettelIds); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Shas != nil {
		if err := cst.SetAny(container, "shas", *data.Shas); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
