// Code generated by tommy 0.4.7 (65f9cee); DO NOT EDIT.

package options_print

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type V1Document struct {
	data   V1
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeV1(input []byte) (*V1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &V1Document{
		cstDoc: doc,
		model:  model,
	}

	if _vAbbreviations, _ok := model.Get("abbreviations"); _ok && _vAbbreviations.Kind == cst.VTable {
		_vAbbreviations.MarkSeen()
		abbreviationsVal0 := &abbreviationsV1{}
		if _vAbbreviationsZettelIds, _ok := _vAbbreviations.Get("zettel-ids"); _ok && _vAbbreviationsZettelIds.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vAbbreviationsZettelIds.Leaf); _xok {
				abbreviationsVal0.ZettelIds = &_x
				_vAbbreviationsZettelIds.MarkConsumed()
			}
		}
		if _vAbbreviationsShas, _ok := _vAbbreviations.Get("shas"); _ok && _vAbbreviationsShas.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vAbbreviationsShas.Leaf); _xok {
				abbreviationsVal0.MarklIds = &_x
				_vAbbreviationsShas.MarkConsumed()
			}
		}
		d.data.Abbreviations = abbreviationsVal0
	} else {
		abbreviationsVal0 := &abbreviationsV1{}
		_foundAbbreviations := false
		if _vZettelIds, _ok := model.Get("zettel-ids"); _ok && _vZettelIds.Kind == cst.VLeaf {
			_foundAbbreviations = true
			if _x, _xok := cst.ExtractBool(_vZettelIds.Leaf); _xok {
				abbreviationsVal0.ZettelIds = &_x
				_vZettelIds.MarkConsumed()
			}
		}
		if _vShas, _ok := model.Get("shas"); _ok && _vShas.Kind == cst.VLeaf {
			_foundAbbreviations = true
			if _x, _xok := cst.ExtractBool(_vShas.Leaf); _xok {
				abbreviationsVal0.MarklIds = &_x
				_vShas.MarkConsumed()
			}
		}
		if _foundAbbreviations {
			d.data.Abbreviations = abbreviationsVal0
		}
	}
	if _vPrintIncludeDescription, _ok := model.Get("print-include-description"); _ok && _vPrintIncludeDescription.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintIncludeDescription.Leaf); _xok {
			d.data.PrintIncludeDescription = &_x
			_vPrintIncludeDescription.MarkConsumed()
		}
	}
	if _vPrintTime, _ok := model.Get("print-time"); _ok && _vPrintTime.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintTime.Leaf); _xok {
			d.data.PrintTime = &_x
			_vPrintTime.MarkConsumed()
		}
	}
	if _vPrintEtikettenAlways, _ok := model.Get("print-etiketten-always"); _ok && _vPrintEtikettenAlways.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintEtikettenAlways.Leaf); _xok {
			d.data.PrintTagsAlways = &_x
			_vPrintEtikettenAlways.MarkConsumed()
		}
	}
	if _vPrintEmptyShas, _ok := model.Get("print-empty-shas"); _ok && _vPrintEmptyShas.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintEmptyShas.Leaf); _xok {
			d.data.PrintEmptyShas = &_x
			_vPrintEmptyShas.MarkConsumed()
		}
	}
	if _vPrintIncludeTypen, _ok := model.Get("print-include-typen"); _ok && _vPrintIncludeTypen.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintIncludeTypen.Leaf); _xok {
			d.data.PrintIncludeTypes = &_x
			_vPrintIncludeTypen.MarkConsumed()
		}
	}
	if _vPrintMatchedDormant, _ok := model.Get("print-matched-dormant"); _ok && _vPrintMatchedDormant.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintMatchedDormant.Leaf); _xok {
			d.data.PrintMatchedDormant = &_x
			_vPrintMatchedDormant.MarkConsumed()
		}
	}
	if _vPrintShas, _ok := model.Get("print-shas"); _ok && _vPrintShas.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintShas.Leaf); _xok {
			d.data.PrintShas = &_x
			_vPrintShas.MarkConsumed()
		}
	}
	if _vPrintFlush, _ok := model.Get("print-flush"); _ok && _vPrintFlush.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintFlush.Leaf); _xok {
			d.data.PrintFlush = &_x
			_vPrintFlush.MarkConsumed()
		}
	}
	if _vPrintUnchanged, _ok := model.Get("print-unchanged"); _ok && _vPrintUnchanged.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintUnchanged.Leaf); _xok {
			d.data.PrintUnchanged = &_x
			_vPrintUnchanged.MarkConsumed()
		}
	}
	if _vPrintColors, _ok := model.Get("print-colors"); _ok && _vPrintColors.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintColors.Leaf); _xok {
			d.data.PrintColors = &_x
			_vPrintColors.MarkConsumed()
		}
	}
	if _vPrintInventoryLists, _ok := model.Get("print-inventory_lists"); _ok && _vPrintInventoryLists.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintInventoryLists.Leaf); _xok {
			d.data.PrintInventoryLists = &_x
			_vPrintInventoryLists.MarkConsumed()
		}
	}
	return d, nil
}

func (d *V1Document) Data() *V1 {
	return &d.data
}

func (d *V1Document) Encode() ([]byte, error) {
	if d.data.Abbreviations != nil {
		tableNode := cst.EnsureChildTable(d.cstDoc.Root(), d.cstDoc.Root(), "abbreviations")
		if d.data.Abbreviations.ZettelIds != nil {
			if err := cst.SetAny(tableNode, "zettel-ids", *d.data.Abbreviations.ZettelIds); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
		if d.data.Abbreviations.MarklIds != nil {
			if err := cst.SetAny(tableNode, "shas", *d.data.Abbreviations.MarklIds); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	if d.data.PrintIncludeDescription != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-include-description", *d.data.PrintIncludeDescription); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintTime != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-time", *d.data.PrintTime); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintTagsAlways != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-etiketten-always", *d.data.PrintTagsAlways); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintEmptyShas != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-empty-shas", *d.data.PrintEmptyShas); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintIncludeTypes != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-include-typen", *d.data.PrintIncludeTypes); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintMatchedDormant != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-matched-dormant", *d.data.PrintMatchedDormant); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintShas != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-shas", *d.data.PrintShas); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintFlush != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-flush", *d.data.PrintFlush); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintUnchanged != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-unchanged", *d.data.PrintUnchanged); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintColors != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-colors", *d.data.PrintColors); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.PrintInventoryLists != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "print-inventory_lists", *d.data.PrintInventoryLists); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *V1Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *V1Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *V1Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *V1Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *V1Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeV1Into(data *V1, sub *cst.Value) error {
	if _vAbbreviations, _ok := sub.Get("abbreviations"); _ok && _vAbbreviations.Kind == cst.VTable {
		_vAbbreviations.MarkSeen()
		abbreviationsVal0 := &abbreviationsV1{}
		if _vAbbreviationsZettelIds, _ok := _vAbbreviations.Get("zettel-ids"); _ok && _vAbbreviationsZettelIds.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vAbbreviationsZettelIds.Leaf); _xok {
				abbreviationsVal0.ZettelIds = &_x
				_vAbbreviationsZettelIds.MarkConsumed()
			}
		}
		if _vAbbreviationsShas, _ok := _vAbbreviations.Get("shas"); _ok && _vAbbreviationsShas.Kind == cst.VLeaf {
			if _x, _xok := cst.ExtractBool(_vAbbreviationsShas.Leaf); _xok {
				abbreviationsVal0.MarklIds = &_x
				_vAbbreviationsShas.MarkConsumed()
			}
		}
		data.Abbreviations = abbreviationsVal0
	} else {
		abbreviationsVal0 := &abbreviationsV1{}
		_foundAbbreviations := false
		if _vZettelIds, _ok := sub.Get("zettel-ids"); _ok && _vZettelIds.Kind == cst.VLeaf {
			_foundAbbreviations = true
			if _x, _xok := cst.ExtractBool(_vZettelIds.Leaf); _xok {
				abbreviationsVal0.ZettelIds = &_x
				_vZettelIds.MarkConsumed()
			}
		}
		if _vShas, _ok := sub.Get("shas"); _ok && _vShas.Kind == cst.VLeaf {
			_foundAbbreviations = true
			if _x, _xok := cst.ExtractBool(_vShas.Leaf); _xok {
				abbreviationsVal0.MarklIds = &_x
				_vShas.MarkConsumed()
			}
		}
		if _foundAbbreviations {
			data.Abbreviations = abbreviationsVal0
		}
	}
	if _vPrintIncludeDescription, _ok := sub.Get("print-include-description"); _ok && _vPrintIncludeDescription.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintIncludeDescription.Leaf); _xok {
			data.PrintIncludeDescription = &_x
			_vPrintIncludeDescription.MarkConsumed()
		}
	}
	if _vPrintTime, _ok := sub.Get("print-time"); _ok && _vPrintTime.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintTime.Leaf); _xok {
			data.PrintTime = &_x
			_vPrintTime.MarkConsumed()
		}
	}
	if _vPrintEtikettenAlways, _ok := sub.Get("print-etiketten-always"); _ok && _vPrintEtikettenAlways.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintEtikettenAlways.Leaf); _xok {
			data.PrintTagsAlways = &_x
			_vPrintEtikettenAlways.MarkConsumed()
		}
	}
	if _vPrintEmptyShas, _ok := sub.Get("print-empty-shas"); _ok && _vPrintEmptyShas.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintEmptyShas.Leaf); _xok {
			data.PrintEmptyShas = &_x
			_vPrintEmptyShas.MarkConsumed()
		}
	}
	if _vPrintIncludeTypen, _ok := sub.Get("print-include-typen"); _ok && _vPrintIncludeTypen.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintIncludeTypen.Leaf); _xok {
			data.PrintIncludeTypes = &_x
			_vPrintIncludeTypen.MarkConsumed()
		}
	}
	if _vPrintMatchedDormant, _ok := sub.Get("print-matched-dormant"); _ok && _vPrintMatchedDormant.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintMatchedDormant.Leaf); _xok {
			data.PrintMatchedDormant = &_x
			_vPrintMatchedDormant.MarkConsumed()
		}
	}
	if _vPrintShas, _ok := sub.Get("print-shas"); _ok && _vPrintShas.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintShas.Leaf); _xok {
			data.PrintShas = &_x
			_vPrintShas.MarkConsumed()
		}
	}
	if _vPrintFlush, _ok := sub.Get("print-flush"); _ok && _vPrintFlush.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintFlush.Leaf); _xok {
			data.PrintFlush = &_x
			_vPrintFlush.MarkConsumed()
		}
	}
	if _vPrintUnchanged, _ok := sub.Get("print-unchanged"); _ok && _vPrintUnchanged.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintUnchanged.Leaf); _xok {
			data.PrintUnchanged = &_x
			_vPrintUnchanged.MarkConsumed()
		}
	}
	if _vPrintColors, _ok := sub.Get("print-colors"); _ok && _vPrintColors.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintColors.Leaf); _xok {
			data.PrintColors = &_x
			_vPrintColors.MarkConsumed()
		}
	}
	if _vPrintInventoryLists, _ok := sub.Get("print-inventory_lists"); _ok && _vPrintInventoryLists.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vPrintInventoryLists.Leaf); _xok {
			data.PrintInventoryLists = &_x
			_vPrintInventoryLists.MarkConsumed()
		}
	}
	return nil
}

func EncodeV1From(data *V1, doc *document.Document, container *cst.Node) error {
	if data.Abbreviations != nil {
		tableNode := cst.EnsureChildTable(doc.Root(), container, "abbreviations")
		if data.Abbreviations.ZettelIds != nil {
			if err := cst.SetAny(tableNode, "zettel-ids", *data.Abbreviations.ZettelIds); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
		if data.Abbreviations.MarklIds != nil {
			if err := cst.SetAny(tableNode, "shas", *data.Abbreviations.MarklIds); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	if data.PrintIncludeDescription != nil {
		if err := cst.SetAny(container, "print-include-description", *data.PrintIncludeDescription); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintTime != nil {
		if err := cst.SetAny(container, "print-time", *data.PrintTime); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintTagsAlways != nil {
		if err := cst.SetAny(container, "print-etiketten-always", *data.PrintTagsAlways); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintEmptyShas != nil {
		if err := cst.SetAny(container, "print-empty-shas", *data.PrintEmptyShas); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintIncludeTypes != nil {
		if err := cst.SetAny(container, "print-include-typen", *data.PrintIncludeTypes); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintMatchedDormant != nil {
		if err := cst.SetAny(container, "print-matched-dormant", *data.PrintMatchedDormant); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintShas != nil {
		if err := cst.SetAny(container, "print-shas", *data.PrintShas); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintFlush != nil {
		if err := cst.SetAny(container, "print-flush", *data.PrintFlush); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintUnchanged != nil {
		if err := cst.SetAny(container, "print-unchanged", *data.PrintUnchanged); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintColors != nil {
		if err := cst.SetAny(container, "print-colors", *data.PrintColors); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.PrintInventoryLists != nil {
		if err := cst.SetAny(container, "print-inventory_lists", *data.PrintInventoryLists); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}

type abbreviationsV1Document struct {
	data   abbreviationsV1
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeabbreviationsV1(input []byte) (*abbreviationsV1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &abbreviationsV1Document{
		cstDoc: doc,
		model:  model,
	}

	if _vZettelIds, _ok := model.Get("zettel-ids"); _ok && _vZettelIds.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vZettelIds.Leaf); _xok {
			d.data.ZettelIds = &_x
			_vZettelIds.MarkConsumed()
		}
	}
	if _vShas, _ok := model.Get("shas"); _ok && _vShas.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vShas.Leaf); _xok {
			d.data.MarklIds = &_x
			_vShas.MarkConsumed()
		}
	}
	return d, nil
}

func (d *abbreviationsV1Document) Data() *abbreviationsV1 {
	return &d.data
}

func (d *abbreviationsV1Document) Encode() ([]byte, error) {
	if d.data.ZettelIds != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "zettel-ids", *d.data.ZettelIds); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.MarklIds != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "shas", *d.data.MarklIds); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *abbreviationsV1Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *abbreviationsV1Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *abbreviationsV1Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *abbreviationsV1Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *abbreviationsV1Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeabbreviationsV1Into(data *abbreviationsV1, sub *cst.Value) error {
	if _vZettelIds, _ok := sub.Get("zettel-ids"); _ok && _vZettelIds.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vZettelIds.Leaf); _xok {
			data.ZettelIds = &_x
			_vZettelIds.MarkConsumed()
		}
	}
	if _vShas, _ok := sub.Get("shas"); _ok && _vShas.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractBool(_vShas.Leaf); _xok {
			data.MarklIds = &_x
			_vShas.MarkConsumed()
		}
	}
	return nil
}

func EncodeabbreviationsV1From(data *abbreviationsV1, doc *document.Document, container *cst.Node) error {
	if data.ZettelIds != nil {
		if err := cst.SetAny(container, "zettel-ids", *data.ZettelIds); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.MarklIds != nil {
		if err := cst.SetAny(container, "shas", *data.MarklIds); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
