#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 52
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 3

enum ts_symbol_identifiers {
  sym__sep = 1,
  anon_sym_CARET = 2,
  anon_sym_LBRACK = 3,
  anon_sym_COMMA = 4,
  anon_sym_RBRACK = 5,
  anon_sym_EQ = 6,
  anon_sym_BANG = 7,
  anon_sym_DASH = 8,
  anon_sym_SLASH = 9,
  anon_sym_COLON = 10,
  anon_sym_PLUS = 11,
  anon_sym_DOT = 12,
  anon_sym_QMARK = 13,
  sym_identifier = 14,
  sym_source_file = 15,
  sym__element = 16,
  sym_negation = 17,
  sym_group = 18,
  sym__group_item = 19,
  sym_group_negation = 20,
  sym_term = 21,
  sym__bare_term = 22,
  sym__predicate = 23,
  sym_exact = 24,
  sym_type_filter = 25,
  sym_dependent_tag = 26,
  sym_object_id = 27,
  sym_tag = 28,
  sym_sigil = 29,
  sym_genres = 30,
  sym_genre = 31,
  aux_sym_source_file_repeat1 = 32,
  aux_sym_group_repeat1 = 33,
  aux_sym_sigil_repeat1 = 34,
  aux_sym_genres_repeat1 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__sep] = "_sep",
  [anon_sym_CARET] = "^",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG] = "!",
  [anon_sym_DASH] = "-",
  [anon_sym_SLASH] = "/",
  [anon_sym_COLON] = ":",
  [anon_sym_PLUS] = "+",
  [anon_sym_DOT] = ".",
  [anon_sym_QMARK] = "\?",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym__element] = "_element",
  [sym_negation] = "negation",
  [sym_group] = "group",
  [sym__group_item] = "_group_item",
  [sym_group_negation] = "group_negation",
  [sym_term] = "term",
  [sym__bare_term] = "_bare_term",
  [sym__predicate] = "_predicate",
  [sym_exact] = "exact",
  [sym_type_filter] = "type_filter",
  [sym_dependent_tag] = "dependent_tag",
  [sym_object_id] = "object_id",
  [sym_tag] = "tag",
  [sym_sigil] = "sigil",
  [sym_genres] = "genres",
  [sym_genre] = "genre",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_group_repeat1] = "group_repeat1",
  [aux_sym_sigil_repeat1] = "sigil_repeat1",
  [aux_sym_genres_repeat1] = "genres_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__sep] = sym__sep,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym__element] = sym__element,
  [sym_negation] = sym_negation,
  [sym_group] = sym_group,
  [sym__group_item] = sym__group_item,
  [sym_group_negation] = sym_group_negation,
  [sym_term] = sym_term,
  [sym__bare_term] = sym__bare_term,
  [sym__predicate] = sym__predicate,
  [sym_exact] = sym_exact,
  [sym_type_filter] = sym_type_filter,
  [sym_dependent_tag] = sym_dependent_tag,
  [sym_object_id] = sym_object_id,
  [sym_tag] = sym_tag,
  [sym_sigil] = sym_sigil,
  [sym_genres] = sym_genres,
  [sym_genre] = sym_genre,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_group_repeat1] = aux_sym_group_repeat1,
  [aux_sym_sigil_repeat1] = aux_sym_sigil_repeat1,
  [aux_sym_genres_repeat1] = aux_sym_genres_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__sep] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__element] = {
    .visible = false,
    .named = true,
  },
  [sym_negation] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym__group_item] = {
    .visible = false,
    .named = true,
  },
  [sym_group_negation] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym__bare_term] = {
    .visible = false,
    .named = true,
  },
  [sym__predicate] = {
    .visible = false,
    .named = true,
  },
  [sym_exact] = {
    .visible = true,
    .named = true,
  },
  [sym_type_filter] = {
    .visible = true,
    .named = true,
  },
  [sym_dependent_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_object_id] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_sigil] = {
    .visible = true,
    .named = true,
  },
  [sym_genres] = {
    .visible = true,
    .named = true,
  },
  [sym_genre] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sigil_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_genres_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_left = 1,
  field_name = 2,
  field_right = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_name] = "name",
  [field_right] = "right",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_left, 0},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      ADVANCE_MAP(
        '!', 8,
        '+', 12,
        ',', 5,
        '-', 9,
        '.', 13,
        '/', 10,
        ':', 11,
        '=', 7,
        '?', 14,
        '[', 4,
        ']', 6,
        '^', 3,
        '\t', 2,
        ' ', 2,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(sym__sep);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(2);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__sep] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(50),
    [sym__element] = STATE(29),
    [sym_negation] = STATE(29),
    [sym_group] = STATE(29),
    [sym_term] = STATE(29),
    [sym__bare_term] = STATE(22),
    [sym__predicate] = STATE(9),
    [sym_exact] = STATE(9),
    [sym_type_filter] = STATE(9),
    [sym_dependent_tag] = STATE(9),
    [sym_object_id] = STATE(9),
    [sym_tag] = STATE(9),
    [sym_sigil] = STATE(22),
    [aux_sym_sigil_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_CARET] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DOT] = ACTIONS(17),
    [anon_sym_QMARK] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
  },
  [2] = {
    [sym__element] = STATE(37),
    [sym_negation] = STATE(37),
    [sym_group] = STATE(37),
    [sym_term] = STATE(37),
    [sym__bare_term] = STATE(22),
    [sym__predicate] = STATE(9),
    [sym_exact] = STATE(9),
    [sym_type_filter] = STATE(9),
    [sym_dependent_tag] = STATE(9),
    [sym_object_id] = STATE(9),
    [sym_tag] = STATE(9),
    [sym_sigil] = STATE(22),
    [aux_sym_sigil_repeat1] = STATE(12),
    [anon_sym_CARET] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DOT] = ACTIONS(17),
    [anon_sym_QMARK] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
  },
  [3] = {
    [sym__group_item] = STATE(31),
    [sym_group_negation] = STATE(31),
    [sym__bare_term] = STATE(31),
    [sym__predicate] = STATE(9),
    [sym_exact] = STATE(9),
    [sym_type_filter] = STATE(9),
    [sym_dependent_tag] = STATE(9),
    [sym_object_id] = STATE(9),
    [sym_tag] = STATE(9),
    [sym_sigil] = STATE(31),
    [aux_sym_sigil_repeat1] = STATE(12),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DOT] = ACTIONS(17),
    [anon_sym_QMARK] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
  },
  [4] = {
    [sym_group] = STATE(40),
    [sym_term] = STATE(40),
    [sym__bare_term] = STATE(22),
    [sym__predicate] = STATE(9),
    [sym_exact] = STATE(9),
    [sym_type_filter] = STATE(9),
    [sym_dependent_tag] = STATE(9),
    [sym_object_id] = STATE(9),
    [sym_tag] = STATE(9),
    [sym_sigil] = STATE(22),
    [aux_sym_sigil_repeat1] = STATE(12),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DOT] = ACTIONS(17),
    [anon_sym_QMARK] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
  },
  [5] = {
    [sym__group_item] = STATE(43),
    [sym_group_negation] = STATE(43),
    [sym__bare_term] = STATE(43),
    [sym__predicate] = STATE(9),
    [sym_exact] = STATE(9),
    [sym_type_filter] = STATE(9),
    [sym_dependent_tag] = STATE(9),
    [sym_object_id] = STATE(9),
    [sym_tag] = STATE(9),
    [sym_sigil] = STATE(43),
    [aux_sym_sigil_repeat1] = STATE(12),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(17),
    [anon_sym_PLUS] = ACTIONS(17),
    [anon_sym_DOT] = ACTIONS(17),
    [anon_sym_QMARK] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(9), 1,
      anon_sym_EQ,
    ACTIONS(11), 1,
      anon_sym_BANG,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(15), 1,
      anon_sym_SLASH,
    ACTIONS(19), 1,
      sym_identifier,
    STATE(12), 1,
      aux_sym_sigil_repeat1,
    STATE(38), 2,
      sym__bare_term,
      sym_sigil,
    ACTIONS(17), 4,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_QMARK,
    STATE(9), 6,
      sym__predicate,
      sym_exact,
      sym_type_filter,
      sym_dependent_tag,
      sym_object_id,
      sym_tag,
  [37] = 7,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(12), 1,
      aux_sym_sigil_repeat1,
    STATE(20), 1,
      sym_sigil,
    STATE(26), 1,
      sym_genre,
    STATE(45), 1,
      sym_genres,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      sym__sep,
    ACTIONS(17), 4,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_QMARK,
  [63] = 7,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(12), 1,
      aux_sym_sigil_repeat1,
    STATE(23), 1,
      sym_sigil,
    STATE(26), 1,
      sym_genre,
    STATE(39), 1,
      sym_genres,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      sym__sep,
    ACTIONS(17), 4,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_QMARK,
  [89] = 4,
    STATE(12), 1,
      aux_sym_sigil_repeat1,
    STATE(21), 1,
      sym_sigil,
    ACTIONS(17), 4,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_QMARK,
    ACTIONS(31), 5,
      ts_builtin_sym_end,
      sym__sep,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_identifier,
  [109] = 7,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(12), 1,
      aux_sym_sigil_repeat1,
    STATE(24), 1,
      sym_sigil,
    STATE(26), 1,
      sym_genre,
    STATE(44), 1,
      sym_genres,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      sym__sep,
    ACTIONS(17), 4,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_QMARK,
  [135] = 3,
    STATE(11), 1,
      aux_sym_sigil_repeat1,
    ACTIONS(37), 4,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_QMARK,
    ACTIONS(35), 5,
      ts_builtin_sym_end,
      sym__sep,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_identifier,
  [152] = 3,
    STATE(11), 1,
      aux_sym_sigil_repeat1,
    ACTIONS(42), 4,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_QMARK,
    ACTIONS(40), 5,
      ts_builtin_sym_end,
      sym__sep,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_identifier,
  [169] = 2,
    ACTIONS(46), 1,
      anon_sym_SLASH,
    ACTIONS(44), 9,
      ts_builtin_sym_end,
      sym__sep,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_QMARK,
      sym_identifier,
  [184] = 1,
    ACTIONS(48), 9,
      ts_builtin_sym_end,
      sym__sep,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_QMARK,
      sym_identifier,
  [196] = 1,
    ACTIONS(50), 9,
      ts_builtin_sym_end,
      sym__sep,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_QMARK,
      sym_identifier,
  [208] = 1,
    ACTIONS(44), 9,
      ts_builtin_sym_end,
      sym__sep,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_QMARK,
      sym_identifier,
  [220] = 1,
    ACTIONS(52), 9,
      ts_builtin_sym_end,
      sym__sep,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_QMARK,
      sym_identifier,
  [232] = 1,
    ACTIONS(54), 9,
      ts_builtin_sym_end,
      sym__sep,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_QMARK,
      sym_identifier,
  [244] = 1,
    ACTIONS(56), 9,
      ts_builtin_sym_end,
      sym__sep,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_COLON,
      anon_sym_PLUS,
      anon_sym_DOT,
      anon_sym_QMARK,
      sym_identifier,
  [256] = 4,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(26), 1,
      sym_genre,
    STATE(46), 1,
      sym_genres,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      sym__sep,
  [270] = 1,
    ACTIONS(60), 5,
      ts_builtin_sym_end,
      sym__sep,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_identifier,
  [278] = 4,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(26), 1,
      sym_genre,
    STATE(41), 1,
      sym_genres,
    ACTIONS(62), 2,
      ts_builtin_sym_end,
      sym__sep,
  [292] = 4,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(26), 1,
      sym_genre,
    STATE(44), 1,
      sym_genres,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      sym__sep,
  [306] = 4,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(26), 1,
      sym_genre,
    STATE(45), 1,
      sym_genres,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      sym__sep,
  [320] = 3,
    ACTIONS(11), 1,
      anon_sym_BANG,
    ACTIONS(64), 1,
      sym_identifier,
    STATE(15), 2,
      sym_type_filter,
      sym_tag,
  [331] = 3,
    ACTIONS(68), 1,
      anon_sym_COMMA,
    STATE(27), 1,
      aux_sym_genres_repeat1,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      sym__sep,
  [342] = 3,
    ACTIONS(68), 1,
      anon_sym_COMMA,
    STATE(28), 1,
      aux_sym_genres_repeat1,
    ACTIONS(70), 2,
      ts_builtin_sym_end,
      sym__sep,
  [353] = 3,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    STATE(28), 1,
      aux_sym_genres_repeat1,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      sym__sep,
  [364] = 3,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 1,
      sym__sep,
    STATE(34), 1,
      aux_sym_source_file_repeat1,
  [374] = 3,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(83), 1,
      anon_sym_RBRACK,
    STATE(33), 1,
      aux_sym_group_repeat1,
  [384] = 3,
    ACTIONS(81), 1,
      anon_sym_COMMA,
    ACTIONS(85), 1,
      anon_sym_RBRACK,
    STATE(30), 1,
      aux_sym_group_repeat1,
  [394] = 3,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 1,
      sym__sep,
    STATE(32), 1,
      aux_sym_source_file_repeat1,
  [404] = 3,
    ACTIONS(92), 1,
      anon_sym_COMMA,
    ACTIONS(95), 1,
      anon_sym_RBRACK,
    STATE(33), 1,
      aux_sym_group_repeat1,
  [414] = 3,
    ACTIONS(79), 1,
      sym__sep,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    STATE(32), 1,
      aux_sym_source_file_repeat1,
  [424] = 1,
    ACTIONS(99), 3,
      ts_builtin_sym_end,
      sym__sep,
      anon_sym_COMMA,
  [430] = 1,
    ACTIONS(72), 3,
      ts_builtin_sym_end,
      sym__sep,
      anon_sym_COMMA,
  [436] = 1,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      sym__sep,
  [441] = 1,
    ACTIONS(101), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [446] = 1,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      sym__sep,
  [451] = 1,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      sym__sep,
  [456] = 1,
    ACTIONS(105), 2,
      ts_builtin_sym_end,
      sym__sep,
  [461] = 2,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(36), 1,
      sym_genre,
  [468] = 1,
    ACTIONS(95), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [473] = 1,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      sym__sep,
  [478] = 1,
    ACTIONS(58), 2,
      ts_builtin_sym_end,
      sym__sep,
  [483] = 1,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      sym__sep,
  [488] = 1,
    ACTIONS(109), 1,
      sym_identifier,
  [492] = 1,
    ACTIONS(111), 1,
      sym_identifier,
  [496] = 1,
    ACTIONS(113), 1,
      sym_identifier,
  [500] = 1,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
  [504] = 1,
    ACTIONS(117), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
  [SMALL_STATE(7)] = 37,
  [SMALL_STATE(8)] = 63,
  [SMALL_STATE(9)] = 89,
  [SMALL_STATE(10)] = 109,
  [SMALL_STATE(11)] = 135,
  [SMALL_STATE(12)] = 152,
  [SMALL_STATE(13)] = 169,
  [SMALL_STATE(14)] = 184,
  [SMALL_STATE(15)] = 196,
  [SMALL_STATE(16)] = 208,
  [SMALL_STATE(17)] = 220,
  [SMALL_STATE(18)] = 232,
  [SMALL_STATE(19)] = 244,
  [SMALL_STATE(20)] = 256,
  [SMALL_STATE(21)] = 270,
  [SMALL_STATE(22)] = 278,
  [SMALL_STATE(23)] = 292,
  [SMALL_STATE(24)] = 306,
  [SMALL_STATE(25)] = 320,
  [SMALL_STATE(26)] = 331,
  [SMALL_STATE(27)] = 342,
  [SMALL_STATE(28)] = 353,
  [SMALL_STATE(29)] = 364,
  [SMALL_STATE(30)] = 374,
  [SMALL_STATE(31)] = 384,
  [SMALL_STATE(32)] = 394,
  [SMALL_STATE(33)] = 404,
  [SMALL_STATE(34)] = 414,
  [SMALL_STATE(35)] = 424,
  [SMALL_STATE(36)] = 430,
  [SMALL_STATE(37)] = 436,
  [SMALL_STATE(38)] = 441,
  [SMALL_STATE(39)] = 446,
  [SMALL_STATE(40)] = 451,
  [SMALL_STATE(41)] = 456,
  [SMALL_STATE(42)] = 461,
  [SMALL_STATE(43)] = 468,
  [SMALL_STATE(44)] = 473,
  [SMALL_STATE(45)] = 478,
  [SMALL_STATE(46)] = 483,
  [SMALL_STATE(47)] = 488,
  [SMALL_STATE(48)] = 492,
  [SMALL_STATE(49)] = 496,
  [SMALL_STATE(50)] = 500,
  [SMALL_STATE(51)] = 504,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 4, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bare_term, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 3, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sigil_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sigil_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sigil, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_filter, 2, 0, 1),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exact, 2, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dependent_tag, 2, 0, 1),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_id, 2, 0, 1),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_id, 3, 0, 2),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 5, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__bare_term, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_genres, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_genres, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_genres_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_genres_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_group_repeat1, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_genre, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group_negation, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_negation, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 6, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [115] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_doddish(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
