// Code generated by tommy 0.5.0 (47364f2); DO NOT EDIT.

package file_extensions

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TOMLV1Document struct {
	data   TOMLV1
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTOMLV1(input []byte) (*TOMLV1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	return decodeTOMLV1Parsed(doc)
}

// DecodeTOMLV1Strict is DecodeTOMLV1 for input that must be exactly what it
// claims: it returns a *cst.SyntaxError when input is not well-formed TOML and
// *cst.TypeError values when a key's TOML type does not match its field, where
// DecodeTOMLV1 would decode leniently. Keys no field claims are not errors; they
// stay in Undecoded.
func DecodeTOMLV1Strict(input []byte) (*TOMLV1Document, error) {
	doc, err := document.ParseStrict(input)
	if err != nil {
		return nil, err
	}
	d, err := decodeTOMLV1Parsed(doc)
	if err != nil {
		return nil, err
	}
	if err := d.model.TypeErrors(); err != nil {
		return nil, err
	}
	return d, nil
}

func decodeTOMLV1Parsed(doc *document.Document) (*TOMLV1Document, error) {
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TOMLV1Document{
		cstDoc: doc,
		model:  model,
	}

	if _vConfig, _ok := model.Field("config"); _ok && _vConfig.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vConfig.Leaf); _xok {
			d.data.Config = &_x
			_vConfig.MarkConsumedString()
		}
	}
	if _vConflict, _ok := model.Field("conflict"); _ok && _vConflict.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vConflict.Leaf); _xok {
			d.data.Conflict = &_x
			_vConflict.MarkConsumedString()
		}
	}
	if _vLockfile, _ok := model.Field("lockfile"); _ok && _vLockfile.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vLockfile.Leaf); _xok {
			d.data.Lockfile = &_x
			_vLockfile.MarkConsumedString()
		}
	}
	if _vOrganize, _ok := model.Field("organize"); _ok && _vOrganize.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vOrganize.Leaf); _xok {
			d.data.Organize = &_x
			_vOrganize.MarkConsumedString()
		}
	}
	if _vRepo, _ok := model.Field("repo"); _ok && _vRepo.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vRepo.Leaf); _xok {
			d.data.Repo = &_x
			_vRepo.MarkConsumedString()
		}
	}
	if _vTag, _ok := model.Field("tag"); _ok && _vTag.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTag.Leaf); _xok {
			d.data.Tag = &_x
			_vTag.MarkConsumedString()
		}
	}
	if _vType, _ok := model.Field("type"); _ok && _vType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vType.Leaf); _xok {
			d.data.Type = &_x
			_vType.MarkConsumedString()
		}
	}
	if _vZettel, _ok := model.Field("zettel"); _ok && _vZettel.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vZettel.Leaf); _xok {
			d.data.Zettel = &_x
			_vZettel.MarkConsumedString()
		}
	}
	return d, nil
}

func (d *TOMLV1Document) Data() *TOMLV1 {
	return &d.data
}

func (d *TOMLV1Document) Encode() ([]byte, error) {
	if d.data.Config != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "config", *d.data.Config); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Conflict != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "conflict", *d.data.Conflict); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Lockfile != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "lockfile", *d.data.Lockfile); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Organize != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "organize", *d.data.Organize); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Repo != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "repo", *d.data.Repo); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Tag != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "tag", *d.data.Tag); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Type != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "type", *d.data.Type); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Zettel != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "zettel", *d.data.Zettel); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TOMLV1Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TOMLV1Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TOMLV1Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TOMLV1Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TOMLV1Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTOMLV1Into(data *TOMLV1, sub *cst.Value) error {
	if _vConfig, _ok := sub.Field("config"); _ok && _vConfig.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vConfig.Leaf); _xok {
			data.Config = &_x
			_vConfig.MarkConsumedString()
		}
	}
	if _vConflict, _ok := sub.Field("conflict"); _ok && _vConflict.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vConflict.Leaf); _xok {
			data.Conflict = &_x
			_vConflict.MarkConsumedString()
		}
	}
	if _vLockfile, _ok := sub.Field("lockfile"); _ok && _vLockfile.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vLockfile.Leaf); _xok {
			data.Lockfile = &_x
			_vLockfile.MarkConsumedString()
		}
	}
	if _vOrganize, _ok := sub.Field("organize"); _ok && _vOrganize.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vOrganize.Leaf); _xok {
			data.Organize = &_x
			_vOrganize.MarkConsumedString()
		}
	}
	if _vRepo, _ok := sub.Field("repo"); _ok && _vRepo.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vRepo.Leaf); _xok {
			data.Repo = &_x
			_vRepo.MarkConsumedString()
		}
	}
	if _vTag, _ok := sub.Field("tag"); _ok && _vTag.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTag.Leaf); _xok {
			data.Tag = &_x
			_vTag.MarkConsumedString()
		}
	}
	if _vType, _ok := sub.Field("type"); _ok && _vType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vType.Leaf); _xok {
			data.Type = &_x
			_vType.MarkConsumedString()
		}
	}
	if _vZettel, _ok := sub.Field("zettel"); _ok && _vZettel.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vZettel.Leaf); _xok {
			data.Zettel = &_x
			_vZettel.MarkConsumedString()
		}
	}
	return nil
}

func EncodeTOMLV1From(data *TOMLV1, doc *document.Document, container *cst.Node) error {
	if data.Config != nil {
		if err := cst.SetAny(container, "config", *data.Config); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Conflict != nil {
		if err := cst.SetAny(container, "conflict", *data.Conflict); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Lockfile != nil {
		if err := cst.SetAny(container, "lockfile", *data.Lockfile); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Organize != nil {
		if err := cst.SetAny(container, "organize", *data.Organize); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Repo != nil {
		if err := cst.SetAny(container, "repo", *data.Repo); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Tag != nil {
		if err := cst.SetAny(container, "tag", *data.Tag); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Type != nil {
		if err := cst.SetAny(container, "type", *data.Type); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Zettel != nil {
		if err := cst.SetAny(container, "zettel", *data.Zettel); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
