// Code generated by tommy 0.4.4 (054f61d); DO NOT EDIT.

package file_extensions

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TOMLV0Document struct {
	data   TOMLV0
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTOMLV0(input []byte) (*TOMLV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TOMLV0Document{
		cstDoc: doc,
		model:  model,
	}

	if _vOrganize, _ok := model.Get("organize"); _ok && _vOrganize.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vOrganize.Leaf); _xok {
			d.data.Organize = &_x
			_vOrganize.MarkConsumed()
		}
	}
	if _vKasten, _ok := model.Get("kasten"); _ok && _vKasten.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vKasten.Leaf); _xok {
			d.data.Repo = &_x
			_vKasten.MarkConsumed()
		}
	}
	if _vEtikett, _ok := model.Get("etikett"); _ok && _vEtikett.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vEtikett.Leaf); _xok {
			d.data.Tag = &_x
			_vEtikett.MarkConsumed()
		}
	}
	if _vTyp, _ok := model.Get("typ"); _ok && _vTyp.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTyp.Leaf); _xok {
			d.data.Type = &_x
			_vTyp.MarkConsumed()
		}
	}
	if _vZettel, _ok := model.Get("zettel"); _ok && _vZettel.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vZettel.Leaf); _xok {
			d.data.Zettel = &_x
			_vZettel.MarkConsumed()
		}
	}
	return d, nil
}

func (d *TOMLV0Document) Data() *TOMLV0 {
	return &d.data
}

func (d *TOMLV0Document) Encode() ([]byte, error) {
	if d.data.Organize != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "organize", *d.data.Organize); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Repo != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "kasten", *d.data.Repo); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Tag != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "etikett", *d.data.Tag); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Type != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "typ", *d.data.Type); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.Zettel != nil {
		if err := cst.SetAny(d.cstDoc.Root(), "zettel", *d.data.Zettel); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TOMLV0Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TOMLV0Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TOMLV0Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TOMLV0Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TOMLV0Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTOMLV0Into(data *TOMLV0, sub *cst.Value) error {
	if _vOrganize, _ok := sub.Get("organize"); _ok && _vOrganize.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vOrganize.Leaf); _xok {
			data.Organize = &_x
			_vOrganize.MarkConsumed()
		}
	}
	if _vKasten, _ok := sub.Get("kasten"); _ok && _vKasten.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vKasten.Leaf); _xok {
			data.Repo = &_x
			_vKasten.MarkConsumed()
		}
	}
	if _vEtikett, _ok := sub.Get("etikett"); _ok && _vEtikett.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vEtikett.Leaf); _xok {
			data.Tag = &_x
			_vEtikett.MarkConsumed()
		}
	}
	if _vTyp, _ok := sub.Get("typ"); _ok && _vTyp.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vTyp.Leaf); _xok {
			data.Type = &_x
			_vTyp.MarkConsumed()
		}
	}
	if _vZettel, _ok := sub.Get("zettel"); _ok && _vZettel.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vZettel.Leaf); _xok {
			data.Zettel = &_x
			_vZettel.MarkConsumed()
		}
	}
	return nil
}

func EncodeTOMLV0From(data *TOMLV0, doc *document.Document, container *cst.Node) error {
	if data.Organize != nil {
		if err := cst.SetAny(container, "organize", *data.Organize); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Repo != nil {
		if err := cst.SetAny(container, "kasten", *data.Repo); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Tag != nil {
		if err := cst.SetAny(container, "etikett", *data.Tag); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Type != nil {
		if err := cst.SetAny(container, "typ", *data.Type); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.Zettel != nil {
		if err := cst.SetAny(container, "zettel", *data.Zettel); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
