// Code generated by tommy 0.4.5 (031c877); DO NOT EDIT.

package tag_blobs

import (
	"fmt"
	"strings"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlV1Document struct {
	data   TomlV1
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlV1(input []byte) (*TomlV1Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlV1Document{
		cstDoc: doc,
		model:  model,
	}

	if _vFilter, _ok := model.Get("filter"); _ok && _vFilter.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vFilter.Leaf); _xok {
			d.data.Filter = _x
			_vFilter.MarkConsumed()
		}
	}
	return d, nil
}

func (d *TomlV1Document) Data() *TomlV1 {
	return &d.data
}

func (d *TomlV1Document) Encode() ([]byte, error) {
	if d.data.Filter != "" || cst.HasValue(d.cstDoc.Root(), "filter") {
		if err := cst.SetAny(d.cstDoc.Root(), "filter", d.data.Filter); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlV1Document) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlV1Document) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlV1Document) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlV1Document) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlV1Document) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlV1Into(data *TomlV1, sub *cst.Value) error {
	if _vFilter, _ok := sub.Get("filter"); _ok && _vFilter.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vFilter.Leaf); _xok {
			data.Filter = _x
			_vFilter.MarkConsumed()
		}
	}
	return nil
}

func EncodeTomlV1From(data *TomlV1, doc *document.Document, container *cst.Node) error {
	if data.Filter != "" || cst.HasValue(container, "filter") {
		if err := cst.SetAny(container, "filter", data.Filter); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
