// Code generated by "stringer -type=Binary"; DO NOT EDIT.

package key_bytes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[ContentLength-67]
	_ = x[Sigil-83]
	_ = x[Blob-65]
	_ = x[RepoPubKey-80]
	_ = x[RepoSig-113]
	_ = x[Description-66]
	_ = x[Tag-69]
	_ = x[Genre-71]
	_ = x[ObjectId-75]
	_ = x[Comment-107]
	_ = x[Tai-84]
	_ = x[Type-116]
	_ = x[References-82]
	_ = x[ReferenceAliases-114]
	_ = x[BlobReferences-98]
	_ = x[SigParentMetadataParentObjectId-77]
	_ = x[DigestMetadataParentObjectId-115]
	_ = x[DigestMetadataWithoutTai-110]
	_ = x[DigestMetadata-109]
	_ = x[ExternalObjectId-101]
	_ = x[Field-70]
	_ = x[CacheDormant-97]
	_ = x[CacheTagImplicit-73]
	_ = x[CacheTags-120]
	_ = x[CacheTags2-121]
}

const _Binary_name = "UnknownBlobDescriptionContentLengthTagFieldGenreCacheTagImplicitObjectIdSigParentMetadataParentObjectIdRepoPubKeyReferencesSigilTaiCacheDormantBlobReferencesExternalObjectIdCommentDigestMetadataDigestMetadataWithoutTaiRepoSigReferenceAliasesDigestMetadataParentObjectIdTypeCacheTagsCacheTags2"

var _Binary_map = map[Binary]string{
	0:   _Binary_name[0:7],
	65:  _Binary_name[7:11],
	66:  _Binary_name[11:22],
	67:  _Binary_name[22:35],
	69:  _Binary_name[35:38],
	70:  _Binary_name[38:43],
	71:  _Binary_name[43:48],
	73:  _Binary_name[48:64],
	75:  _Binary_name[64:72],
	77:  _Binary_name[72:103],
	80:  _Binary_name[103:113],
	82:  _Binary_name[113:123],
	83:  _Binary_name[123:128],
	84:  _Binary_name[128:131],
	97:  _Binary_name[131:143],
	98:  _Binary_name[143:157],
	101: _Binary_name[157:173],
	107: _Binary_name[173:180],
	109: _Binary_name[180:194],
	110: _Binary_name[194:218],
	113: _Binary_name[218:225],
	114: _Binary_name[225:241],
	115: _Binary_name[241:269],
	116: _Binary_name[269:273],
	120: _Binary_name[273:282],
	121: _Binary_name[282:292],
}

func (i Binary) String() string {
	if str, ok := _Binary_map[i]; ok {
		return str
	}
	return "Binary(" + strconv.FormatInt(int64(i), 10) + ")"
}
