// Code generated by tommy 0.5.0 (47364f2); DO NOT EDIT.

package options_tools

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type OptionsDocument struct {
	data   Options
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeOptions(input []byte) (*OptionsDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	return decodeOptionsParsed(doc)
}

// DecodeOptionsStrict is DecodeOptions for input that must be exactly what it
// claims: it returns a *cst.SyntaxError when input is not well-formed TOML and
// *cst.TypeError values when a key's TOML type does not match its field, where
// DecodeOptions would decode leniently. Keys no field claims are not errors; they
// stay in Undecoded.
func DecodeOptionsStrict(input []byte) (*OptionsDocument, error) {
	doc, err := document.ParseStrict(input)
	if err != nil {
		return nil, err
	}
	d, err := decodeOptionsParsed(doc)
	if err != nil {
		return nil, err
	}
	if err := d.model.TypeErrors(); err != nil {
		return nil, err
	}
	return d, nil
}

func decodeOptionsParsed(doc *document.Document) (*OptionsDocument, error) {
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &OptionsDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vMerge, _ok := model.Field("merge"); _ok && _vMerge.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vMerge.Leaf); _xok {
			d.data.Merge = _x
			if d.data.Merge == nil {
				d.data.Merge = []string{}
			}
			_vMerge.MarkConsumed()
		}
	}
	return d, nil
}

func (d *OptionsDocument) Data() *Options {
	return &d.data
}

func (d *OptionsDocument) Encode() ([]byte, error) {
	{
		if d.data.Merge != nil {
			if err := cst.SetAny(d.cstDoc.Root(), "merge", d.data.Merge); err != nil {
				return nil, fmt.Errorf("%w", err)
			}
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *OptionsDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *OptionsDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *OptionsDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *OptionsDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *OptionsDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeOptionsInto(data *Options, sub *cst.Value) error {
	if _vMerge, _ok := sub.Field("merge"); _ok && _vMerge.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractStringSlice(_vMerge.Leaf); _xok {
			data.Merge = _x
			if data.Merge == nil {
				data.Merge = []string{}
			}
			_vMerge.MarkConsumed()
		}
	}
	return nil
}

func EncodeOptionsFrom(data *Options, doc *document.Document, container *cst.Node) error {
	{
		if data.Merge != nil {
			if err := cst.SetAny(container, "merge", data.Merge); err != nil {
				return fmt.Errorf("%w", err)
			}
		}
	}
	return nil
}
