// Code generated by tommy 0.5.0 (a5d3780); DO NOT EDIT.

package genesis_config_blobs

import (
	"fmt"
	"strings"

	"code.linenisgreat.com/dodder/go/internal/alfa/store_version"
	"code.linenisgreat.com/tommy/pkg/cst"
	"code.linenisgreat.com/tommy/pkg/document"
)

var (
	_ = fmt.Errorf
	_ cst.NodeKind
	_ = strings.Contains
)

type TomlV2PrivateDocument struct {
	data   TomlV2Private
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlV2Private(input []byte) (*TomlV2PrivateDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlV2PrivateDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vPrivateKey, _ok := model.Get("private-key"); _ok && _vPrivateKey.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPrivateKey.Leaf); _xok {
			if err := d.data.PrivateKey.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("private-key: %w", err)
			}
			_vPrivateKey.MarkConsumed()
		}
	}
	if _vStoreVersion, _ok := model.Get("store-version"); _ok && _vStoreVersion.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractInt(_vStoreVersion.Leaf); _xok {
			d.data.StoreVersion = store_version.Version(_x)
			_vStoreVersion.MarkConsumed()
		}
	}
	if _vId, _ok := model.Get("id"); _ok && _vId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vId.Leaf); _xok {
			if err := d.data.RepoId.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("id: %w", err)
			}
			_vId.MarkConsumed()
		}
	}
	if _vInventoryListType, _ok := model.Get("inventory_list-type"); _ok && _vInventoryListType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vInventoryListType.Leaf); _xok {
			d.data.InventoryListType = _x
			_vInventoryListType.MarkConsumed()
		}
	}
	if _vObjectSigType, _ok := model.Get("object-sig-type"); _ok && _vObjectSigType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vObjectSigType.Leaf); _xok {
			d.data.ObjectSigType = _x
			_vObjectSigType.MarkConsumed()
		}
	}
	return d, nil
}

func (d *TomlV2PrivateDocument) Data() *TomlV2Private {
	return &d.data
}

func (d *TomlV2PrivateDocument) Encode() ([]byte, error) {
	{
		v, err := d.data.PrivateKey.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("private-key: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "private-key", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.StoreVersion != store_version.Version(0) || cst.HasValue(d.cstDoc.Root(), "store-version") {
		if err := cst.SetAny(d.cstDoc.Root(), "store-version", int(d.data.StoreVersion)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.RepoId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("id: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "id", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.InventoryListType != "" || cst.HasValue(d.cstDoc.Root(), "inventory_list-type") {
		if err := cst.SetAny(d.cstDoc.Root(), "inventory_list-type", d.data.InventoryListType); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.ObjectSigType != "" || cst.HasValue(d.cstDoc.Root(), "object-sig-type") {
		if err := cst.SetAny(d.cstDoc.Root(), "object-sig-type", d.data.ObjectSigType); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlV2PrivateDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlV2PrivateDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlV2PrivateDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlV2PrivateDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlV2PrivateDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlV2PrivateInto(data *TomlV2Private, sub *cst.Value) error {
	if _vPrivateKey, _ok := sub.Get("private-key"); _ok && _vPrivateKey.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPrivateKey.Leaf); _xok {
			if err := data.PrivateKey.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("private-key: %w", err)
			}
			_vPrivateKey.MarkConsumed()
		}
	}
	if _vStoreVersion, _ok := sub.Get("store-version"); _ok && _vStoreVersion.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractInt(_vStoreVersion.Leaf); _xok {
			data.StoreVersion = store_version.Version(_x)
			_vStoreVersion.MarkConsumed()
		}
	}
	if _vId, _ok := sub.Get("id"); _ok && _vId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vId.Leaf); _xok {
			if err := data.RepoId.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("id: %w", err)
			}
			_vId.MarkConsumed()
		}
	}
	if _vInventoryListType, _ok := sub.Get("inventory_list-type"); _ok && _vInventoryListType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vInventoryListType.Leaf); _xok {
			data.InventoryListType = _x
			_vInventoryListType.MarkConsumed()
		}
	}
	if _vObjectSigType, _ok := sub.Get("object-sig-type"); _ok && _vObjectSigType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vObjectSigType.Leaf); _xok {
			data.ObjectSigType = _x
			_vObjectSigType.MarkConsumed()
		}
	}
	return nil
}

func EncodeTomlV2PrivateFrom(data *TomlV2Private, doc *document.Document, container *cst.Node) error {
	{
		v, err := data.PrivateKey.MarshalText()
		if err != nil {
			return fmt.Errorf("private-key: %w", err)
		}
		if err := cst.SetAny(container, "private-key", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.StoreVersion != store_version.Version(0) || cst.HasValue(container, "store-version") {
		if err := cst.SetAny(container, "store-version", int(data.StoreVersion)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.RepoId.MarshalText()
		if err != nil {
			return fmt.Errorf("id: %w", err)
		}
		if err := cst.SetAny(container, "id", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.InventoryListType != "" || cst.HasValue(container, "inventory_list-type") {
		if err := cst.SetAny(container, "inventory_list-type", data.InventoryListType); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.ObjectSigType != "" || cst.HasValue(container, "object-sig-type") {
		if err := cst.SetAny(container, "object-sig-type", data.ObjectSigType); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}

type TomlV2PublicDocument struct {
	data   TomlV2Public
	cstDoc *document.Document
	model  *cst.Value
}

func DecodeTomlV2Public(input []byte) (*TomlV2PublicDocument, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}
	model, err := cst.Decompose(doc.Root())
	if err != nil {
		return nil, err
	}

	d := &TomlV2PublicDocument{
		cstDoc: doc,
		model:  model,
	}

	if _vPublicKey, _ok := model.Get("public-key"); _ok && _vPublicKey.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPublicKey.Leaf); _xok {
			if err := d.data.PublicKey.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("public-key: %w", err)
			}
			_vPublicKey.MarkConsumed()
		}
	}
	if _vStoreVersion, _ok := model.Get("store-version"); _ok && _vStoreVersion.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractInt(_vStoreVersion.Leaf); _xok {
			d.data.StoreVersion = store_version.Version(_x)
			_vStoreVersion.MarkConsumed()
		}
	}
	if _vId, _ok := model.Get("id"); _ok && _vId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vId.Leaf); _xok {
			if err := d.data.RepoId.UnmarshalText([]byte(_x)); err != nil {
				return nil, fmt.Errorf("id: %w", err)
			}
			_vId.MarkConsumed()
		}
	}
	if _vInventoryListType, _ok := model.Get("inventory_list-type"); _ok && _vInventoryListType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vInventoryListType.Leaf); _xok {
			d.data.InventoryListType = _x
			_vInventoryListType.MarkConsumed()
		}
	}
	if _vObjectSigType, _ok := model.Get("object-sig-type"); _ok && _vObjectSigType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vObjectSigType.Leaf); _xok {
			d.data.ObjectSigType = _x
			_vObjectSigType.MarkConsumed()
		}
	}
	return d, nil
}

func (d *TomlV2PublicDocument) Data() *TomlV2Public {
	return &d.data
}

func (d *TomlV2PublicDocument) Encode() ([]byte, error) {
	{
		v, err := d.data.PublicKey.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("public-key: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "public-key", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.StoreVersion != store_version.Version(0) || cst.HasValue(d.cstDoc.Root(), "store-version") {
		if err := cst.SetAny(d.cstDoc.Root(), "store-version", int(d.data.StoreVersion)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	{
		v, err := d.data.RepoId.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("id: %w", err)
		}
		if err := cst.SetAny(d.cstDoc.Root(), "id", string(v)); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.InventoryListType != "" || cst.HasValue(d.cstDoc.Root(), "inventory_list-type") {
		if err := cst.SetAny(d.cstDoc.Root(), "inventory_list-type", d.data.InventoryListType); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	if d.data.ObjectSigType != "" || cst.HasValue(d.cstDoc.Root(), "object-sig-type") {
		if err := cst.SetAny(d.cstDoc.Root(), "object-sig-type", d.data.ObjectSigType); err != nil {
			return nil, fmt.Errorf("%w", err)
		}
	}
	return d.cstDoc.Bytes(), nil
}

func (d *TomlV2PublicDocument) Undecoded() []string {
	if d.model == nil {
		return nil
	}
	return d.model.Undecoded()
}

func (d *TomlV2PublicDocument) Comment(key string) string {
	return d.cstDoc.GetComment(key)
}

func (d *TomlV2PublicDocument) SetComment(key, comment string) {
	d.cstDoc.SetComment(key, comment)
}

func (d *TomlV2PublicDocument) InlineComment(key string) string {
	return d.cstDoc.GetInlineComment(key)
}

func (d *TomlV2PublicDocument) SetInlineComment(key, comment string) {
	d.cstDoc.SetInlineComment(key, comment)
}

func DecodeTomlV2PublicInto(data *TomlV2Public, sub *cst.Value) error {
	if _vPublicKey, _ok := sub.Get("public-key"); _ok && _vPublicKey.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vPublicKey.Leaf); _xok {
			if err := data.PublicKey.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("public-key: %w", err)
			}
			_vPublicKey.MarkConsumed()
		}
	}
	if _vStoreVersion, _ok := sub.Get("store-version"); _ok && _vStoreVersion.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractInt(_vStoreVersion.Leaf); _xok {
			data.StoreVersion = store_version.Version(_x)
			_vStoreVersion.MarkConsumed()
		}
	}
	if _vId, _ok := sub.Get("id"); _ok && _vId.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vId.Leaf); _xok {
			if err := data.RepoId.UnmarshalText([]byte(_x)); err != nil {
				return fmt.Errorf("id: %w", err)
			}
			_vId.MarkConsumed()
		}
	}
	if _vInventoryListType, _ok := sub.Get("inventory_list-type"); _ok && _vInventoryListType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vInventoryListType.Leaf); _xok {
			data.InventoryListType = _x
			_vInventoryListType.MarkConsumed()
		}
	}
	if _vObjectSigType, _ok := sub.Get("object-sig-type"); _ok && _vObjectSigType.Kind == cst.VLeaf {
		if _x, _xok := cst.ExtractString(_vObjectSigType.Leaf); _xok {
			data.ObjectSigType = _x
			_vObjectSigType.MarkConsumed()
		}
	}
	return nil
}

func EncodeTomlV2PublicFrom(data *TomlV2Public, doc *document.Document, container *cst.Node) error {
	{
		v, err := data.PublicKey.MarshalText()
		if err != nil {
			return fmt.Errorf("public-key: %w", err)
		}
		if err := cst.SetAny(container, "public-key", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.StoreVersion != store_version.Version(0) || cst.HasValue(container, "store-version") {
		if err := cst.SetAny(container, "store-version", int(data.StoreVersion)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	{
		v, err := data.RepoId.MarshalText()
		if err != nil {
			return fmt.Errorf("id: %w", err)
		}
		if err := cst.SetAny(container, "id", string(v)); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.InventoryListType != "" || cst.HasValue(container, "inventory_list-type") {
		if err := cst.SetAny(container, "inventory_list-type", data.InventoryListType); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	if data.ObjectSigType != "" || cst.HasValue(container, "object-sig-type") {
		if err := cst.SetAny(container, "object-sig-type", data.ObjectSigType); err != nil {
			return fmt.Errorf("%w", err)
		}
	}
	return nil
}
