// Code generated by tommy; DO NOT EDIT.

package repo_blobs

import (
	"fmt"

	"github.com/amarbel-llc/tommy/pkg/cst"
	"github.com/amarbel-llc/tommy/pkg/document"
)

// Ensure imports are used.
var (
	_ = fmt.Errorf
	_ cst.NodeKind
)

type TomlXDGV0Document struct {
	data     TomlXDGV0
	cstDoc   *document.Document
	consumed map[string]bool
}

func DecodeTomlXDGV0(input []byte) (*TomlXDGV0Document, error) {
	doc, err := document.Parse(input)
	if err != nil {
		return nil, err
	}

	d := &TomlXDGV0Document{cstDoc: doc, consumed: make(map[string]bool)}

	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "public-key"); err == nil {
		if err := d.data.PublicKey.UnmarshalText([]byte(v)); err != nil {
			return nil, fmt.Errorf("public-key: %w", err)
		}
		d.consumed["public-key"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "data"); err == nil {
		d.data.Data = v
		d.consumed["data"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "config"); err == nil {
		d.data.Config = v
		d.consumed["config"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "state"); err == nil {
		d.data.State = v
		d.consumed["state"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "cache"); err == nil {
		d.data.Cache = v
		d.consumed["cache"] = true
	}
	if v, err := document.GetFromContainer[string](d.cstDoc, d.cstDoc.Root(), "runtime"); err == nil {
		d.data.Runtime = v
		d.consumed["runtime"] = true
	}

	return d, nil
}

func (d *TomlXDGV0Document) Data() *TomlXDGV0 { return &d.data }

func (d *TomlXDGV0Document) Encode() ([]byte, error) {
	{
		v, err := d.data.PublicKey.MarshalText()
		if err != nil {
			return nil, fmt.Errorf("public-key: %w", err)
		}
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "public-key", string(v)); err != nil {
			return nil, err
		}
	}
	if d.data.Data != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "data") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "data", d.data.Data); err != nil {
			return nil, err
		}
	}
	if d.data.Config != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "config") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "config", d.data.Config); err != nil {
			return nil, err
		}
	}
	if d.data.State != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "state") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "state", d.data.State); err != nil {
			return nil, err
		}
	}
	if d.data.Cache != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "cache") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "cache", d.data.Cache); err != nil {
			return nil, err
		}
	}
	if d.data.Runtime != "" || d.cstDoc.HasInContainer(d.cstDoc.Root(), "runtime") {
		if err := d.cstDoc.SetInContainer(d.cstDoc.Root(), "runtime", d.data.Runtime); err != nil {
			return nil, err
		}
	}

	return d.cstDoc.Bytes(), nil
}

func (d *TomlXDGV0Document) Undecoded() []string {
	return document.UndecodedKeys(d.cstDoc.Root(), d.consumed)
}
